# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/nomoto/src/StagedLSH/ver1.2/soft/u200/hw/_x/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/pfm_dynamic_memory_subsystem_0.xci
# IP: The module: 'pfm_dynamic_memory_subsystem_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/nomoto/src/StagedLSH/ver1.2/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/bd_d216.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d216 || ORIG_REF_NAME==bd_d216} -quiet] -quiet

# IP: /home/nomoto/src/StagedLSH/ver1.2/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_0/bd_d216_psr_aclk_SLR0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d216_psr_aclk_SLR0_0 || ORIG_REF_NAME==bd_d216_psr_aclk_SLR0_0} -quiet] -quiet

# IP: /home/nomoto/src/StagedLSH/ver1.2/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_1/bd_d216_psr_aclk_SLR1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d216_psr_aclk_SLR1_0 || ORIG_REF_NAME==bd_d216_psr_aclk_SLR1_0} -quiet] -quiet

# IP: /home/nomoto/src/StagedLSH/ver1.2/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_7/bd_d216_psr_aclk2_SLR1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d216_psr_aclk2_SLR1_0 || ORIG_REF_NAME==bd_d216_psr_aclk2_SLR1_0} -quiet] -quiet

# IP: /home/nomoto/src/StagedLSH/ver1.2/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_10/bd_d216_interconnect_S00_AXI_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d216_interconnect_S00_AXI_0 || ORIG_REF_NAME==bd_d216_interconnect_S00_AXI_0} -quiet] -quiet

# IP: /home/nomoto/src/StagedLSH/ver1.2/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_11/bd_d216_interconnect_S02_AXI_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d216_interconnect_S02_AXI_0 || ORIG_REF_NAME==bd_d216_interconnect_S02_AXI_0} -quiet] -quiet

# IP: /home/nomoto/src/StagedLSH/ver1.2/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_12/bd_d216_interconnect_DDR4_MEM00_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d216_interconnect_DDR4_MEM00_0 || ORIG_REF_NAME==bd_d216_interconnect_DDR4_MEM00_0} -quiet] -quiet

# IP: /home/nomoto/src/StagedLSH/ver1.2/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_13/bd_d216_interconnect_DDR4_MEM01_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d216_interconnect_DDR4_MEM01_0 || ORIG_REF_NAME==bd_d216_interconnect_DDR4_MEM01_0} -quiet] -quiet

# IP: /home/nomoto/src/StagedLSH/ver1.2/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_14/bd_d216_interconnect_M00_AXI_MEM00_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d216_interconnect_M00_AXI_MEM00_0 || ORIG_REF_NAME==bd_d216_interconnect_M00_AXI_MEM00_0} -quiet] -quiet

# IP: /home/nomoto/src/StagedLSH/ver1.2/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_15/bd_d216_interconnect_PLRAM_MEM00_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d216_interconnect_PLRAM_MEM00_0 || ORIG_REF_NAME==bd_d216_interconnect_PLRAM_MEM00_0} -quiet] -quiet

# IP: /home/nomoto/src/StagedLSH/ver1.2/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_16/bd_d216_interconnect_PLRAM_MEM01_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d216_interconnect_PLRAM_MEM01_0 || ORIG_REF_NAME==bd_d216_interconnect_PLRAM_MEM01_0} -quiet] -quiet

# IP: /home/nomoto/src/StagedLSH/ver1.2/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_31/bd_d216_vip_S00_AXI_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d216_vip_S00_AXI_0 || ORIG_REF_NAME==bd_d216_vip_S00_AXI_0} -quiet] -quiet

# IP: /home/nomoto/src/StagedLSH/ver1.2/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_32/bd_d216_vip_S01_AXI_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d216_vip_S01_AXI_0 || ORIG_REF_NAME==bd_d216_vip_S01_AXI_0} -quiet] -quiet

# IP: /home/nomoto/src/StagedLSH/ver1.2/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_33/bd_d216_vip_S02_AXI_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d216_vip_S02_AXI_0 || ORIG_REF_NAME==bd_d216_vip_S02_AXI_0} -quiet] -quiet

# IP: /home/nomoto/src/StagedLSH/ver1.2/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_34/bd_d216_vip_S04_AXI_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d216_vip_S04_AXI_0 || ORIG_REF_NAME==bd_d216_vip_S04_AXI_0} -quiet] -quiet

# IP: /home/nomoto/src/StagedLSH/ver1.2/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_35/bd_d216_vip_S05_AXI_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d216_vip_S05_AXI_0 || ORIG_REF_NAME==bd_d216_vip_S05_AXI_0} -quiet] -quiet

# IP: /home/nomoto/src/StagedLSH/ver1.2/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_36/bd_d216_vip_S06_AXI_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d216_vip_S06_AXI_0 || ORIG_REF_NAME==bd_d216_vip_S06_AXI_0} -quiet] -quiet

# IP: /home/nomoto/src/StagedLSH/ver1.2/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_37/bd_d216_vip_S07_AXI_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d216_vip_S07_AXI_0 || ORIG_REF_NAME==bd_d216_vip_S07_AXI_0} -quiet] -quiet

# IP: /home/nomoto/src/StagedLSH/ver1.2/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_38/bd_d216_vip_S08_AXI_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d216_vip_S08_AXI_0 || ORIG_REF_NAME==bd_d216_vip_S08_AXI_0} -quiet] -quiet

# IP: /home/nomoto/src/StagedLSH/ver1.2/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_39/bd_d216_vip_M00_AXI_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d216_vip_M00_AXI_0 || ORIG_REF_NAME==bd_d216_vip_M00_AXI_0} -quiet] -quiet

# IP: /home/nomoto/src/StagedLSH/ver1.2/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_50/bd_d216_rs_M00_AXI_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d216_rs_M00_AXI_0 || ORIG_REF_NAME==bd_d216_rs_M00_AXI_0} -quiet] -quiet

# IP: /home/nomoto/src/StagedLSH/ver1.2/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_17/bd_d216_ddr4_mem00_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d216_ddr4_mem00_0 || ORIG_REF_NAME==bd_d216_ddr4_mem00_0} -quiet] -quiet

# IP: /home/nomoto/src/StagedLSH/ver1.2/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_18/bd_d216_psr_ddr4_mem00_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d216_psr_ddr4_mem00_0 || ORIG_REF_NAME==bd_d216_psr_ddr4_mem00_0} -quiet] -quiet

# IP: /home/nomoto/src/StagedLSH/ver1.2/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_19/bd_d216_ddr4_mem00_ctrl_cc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d216_ddr4_mem00_ctrl_cc_0 || ORIG_REF_NAME==bd_d216_ddr4_mem00_ctrl_cc_0} -quiet] -quiet

# IP: /home/nomoto/src/StagedLSH/ver1.2/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_20/bd_d216_ddr4_mem01_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d216_ddr4_mem01_0 || ORIG_REF_NAME==bd_d216_ddr4_mem01_0} -quiet] -quiet

# IP: /home/nomoto/src/StagedLSH/ver1.2/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_21/bd_d216_psr_ddr4_mem01_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d216_psr_ddr4_mem01_0 || ORIG_REF_NAME==bd_d216_psr_ddr4_mem01_0} -quiet] -quiet

# IP: /home/nomoto/src/StagedLSH/ver1.2/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_22/bd_d216_ddr4_mem01_ctrl_cc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d216_ddr4_mem01_ctrl_cc_0 || ORIG_REF_NAME==bd_d216_ddr4_mem01_ctrl_cc_0} -quiet] -quiet

# IP: /home/nomoto/src/StagedLSH/ver1.2/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_23/bd_d216_calib_concat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d216_calib_concat_0 || ORIG_REF_NAME==bd_d216_calib_concat_0} -quiet] -quiet

# IP: /home/nomoto/src/StagedLSH/ver1.2/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_24/bd_d216_calib_reduce_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d216_calib_reduce_0 || ORIG_REF_NAME==bd_d216_calib_reduce_0} -quiet] -quiet

# IP: /home/nomoto/src/StagedLSH/ver1.2/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_25/bd_d216_calib_vector_concat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d216_calib_vector_concat_0 || ORIG_REF_NAME==bd_d216_calib_vector_concat_0} -quiet] -quiet

# IP: /home/nomoto/src/StagedLSH/ver1.2/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_26/bd_d216_plram_mem00_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d216_plram_mem00_0 || ORIG_REF_NAME==bd_d216_plram_mem00_0} -quiet] -quiet

# IP: /home/nomoto/src/StagedLSH/ver1.2/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_27/bd_d216_plram_mem00_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d216_plram_mem00_bram_0 || ORIG_REF_NAME==bd_d216_plram_mem00_bram_0} -quiet] -quiet

# IP: /home/nomoto/src/StagedLSH/ver1.2/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_28/bd_d216_plram_mem01_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d216_plram_mem01_0 || ORIG_REF_NAME==bd_d216_plram_mem01_0} -quiet] -quiet

# IP: /home/nomoto/src/StagedLSH/ver1.2/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_29/bd_d216_plram_mem01_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d216_plram_mem01_bram_0 || ORIG_REF_NAME==bd_d216_plram_mem01_bram_0} -quiet] -quiet

# IP: /home/nomoto/src/StagedLSH/ver1.2/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_9/bd_d216_psr_ctrl_interconnect_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d216_psr_ctrl_interconnect_0 || ORIG_REF_NAME==bd_d216_psr_ctrl_interconnect_0} -quiet] -quiet

# IP: /home/nomoto/src/StagedLSH/ver1.2/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_30/bd_d216_interconnect_ddrmem_ctrl_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d216_interconnect_ddrmem_ctrl_0 || ORIG_REF_NAME==bd_d216_interconnect_ddrmem_ctrl_0} -quiet] -quiet

# IP: /home/nomoto/src/StagedLSH/ver1.2/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_40/bd_d216_vip_DDR4_MEM00_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d216_vip_DDR4_MEM00_0 || ORIG_REF_NAME==bd_d216_vip_DDR4_MEM00_0} -quiet] -quiet

# IP: /home/nomoto/src/StagedLSH/ver1.2/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_41/bd_d216_vip_ui_clk_DDR4_MEM00_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d216_vip_ui_clk_DDR4_MEM00_0 || ORIG_REF_NAME==bd_d216_vip_ui_clk_DDR4_MEM00_0} -quiet] -quiet

# IP: /home/nomoto/src/StagedLSH/ver1.2/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_42/bd_d216_vip_ui_rst_DDR4_MEM00_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d216_vip_ui_rst_DDR4_MEM00_0 || ORIG_REF_NAME==bd_d216_vip_ui_rst_DDR4_MEM00_0} -quiet] -quiet

# IP: /home/nomoto/src/StagedLSH/ver1.2/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_43/bd_d216_vip_ctrl_DDR4_MEM00_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d216_vip_ctrl_DDR4_MEM00_0 || ORIG_REF_NAME==bd_d216_vip_ctrl_DDR4_MEM00_0} -quiet] -quiet

# IP: /home/nomoto/src/StagedLSH/ver1.2/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_44/bd_d216_vip_DDR4_MEM01_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d216_vip_DDR4_MEM01_0 || ORIG_REF_NAME==bd_d216_vip_DDR4_MEM01_0} -quiet] -quiet

# IP: /home/nomoto/src/StagedLSH/ver1.2/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_45/bd_d216_vip_ui_clk_DDR4_MEM01_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d216_vip_ui_clk_DDR4_MEM01_0 || ORIG_REF_NAME==bd_d216_vip_ui_clk_DDR4_MEM01_0} -quiet] -quiet

# IP: /home/nomoto/src/StagedLSH/ver1.2/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_46/bd_d216_vip_ui_rst_DDR4_MEM01_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d216_vip_ui_rst_DDR4_MEM01_0 || ORIG_REF_NAME==bd_d216_vip_ui_rst_DDR4_MEM01_0} -quiet] -quiet

# IP: /home/nomoto/src/StagedLSH/ver1.2/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_47/bd_d216_vip_ctrl_DDR4_MEM01_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d216_vip_ctrl_DDR4_MEM01_0 || ORIG_REF_NAME==bd_d216_vip_ctrl_DDR4_MEM01_0} -quiet] -quiet

# IP: /home/nomoto/src/StagedLSH/ver1.2/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_48/bd_d216_vip_PLRAM_MEM00_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d216_vip_PLRAM_MEM00_0 || ORIG_REF_NAME==bd_d216_vip_PLRAM_MEM00_0} -quiet] -quiet

# IP: /home/nomoto/src/StagedLSH/ver1.2/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_49/bd_d216_vip_PLRAM_MEM01_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d216_vip_PLRAM_MEM01_0 || ORIG_REF_NAME==bd_d216_vip_PLRAM_MEM01_0} -quiet] -quiet

# XDC: /home/nomoto/src/StagedLSH/ver1.2/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/bd_d216_ooc.xdc

# XDC: /home/nomoto/src/StagedLSH/ver1.2/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/pfm_dynamic_memory_subsystem_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'pfm_dynamic_memory_subsystem_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/nomoto/src/StagedLSH/ver1.2/soft/u200/hw/_x/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/pfm_dynamic_memory_subsystem_0.xci
# IP: The module: 'pfm_dynamic_memory_subsystem_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/nomoto/src/StagedLSH/ver1.2/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/bd_d216.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d216 || ORIG_REF_NAME==bd_d216} -quiet] -quiet

# IP: /home/nomoto/src/StagedLSH/ver1.2/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_0/bd_d216_psr_aclk_SLR0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d216_psr_aclk_SLR0_0 || ORIG_REF_NAME==bd_d216_psr_aclk_SLR0_0} -quiet] -quiet

# IP: /home/nomoto/src/StagedLSH/ver1.2/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_1/bd_d216_psr_aclk_SLR1_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d216_psr_aclk_SLR1_0 || ORIG_REF_NAME==bd_d216_psr_aclk_SLR1_0} -quiet] -quiet

# IP: /home/nomoto/src/StagedLSH/ver1.2/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_7/bd_d216_psr_aclk2_SLR1_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d216_psr_aclk2_SLR1_0 || ORIG_REF_NAME==bd_d216_psr_aclk2_SLR1_0} -quiet] -quiet

# IP: /home/nomoto/src/StagedLSH/ver1.2/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_10/bd_d216_interconnect_S00_AXI_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d216_interconnect_S00_AXI_0 || ORIG_REF_NAME==bd_d216_interconnect_S00_AXI_0} -quiet] -quiet

# IP: /home/nomoto/src/StagedLSH/ver1.2/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_11/bd_d216_interconnect_S02_AXI_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d216_interconnect_S02_AXI_0 || ORIG_REF_NAME==bd_d216_interconnect_S02_AXI_0} -quiet] -quiet

# IP: /home/nomoto/src/StagedLSH/ver1.2/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_12/bd_d216_interconnect_DDR4_MEM00_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d216_interconnect_DDR4_MEM00_0 || ORIG_REF_NAME==bd_d216_interconnect_DDR4_MEM00_0} -quiet] -quiet

# IP: /home/nomoto/src/StagedLSH/ver1.2/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_13/bd_d216_interconnect_DDR4_MEM01_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d216_interconnect_DDR4_MEM01_0 || ORIG_REF_NAME==bd_d216_interconnect_DDR4_MEM01_0} -quiet] -quiet

# IP: /home/nomoto/src/StagedLSH/ver1.2/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_14/bd_d216_interconnect_M00_AXI_MEM00_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d216_interconnect_M00_AXI_MEM00_0 || ORIG_REF_NAME==bd_d216_interconnect_M00_AXI_MEM00_0} -quiet] -quiet

# IP: /home/nomoto/src/StagedLSH/ver1.2/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_15/bd_d216_interconnect_PLRAM_MEM00_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d216_interconnect_PLRAM_MEM00_0 || ORIG_REF_NAME==bd_d216_interconnect_PLRAM_MEM00_0} -quiet] -quiet

# IP: /home/nomoto/src/StagedLSH/ver1.2/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_16/bd_d216_interconnect_PLRAM_MEM01_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d216_interconnect_PLRAM_MEM01_0 || ORIG_REF_NAME==bd_d216_interconnect_PLRAM_MEM01_0} -quiet] -quiet

# IP: /home/nomoto/src/StagedLSH/ver1.2/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_31/bd_d216_vip_S00_AXI_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d216_vip_S00_AXI_0 || ORIG_REF_NAME==bd_d216_vip_S00_AXI_0} -quiet] -quiet

# IP: /home/nomoto/src/StagedLSH/ver1.2/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_32/bd_d216_vip_S01_AXI_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d216_vip_S01_AXI_0 || ORIG_REF_NAME==bd_d216_vip_S01_AXI_0} -quiet] -quiet

# IP: /home/nomoto/src/StagedLSH/ver1.2/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_33/bd_d216_vip_S02_AXI_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d216_vip_S02_AXI_0 || ORIG_REF_NAME==bd_d216_vip_S02_AXI_0} -quiet] -quiet

# IP: /home/nomoto/src/StagedLSH/ver1.2/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_34/bd_d216_vip_S04_AXI_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d216_vip_S04_AXI_0 || ORIG_REF_NAME==bd_d216_vip_S04_AXI_0} -quiet] -quiet

# IP: /home/nomoto/src/StagedLSH/ver1.2/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_35/bd_d216_vip_S05_AXI_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d216_vip_S05_AXI_0 || ORIG_REF_NAME==bd_d216_vip_S05_AXI_0} -quiet] -quiet

# IP: /home/nomoto/src/StagedLSH/ver1.2/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_36/bd_d216_vip_S06_AXI_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d216_vip_S06_AXI_0 || ORIG_REF_NAME==bd_d216_vip_S06_AXI_0} -quiet] -quiet

# IP: /home/nomoto/src/StagedLSH/ver1.2/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_37/bd_d216_vip_S07_AXI_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d216_vip_S07_AXI_0 || ORIG_REF_NAME==bd_d216_vip_S07_AXI_0} -quiet] -quiet

# IP: /home/nomoto/src/StagedLSH/ver1.2/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_38/bd_d216_vip_S08_AXI_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d216_vip_S08_AXI_0 || ORIG_REF_NAME==bd_d216_vip_S08_AXI_0} -quiet] -quiet

# IP: /home/nomoto/src/StagedLSH/ver1.2/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_39/bd_d216_vip_M00_AXI_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d216_vip_M00_AXI_0 || ORIG_REF_NAME==bd_d216_vip_M00_AXI_0} -quiet] -quiet

# IP: /home/nomoto/src/StagedLSH/ver1.2/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_50/bd_d216_rs_M00_AXI_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d216_rs_M00_AXI_0 || ORIG_REF_NAME==bd_d216_rs_M00_AXI_0} -quiet] -quiet

# IP: /home/nomoto/src/StagedLSH/ver1.2/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_17/bd_d216_ddr4_mem00_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d216_ddr4_mem00_0 || ORIG_REF_NAME==bd_d216_ddr4_mem00_0} -quiet] -quiet

# IP: /home/nomoto/src/StagedLSH/ver1.2/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_18/bd_d216_psr_ddr4_mem00_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d216_psr_ddr4_mem00_0 || ORIG_REF_NAME==bd_d216_psr_ddr4_mem00_0} -quiet] -quiet

# IP: /home/nomoto/src/StagedLSH/ver1.2/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_19/bd_d216_ddr4_mem00_ctrl_cc_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d216_ddr4_mem00_ctrl_cc_0 || ORIG_REF_NAME==bd_d216_ddr4_mem00_ctrl_cc_0} -quiet] -quiet

# IP: /home/nomoto/src/StagedLSH/ver1.2/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_20/bd_d216_ddr4_mem01_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d216_ddr4_mem01_0 || ORIG_REF_NAME==bd_d216_ddr4_mem01_0} -quiet] -quiet

# IP: /home/nomoto/src/StagedLSH/ver1.2/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_21/bd_d216_psr_ddr4_mem01_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d216_psr_ddr4_mem01_0 || ORIG_REF_NAME==bd_d216_psr_ddr4_mem01_0} -quiet] -quiet

# IP: /home/nomoto/src/StagedLSH/ver1.2/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_22/bd_d216_ddr4_mem01_ctrl_cc_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d216_ddr4_mem01_ctrl_cc_0 || ORIG_REF_NAME==bd_d216_ddr4_mem01_ctrl_cc_0} -quiet] -quiet

# IP: /home/nomoto/src/StagedLSH/ver1.2/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_23/bd_d216_calib_concat_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d216_calib_concat_0 || ORIG_REF_NAME==bd_d216_calib_concat_0} -quiet] -quiet

# IP: /home/nomoto/src/StagedLSH/ver1.2/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_24/bd_d216_calib_reduce_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d216_calib_reduce_0 || ORIG_REF_NAME==bd_d216_calib_reduce_0} -quiet] -quiet

# IP: /home/nomoto/src/StagedLSH/ver1.2/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_25/bd_d216_calib_vector_concat_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d216_calib_vector_concat_0 || ORIG_REF_NAME==bd_d216_calib_vector_concat_0} -quiet] -quiet

# IP: /home/nomoto/src/StagedLSH/ver1.2/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_26/bd_d216_plram_mem00_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d216_plram_mem00_0 || ORIG_REF_NAME==bd_d216_plram_mem00_0} -quiet] -quiet

# IP: /home/nomoto/src/StagedLSH/ver1.2/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_27/bd_d216_plram_mem00_bram_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d216_plram_mem00_bram_0 || ORIG_REF_NAME==bd_d216_plram_mem00_bram_0} -quiet] -quiet

# IP: /home/nomoto/src/StagedLSH/ver1.2/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_28/bd_d216_plram_mem01_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d216_plram_mem01_0 || ORIG_REF_NAME==bd_d216_plram_mem01_0} -quiet] -quiet

# IP: /home/nomoto/src/StagedLSH/ver1.2/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_29/bd_d216_plram_mem01_bram_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d216_plram_mem01_bram_0 || ORIG_REF_NAME==bd_d216_plram_mem01_bram_0} -quiet] -quiet

# IP: /home/nomoto/src/StagedLSH/ver1.2/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_9/bd_d216_psr_ctrl_interconnect_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d216_psr_ctrl_interconnect_0 || ORIG_REF_NAME==bd_d216_psr_ctrl_interconnect_0} -quiet] -quiet

# IP: /home/nomoto/src/StagedLSH/ver1.2/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_30/bd_d216_interconnect_ddrmem_ctrl_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d216_interconnect_ddrmem_ctrl_0 || ORIG_REF_NAME==bd_d216_interconnect_ddrmem_ctrl_0} -quiet] -quiet

# IP: /home/nomoto/src/StagedLSH/ver1.2/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_40/bd_d216_vip_DDR4_MEM00_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d216_vip_DDR4_MEM00_0 || ORIG_REF_NAME==bd_d216_vip_DDR4_MEM00_0} -quiet] -quiet

# IP: /home/nomoto/src/StagedLSH/ver1.2/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_41/bd_d216_vip_ui_clk_DDR4_MEM00_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d216_vip_ui_clk_DDR4_MEM00_0 || ORIG_REF_NAME==bd_d216_vip_ui_clk_DDR4_MEM00_0} -quiet] -quiet

# IP: /home/nomoto/src/StagedLSH/ver1.2/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_42/bd_d216_vip_ui_rst_DDR4_MEM00_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d216_vip_ui_rst_DDR4_MEM00_0 || ORIG_REF_NAME==bd_d216_vip_ui_rst_DDR4_MEM00_0} -quiet] -quiet

# IP: /home/nomoto/src/StagedLSH/ver1.2/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_43/bd_d216_vip_ctrl_DDR4_MEM00_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d216_vip_ctrl_DDR4_MEM00_0 || ORIG_REF_NAME==bd_d216_vip_ctrl_DDR4_MEM00_0} -quiet] -quiet

# IP: /home/nomoto/src/StagedLSH/ver1.2/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_44/bd_d216_vip_DDR4_MEM01_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d216_vip_DDR4_MEM01_0 || ORIG_REF_NAME==bd_d216_vip_DDR4_MEM01_0} -quiet] -quiet

# IP: /home/nomoto/src/StagedLSH/ver1.2/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_45/bd_d216_vip_ui_clk_DDR4_MEM01_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d216_vip_ui_clk_DDR4_MEM01_0 || ORIG_REF_NAME==bd_d216_vip_ui_clk_DDR4_MEM01_0} -quiet] -quiet

# IP: /home/nomoto/src/StagedLSH/ver1.2/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_46/bd_d216_vip_ui_rst_DDR4_MEM01_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d216_vip_ui_rst_DDR4_MEM01_0 || ORIG_REF_NAME==bd_d216_vip_ui_rst_DDR4_MEM01_0} -quiet] -quiet

# IP: /home/nomoto/src/StagedLSH/ver1.2/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_47/bd_d216_vip_ctrl_DDR4_MEM01_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d216_vip_ctrl_DDR4_MEM01_0 || ORIG_REF_NAME==bd_d216_vip_ctrl_DDR4_MEM01_0} -quiet] -quiet

# IP: /home/nomoto/src/StagedLSH/ver1.2/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_48/bd_d216_vip_PLRAM_MEM00_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d216_vip_PLRAM_MEM00_0 || ORIG_REF_NAME==bd_d216_vip_PLRAM_MEM00_0} -quiet] -quiet

# IP: /home/nomoto/src/StagedLSH/ver1.2/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_49/bd_d216_vip_PLRAM_MEM01_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d216_vip_PLRAM_MEM01_0 || ORIG_REF_NAME==bd_d216_vip_PLRAM_MEM01_0} -quiet] -quiet

# XDC: /home/nomoto/src/StagedLSH/ver1.2/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/bd_d216_ooc.xdc

# XDC: /home/nomoto/src/StagedLSH/ver1.2/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/pfm_dynamic_memory_subsystem_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'pfm_dynamic_memory_subsystem_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
