# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/nomoto/src/StagedLSH/ver1.3/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_27/bd_d216_plram_mem00_bram_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_d216_plram_mem00_bram_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/nomoto/src/StagedLSH/ver1.3/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_27/bd_d216_plram_mem00_bram_0_slr.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_d216_plram_mem00_bram_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/nomoto/src/StagedLSH/ver1.3/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_27/bd_d216_plram_mem00_bram_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_d216_plram_mem00_bram_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/nomoto/src/StagedLSH/ver1.3/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_memory_subsystem_0/bd_0/ip/ip_27/bd_d216_plram_mem00_bram_0_slr.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_d216_plram_mem00_bram_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
