// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module table_serch_hd_cal96 (
        ap_ready,
        flame96,
        temp_flame96_V_read,
        ap_return
);


output   ap_ready;
input  [95:0] flame96;
input  [95:0] temp_flame96_V_read;
output  [6:0] ap_return;

wire   [94:0] trunc_ln1350_127_fu_906_p1;
wire   [94:0] trunc_ln1350_126_fu_902_p1;
wire   [93:0] trunc_ln1350_125_fu_898_p1;
wire   [93:0] trunc_ln1350_124_fu_894_p1;
wire   [92:0] trunc_ln1350_123_fu_890_p1;
wire   [92:0] trunc_ln1350_122_fu_886_p1;
wire   [91:0] trunc_ln1350_121_fu_882_p1;
wire   [91:0] trunc_ln1350_120_fu_878_p1;
wire   [90:0] trunc_ln1350_119_fu_874_p1;
wire   [90:0] trunc_ln1350_118_fu_870_p1;
wire   [89:0] trunc_ln1350_117_fu_866_p1;
wire   [89:0] trunc_ln1350_116_fu_862_p1;
wire   [88:0] trunc_ln1350_115_fu_858_p1;
wire   [88:0] trunc_ln1350_114_fu_854_p1;
wire   [87:0] trunc_ln1350_113_fu_850_p1;
wire   [87:0] trunc_ln1350_112_fu_846_p1;
wire   [86:0] trunc_ln1350_111_fu_842_p1;
wire   [86:0] trunc_ln1350_110_fu_838_p1;
wire   [85:0] trunc_ln1350_109_fu_834_p1;
wire   [85:0] trunc_ln1350_108_fu_830_p1;
wire   [84:0] trunc_ln1350_107_fu_826_p1;
wire   [84:0] trunc_ln1350_106_fu_822_p1;
wire   [83:0] trunc_ln1350_105_fu_818_p1;
wire   [83:0] trunc_ln1350_104_fu_814_p1;
wire   [82:0] trunc_ln1350_103_fu_810_p1;
wire   [82:0] trunc_ln1350_102_fu_806_p1;
wire   [81:0] trunc_ln1350_101_fu_802_p1;
wire   [81:0] trunc_ln1350_100_fu_798_p1;
wire   [80:0] trunc_ln1350_99_fu_794_p1;
wire   [80:0] trunc_ln1350_98_fu_790_p1;
wire   [79:0] trunc_ln1350_97_fu_786_p1;
wire   [79:0] trunc_ln1350_96_fu_782_p1;
wire   [78:0] trunc_ln1350_95_fu_778_p1;
wire   [78:0] trunc_ln1350_94_fu_774_p1;
wire   [77:0] trunc_ln1350_93_fu_770_p1;
wire   [77:0] trunc_ln1350_92_fu_766_p1;
wire   [76:0] trunc_ln1350_91_fu_762_p1;
wire   [76:0] trunc_ln1350_90_fu_758_p1;
wire   [75:0] trunc_ln1350_89_fu_754_p1;
wire   [75:0] trunc_ln1350_88_fu_750_p1;
wire   [74:0] trunc_ln1350_87_fu_746_p1;
wire   [74:0] trunc_ln1350_86_fu_742_p1;
wire   [73:0] trunc_ln1350_85_fu_738_p1;
wire   [73:0] trunc_ln1350_84_fu_734_p1;
wire   [72:0] trunc_ln1350_83_fu_730_p1;
wire   [72:0] trunc_ln1350_82_fu_726_p1;
wire   [71:0] trunc_ln1350_81_fu_722_p1;
wire   [71:0] trunc_ln1350_80_fu_718_p1;
wire   [70:0] trunc_ln1350_79_fu_714_p1;
wire   [70:0] trunc_ln1350_78_fu_710_p1;
wire   [69:0] trunc_ln1350_77_fu_706_p1;
wire   [69:0] trunc_ln1350_76_fu_702_p1;
wire   [68:0] trunc_ln1350_75_fu_698_p1;
wire   [68:0] trunc_ln1350_74_fu_694_p1;
wire   [67:0] trunc_ln1350_73_fu_690_p1;
wire   [67:0] trunc_ln1350_72_fu_686_p1;
wire   [66:0] trunc_ln1350_71_fu_682_p1;
wire   [66:0] trunc_ln1350_70_fu_678_p1;
wire   [65:0] trunc_ln1350_69_fu_674_p1;
wire   [65:0] trunc_ln1350_68_fu_670_p1;
wire   [64:0] trunc_ln1350_67_fu_666_p1;
wire   [64:0] trunc_ln1350_66_fu_662_p1;
wire   [63:0] trunc_ln1350_65_fu_658_p1;
wire   [63:0] trunc_ln1350_64_fu_654_p1;
wire   [62:0] trunc_ln1350_63_fu_650_p1;
wire   [62:0] trunc_ln1350_62_fu_646_p1;
wire   [61:0] trunc_ln1350_61_fu_642_p1;
wire   [61:0] trunc_ln1350_60_fu_638_p1;
wire   [60:0] trunc_ln1350_59_fu_634_p1;
wire   [60:0] trunc_ln1350_58_fu_630_p1;
wire   [59:0] trunc_ln1350_57_fu_626_p1;
wire   [59:0] trunc_ln1350_56_fu_622_p1;
wire   [58:0] trunc_ln1350_55_fu_618_p1;
wire   [58:0] trunc_ln1350_54_fu_614_p1;
wire   [57:0] trunc_ln1350_53_fu_610_p1;
wire   [57:0] trunc_ln1350_52_fu_606_p1;
wire   [56:0] trunc_ln1350_51_fu_602_p1;
wire   [56:0] trunc_ln1350_50_fu_598_p1;
wire   [55:0] trunc_ln1350_49_fu_594_p1;
wire   [55:0] trunc_ln1350_48_fu_590_p1;
wire   [54:0] trunc_ln1350_47_fu_586_p1;
wire   [54:0] trunc_ln1350_46_fu_582_p1;
wire   [53:0] trunc_ln1350_45_fu_578_p1;
wire   [53:0] trunc_ln1350_44_fu_574_p1;
wire   [52:0] trunc_ln1350_43_fu_570_p1;
wire   [52:0] trunc_ln1350_42_fu_566_p1;
wire   [51:0] trunc_ln1350_41_fu_562_p1;
wire   [51:0] trunc_ln1350_40_fu_558_p1;
wire   [50:0] trunc_ln1350_39_fu_554_p1;
wire   [50:0] trunc_ln1350_38_fu_550_p1;
wire   [49:0] trunc_ln1350_37_fu_546_p1;
wire   [49:0] trunc_ln1350_36_fu_542_p1;
wire   [48:0] trunc_ln1350_35_fu_538_p1;
wire   [48:0] trunc_ln1350_34_fu_534_p1;
wire   [47:0] trunc_ln1350_33_fu_530_p1;
wire   [47:0] trunc_ln1350_32_fu_526_p1;
wire   [46:0] trunc_ln1350_31_fu_522_p1;
wire   [46:0] trunc_ln1350_30_fu_518_p1;
wire   [45:0] trunc_ln1350_29_fu_514_p1;
wire   [45:0] trunc_ln1350_28_fu_510_p1;
wire   [44:0] trunc_ln1350_27_fu_506_p1;
wire   [44:0] trunc_ln1350_26_fu_502_p1;
wire   [43:0] trunc_ln1350_25_fu_498_p1;
wire   [43:0] trunc_ln1350_24_fu_494_p1;
wire   [42:0] trunc_ln1350_23_fu_490_p1;
wire   [42:0] trunc_ln1350_22_fu_486_p1;
wire   [41:0] trunc_ln1350_21_fu_482_p1;
wire   [41:0] trunc_ln1350_20_fu_478_p1;
wire   [40:0] trunc_ln1350_19_fu_474_p1;
wire   [40:0] trunc_ln1350_18_fu_470_p1;
wire   [39:0] trunc_ln1350_17_fu_466_p1;
wire   [39:0] trunc_ln1350_16_fu_462_p1;
wire   [38:0] trunc_ln1350_15_fu_458_p1;
wire   [38:0] trunc_ln1350_14_fu_454_p1;
wire   [37:0] trunc_ln1350_13_fu_450_p1;
wire   [37:0] trunc_ln1350_12_fu_446_p1;
wire   [36:0] trunc_ln1350_11_fu_442_p1;
wire   [36:0] trunc_ln1350_10_fu_438_p1;
wire   [35:0] trunc_ln1350_9_fu_434_p1;
wire   [35:0] trunc_ln1350_8_fu_430_p1;
wire   [34:0] trunc_ln1350_7_fu_426_p1;
wire   [34:0] trunc_ln1350_6_fu_422_p1;
wire   [33:0] trunc_ln1350_5_fu_418_p1;
wire   [33:0] trunc_ln1350_4_fu_414_p1;
wire   [32:0] trunc_ln1350_3_fu_410_p1;
wire   [32:0] trunc_ln1350_2_fu_406_p1;
wire   [31:0] trunc_ln1350_1_fu_402_p1;
wire   [31:0] trunc_ln1350_fu_398_p1;
wire   [30:0] trunc_ln819_61_fu_1538_p1;
wire   [30:0] trunc_ln819_60_fu_1534_p1;
wire   [29:0] trunc_ln819_59_fu_1530_p1;
wire   [29:0] trunc_ln819_58_fu_1526_p1;
wire   [28:0] trunc_ln819_57_fu_1522_p1;
wire   [28:0] trunc_ln819_56_fu_1518_p1;
wire   [27:0] trunc_ln819_55_fu_1514_p1;
wire   [27:0] trunc_ln819_54_fu_1510_p1;
wire   [26:0] trunc_ln819_53_fu_1506_p1;
wire   [26:0] trunc_ln819_52_fu_1502_p1;
wire   [25:0] trunc_ln819_51_fu_1498_p1;
wire   [25:0] trunc_ln819_50_fu_1494_p1;
wire   [24:0] trunc_ln819_49_fu_1490_p1;
wire   [24:0] trunc_ln819_48_fu_1486_p1;
wire   [23:0] trunc_ln819_47_fu_1482_p1;
wire   [23:0] trunc_ln819_46_fu_1478_p1;
wire   [22:0] trunc_ln819_45_fu_1474_p1;
wire   [22:0] trunc_ln819_44_fu_1470_p1;
wire   [21:0] trunc_ln819_43_fu_1466_p1;
wire   [21:0] trunc_ln819_42_fu_1462_p1;
wire   [20:0] trunc_ln819_41_fu_1458_p1;
wire   [20:0] trunc_ln819_40_fu_1454_p1;
wire   [19:0] trunc_ln819_39_fu_1450_p1;
wire   [19:0] trunc_ln819_38_fu_1446_p1;
wire   [18:0] trunc_ln819_37_fu_1442_p1;
wire   [18:0] trunc_ln819_36_fu_1438_p1;
wire   [17:0] trunc_ln819_35_fu_1434_p1;
wire   [17:0] trunc_ln819_34_fu_1430_p1;
wire   [16:0] trunc_ln819_33_fu_1426_p1;
wire   [16:0] trunc_ln819_32_fu_1422_p1;
wire   [15:0] trunc_ln819_31_fu_1418_p1;
wire   [15:0] trunc_ln819_30_fu_1414_p1;
wire   [14:0] trunc_ln819_29_fu_1410_p1;
wire   [14:0] trunc_ln819_28_fu_1406_p1;
wire   [13:0] trunc_ln819_27_fu_1402_p1;
wire   [13:0] trunc_ln819_26_fu_1398_p1;
wire   [12:0] trunc_ln819_25_fu_1394_p1;
wire   [12:0] trunc_ln819_24_fu_1390_p1;
wire   [11:0] trunc_ln819_23_fu_1386_p1;
wire   [11:0] trunc_ln819_22_fu_1382_p1;
wire   [10:0] trunc_ln819_21_fu_1378_p1;
wire   [10:0] trunc_ln819_20_fu_1374_p1;
wire   [9:0] trunc_ln819_19_fu_1370_p1;
wire   [9:0] trunc_ln819_18_fu_1366_p1;
wire   [8:0] trunc_ln819_17_fu_1362_p1;
wire   [8:0] trunc_ln819_16_fu_1358_p1;
wire   [7:0] trunc_ln819_15_fu_1354_p1;
wire   [7:0] trunc_ln819_14_fu_1350_p1;
wire   [6:0] trunc_ln819_13_fu_1346_p1;
wire   [6:0] trunc_ln819_12_fu_1342_p1;
wire   [5:0] trunc_ln819_11_fu_1338_p1;
wire   [5:0] trunc_ln819_10_fu_1334_p1;
wire   [4:0] trunc_ln819_9_fu_1330_p1;
wire   [4:0] trunc_ln819_8_fu_1326_p1;
wire   [3:0] trunc_ln819_7_fu_1322_p1;
wire   [3:0] trunc_ln819_6_fu_1318_p1;
wire   [2:0] trunc_ln819_5_fu_1314_p1;
wire   [2:0] trunc_ln819_4_fu_1310_p1;
wire   [1:0] trunc_ln819_3_fu_1306_p1;
wire   [1:0] trunc_ln819_2_fu_1302_p1;
wire   [0:0] trunc_ln819_1_fu_1298_p1;
wire   [0:0] trunc_ln819_fu_1294_p1;
wire   [0:0] xor_ln1158_30_fu_1728_p2;
wire   [1:0] xor_ln1158_29_fu_1722_p2;
wire   [0:0] tmp_fu_1738_p3;
wire   [2:0] xor_ln1158_28_fu_1716_p2;
wire   [0:0] tmp_57_fu_1750_p3;
wire   [3:0] xor_ln1158_27_fu_1710_p2;
wire   [0:0] tmp_58_fu_1762_p3;
wire   [4:0] xor_ln1158_26_fu_1704_p2;
wire   [0:0] tmp_59_fu_1774_p3;
wire   [5:0] xor_ln1158_25_fu_1698_p2;
wire   [0:0] tmp_60_fu_1786_p3;
wire   [6:0] xor_ln1158_24_fu_1692_p2;
wire   [0:0] tmp_61_fu_1798_p3;
wire   [7:0] xor_ln1158_23_fu_1686_p2;
wire   [0:0] tmp_62_fu_1810_p3;
wire   [8:0] xor_ln1158_22_fu_1680_p2;
wire   [0:0] tmp_63_fu_1822_p3;
wire   [9:0] xor_ln1158_21_fu_1674_p2;
wire   [0:0] tmp_64_fu_1834_p3;
wire   [10:0] xor_ln1158_20_fu_1668_p2;
wire   [0:0] tmp_65_fu_1846_p3;
wire   [11:0] xor_ln1158_19_fu_1662_p2;
wire   [0:0] tmp_66_fu_1858_p3;
wire   [12:0] xor_ln1158_18_fu_1656_p2;
wire   [0:0] tmp_67_fu_1870_p3;
wire   [13:0] xor_ln1158_17_fu_1650_p2;
wire   [0:0] tmp_68_fu_1882_p3;
wire   [14:0] xor_ln1158_16_fu_1644_p2;
wire   [0:0] tmp_69_fu_1894_p3;
wire   [15:0] xor_ln1158_15_fu_1638_p2;
wire   [0:0] tmp_70_fu_1906_p3;
wire   [16:0] xor_ln1158_14_fu_1632_p2;
wire   [0:0] tmp_71_fu_1918_p3;
wire   [17:0] xor_ln1158_13_fu_1626_p2;
wire   [0:0] tmp_72_fu_1930_p3;
wire   [18:0] xor_ln1158_12_fu_1620_p2;
wire   [0:0] tmp_73_fu_1942_p3;
wire   [19:0] xor_ln1158_11_fu_1614_p2;
wire   [0:0] tmp_74_fu_1954_p3;
wire   [20:0] xor_ln1158_10_fu_1608_p2;
wire   [0:0] tmp_75_fu_1966_p3;
wire   [21:0] xor_ln1158_9_fu_1602_p2;
wire   [0:0] tmp_76_fu_1978_p3;
wire   [22:0] xor_ln1158_8_fu_1596_p2;
wire   [0:0] tmp_77_fu_1990_p3;
wire   [23:0] xor_ln1158_7_fu_1590_p2;
wire   [0:0] tmp_78_fu_2002_p3;
wire   [24:0] xor_ln1158_6_fu_1584_p2;
wire   [0:0] tmp_79_fu_2014_p3;
wire   [25:0] xor_ln1158_5_fu_1578_p2;
wire   [0:0] tmp_80_fu_2026_p3;
wire   [26:0] xor_ln1158_4_fu_1572_p2;
wire   [0:0] tmp_81_fu_2038_p3;
wire   [27:0] xor_ln1158_3_fu_1566_p2;
wire   [0:0] tmp_82_fu_2050_p3;
wire   [28:0] xor_ln1158_2_fu_1560_p2;
wire   [0:0] tmp_83_fu_2062_p3;
wire   [29:0] xor_ln1158_1_fu_1554_p2;
wire   [0:0] tmp_84_fu_2074_p3;
wire   [30:0] xor_ln1158_fu_1548_p2;
wire   [0:0] tmp_85_fu_2086_p3;
wire   [31:0] xor_ln819_fu_1542_p2;
wire   [0:0] tmp_86_fu_2098_p3;
wire   [32:0] xor_ln1350_63_fu_1288_p2;
wire   [0:0] tmp_87_fu_2110_p3;
wire   [33:0] xor_ln1350_62_fu_1282_p2;
wire   [0:0] tmp_88_fu_2122_p3;
wire   [34:0] xor_ln1350_61_fu_1276_p2;
wire   [0:0] tmp_89_fu_2134_p3;
wire   [35:0] xor_ln1350_60_fu_1270_p2;
wire   [0:0] tmp_90_fu_2146_p3;
wire   [36:0] xor_ln1350_59_fu_1264_p2;
wire   [0:0] tmp_91_fu_2158_p3;
wire   [37:0] xor_ln1350_58_fu_1258_p2;
wire   [0:0] tmp_92_fu_2170_p3;
wire   [38:0] xor_ln1350_57_fu_1252_p2;
wire   [0:0] tmp_93_fu_2182_p3;
wire   [39:0] xor_ln1350_56_fu_1246_p2;
wire   [0:0] tmp_94_fu_2194_p3;
wire   [40:0] xor_ln1350_55_fu_1240_p2;
wire   [0:0] tmp_95_fu_2206_p3;
wire   [41:0] xor_ln1350_54_fu_1234_p2;
wire   [0:0] tmp_96_fu_2218_p3;
wire   [42:0] xor_ln1350_53_fu_1228_p2;
wire   [0:0] tmp_97_fu_2230_p3;
wire   [43:0] xor_ln1350_52_fu_1222_p2;
wire   [0:0] tmp_98_fu_2242_p3;
wire   [44:0] xor_ln1350_51_fu_1216_p2;
wire   [0:0] tmp_99_fu_2254_p3;
wire   [45:0] xor_ln1350_50_fu_1210_p2;
wire   [0:0] tmp_100_fu_2266_p3;
wire   [46:0] xor_ln1350_49_fu_1204_p2;
wire   [0:0] tmp_101_fu_2278_p3;
wire   [47:0] xor_ln1350_48_fu_1198_p2;
wire   [0:0] tmp_102_fu_2290_p3;
wire   [48:0] xor_ln1350_47_fu_1192_p2;
wire   [0:0] tmp_103_fu_2302_p3;
wire   [49:0] xor_ln1350_46_fu_1186_p2;
wire   [0:0] tmp_104_fu_2314_p3;
wire   [50:0] xor_ln1350_45_fu_1180_p2;
wire   [0:0] tmp_105_fu_2326_p3;
wire   [51:0] xor_ln1350_44_fu_1174_p2;
wire   [0:0] tmp_106_fu_2338_p3;
wire   [52:0] xor_ln1350_43_fu_1168_p2;
wire   [0:0] tmp_107_fu_2350_p3;
wire   [53:0] xor_ln1350_42_fu_1162_p2;
wire   [0:0] tmp_108_fu_2362_p3;
wire   [54:0] xor_ln1350_41_fu_1156_p2;
wire   [0:0] tmp_109_fu_2374_p3;
wire   [55:0] xor_ln1350_40_fu_1150_p2;
wire   [0:0] tmp_110_fu_2386_p3;
wire   [56:0] xor_ln1350_39_fu_1144_p2;
wire   [0:0] tmp_111_fu_2398_p3;
wire   [57:0] xor_ln1350_38_fu_1138_p2;
wire   [0:0] tmp_112_fu_2410_p3;
wire   [58:0] xor_ln1350_37_fu_1132_p2;
wire   [0:0] tmp_113_fu_2422_p3;
wire   [59:0] xor_ln1350_36_fu_1126_p2;
wire   [0:0] tmp_114_fu_2434_p3;
wire   [60:0] xor_ln1350_35_fu_1120_p2;
wire   [0:0] tmp_115_fu_2446_p3;
wire   [61:0] xor_ln1350_34_fu_1114_p2;
wire   [0:0] tmp_116_fu_2458_p3;
wire   [62:0] xor_ln1350_33_fu_1108_p2;
wire   [0:0] tmp_117_fu_2470_p3;
wire   [63:0] xor_ln1350_32_fu_1102_p2;
wire   [0:0] tmp_118_fu_2482_p3;
wire   [64:0] xor_ln1350_31_fu_1096_p2;
wire   [0:0] tmp_119_fu_2494_p3;
wire   [65:0] xor_ln1350_30_fu_1090_p2;
wire   [0:0] tmp_120_fu_2506_p3;
wire   [66:0] xor_ln1350_29_fu_1084_p2;
wire   [0:0] tmp_121_fu_2518_p3;
wire   [67:0] xor_ln1350_28_fu_1078_p2;
wire   [0:0] tmp_122_fu_2530_p3;
wire   [68:0] xor_ln1350_27_fu_1072_p2;
wire   [0:0] tmp_123_fu_2542_p3;
wire   [69:0] xor_ln1350_26_fu_1066_p2;
wire   [0:0] tmp_124_fu_2554_p3;
wire   [70:0] xor_ln1350_25_fu_1060_p2;
wire   [0:0] tmp_125_fu_2566_p3;
wire   [71:0] xor_ln1350_24_fu_1054_p2;
wire   [0:0] tmp_126_fu_2578_p3;
wire   [72:0] xor_ln1350_23_fu_1048_p2;
wire   [0:0] tmp_127_fu_2590_p3;
wire   [73:0] xor_ln1350_22_fu_1042_p2;
wire   [0:0] tmp_128_fu_2602_p3;
wire   [74:0] xor_ln1350_21_fu_1036_p2;
wire   [0:0] tmp_129_fu_2614_p3;
wire   [75:0] xor_ln1350_20_fu_1030_p2;
wire   [0:0] tmp_130_fu_2626_p3;
wire   [76:0] xor_ln1350_19_fu_1024_p2;
wire   [0:0] tmp_131_fu_2638_p3;
wire   [77:0] xor_ln1350_18_fu_1018_p2;
wire   [0:0] tmp_132_fu_2650_p3;
wire   [78:0] xor_ln1350_17_fu_1012_p2;
wire   [0:0] tmp_133_fu_2662_p3;
wire   [79:0] xor_ln1350_16_fu_1006_p2;
wire   [0:0] tmp_134_fu_2674_p3;
wire   [80:0] xor_ln1350_15_fu_1000_p2;
wire   [0:0] tmp_135_fu_2686_p3;
wire   [81:0] xor_ln1350_14_fu_994_p2;
wire   [0:0] tmp_136_fu_2698_p3;
wire   [82:0] xor_ln1350_13_fu_988_p2;
wire   [0:0] tmp_137_fu_2710_p3;
wire   [83:0] xor_ln1350_12_fu_982_p2;
wire   [0:0] tmp_138_fu_2722_p3;
wire   [84:0] xor_ln1350_11_fu_976_p2;
wire   [0:0] tmp_139_fu_2734_p3;
wire   [85:0] xor_ln1350_10_fu_970_p2;
wire   [0:0] tmp_140_fu_2746_p3;
wire   [86:0] xor_ln1350_9_fu_964_p2;
wire   [0:0] tmp_141_fu_2758_p3;
wire   [87:0] xor_ln1350_8_fu_958_p2;
wire   [0:0] tmp_142_fu_2770_p3;
wire   [88:0] xor_ln1350_7_fu_952_p2;
wire   [0:0] tmp_143_fu_2782_p3;
wire   [89:0] xor_ln1350_6_fu_946_p2;
wire   [0:0] tmp_144_fu_2794_p3;
wire   [90:0] xor_ln1350_5_fu_940_p2;
wire   [0:0] tmp_145_fu_2806_p3;
wire   [91:0] xor_ln1350_4_fu_934_p2;
wire   [0:0] tmp_146_fu_2818_p3;
wire   [92:0] xor_ln1350_3_fu_928_p2;
wire   [0:0] tmp_147_fu_2830_p3;
wire   [93:0] xor_ln1350_2_fu_922_p2;
wire   [0:0] tmp_148_fu_2842_p3;
wire   [94:0] xor_ln1350_1_fu_916_p2;
wire   [0:0] tmp_149_fu_2854_p3;
wire   [95:0] ret_fu_910_p2;
wire   [0:0] tmp_150_fu_2866_p3;
wire   [1:0] zext_ln1158_fu_1734_p1;
wire   [1:0] zext_ln1158_31_fu_2106_p1;
wire   [1:0] add_ln1159_fu_2878_p2;
wire   [1:0] zext_ln1159_62_fu_2874_p1;
wire   [1:0] add_ln1159_1_fu_2884_p2;
wire   [1:0] zext_ln1158_3_fu_1770_p1;
wire   [1:0] zext_ln1158_2_fu_1758_p1;
wire   [1:0] add_ln1159_2_fu_2894_p2;
wire   [1:0] zext_ln1158_1_fu_1746_p1;
wire   [1:0] add_ln1159_3_fu_2900_p2;
wire   [2:0] zext_ln1159_1_fu_2906_p1;
wire   [2:0] zext_ln1159_fu_2890_p1;
wire   [2:0] add_ln1159_4_fu_2910_p2;
wire   [1:0] zext_ln1158_4_fu_1782_p1;
wire   [1:0] zext_ln1158_7_fu_1818_p1;
wire   [1:0] add_ln1159_5_fu_2920_p2;
wire   [1:0] zext_ln1158_5_fu_1794_p1;
wire   [1:0] add_ln1159_6_fu_2926_p2;
wire   [1:0] zext_ln1158_9_fu_1842_p1;
wire   [1:0] zext_ln1158_8_fu_1830_p1;
wire   [1:0] add_ln1159_7_fu_2936_p2;
wire   [1:0] zext_ln1158_6_fu_1806_p1;
wire   [1:0] add_ln1159_8_fu_2942_p2;
wire   [2:0] zext_ln1159_4_fu_2948_p1;
wire   [2:0] zext_ln1159_3_fu_2932_p1;
wire   [2:0] add_ln1159_9_fu_2952_p2;
wire   [3:0] zext_ln1159_5_fu_2958_p1;
wire   [3:0] zext_ln1159_2_fu_2916_p1;
wire   [3:0] add_ln1159_10_fu_2962_p2;
wire   [1:0] zext_ln1158_10_fu_1854_p1;
wire   [1:0] zext_ln1158_13_fu_1890_p1;
wire   [1:0] add_ln1159_11_fu_2972_p2;
wire   [1:0] zext_ln1158_11_fu_1866_p1;
wire   [1:0] add_ln1159_12_fu_2978_p2;
wire   [1:0] zext_ln1158_15_fu_1914_p1;
wire   [1:0] zext_ln1158_14_fu_1902_p1;
wire   [1:0] add_ln1159_13_fu_2988_p2;
wire   [1:0] zext_ln1158_12_fu_1878_p1;
wire   [1:0] add_ln1159_14_fu_2994_p2;
wire   [2:0] zext_ln1159_8_fu_3000_p1;
wire   [2:0] zext_ln1159_7_fu_2984_p1;
wire   [2:0] add_ln1159_15_fu_3004_p2;
wire   [1:0] zext_ln1158_16_fu_1926_p1;
wire   [1:0] zext_ln1158_19_fu_1962_p1;
wire   [1:0] add_ln1159_16_fu_3014_p2;
wire   [1:0] zext_ln1158_17_fu_1938_p1;
wire   [1:0] add_ln1159_17_fu_3020_p2;
wire   [1:0] zext_ln1158_21_fu_1986_p1;
wire   [1:0] zext_ln1158_20_fu_1974_p1;
wire   [1:0] add_ln1159_18_fu_3030_p2;
wire   [1:0] zext_ln1158_18_fu_1950_p1;
wire   [1:0] add_ln1159_19_fu_3036_p2;
wire   [2:0] zext_ln1159_11_fu_3042_p1;
wire   [2:0] zext_ln1159_10_fu_3026_p1;
wire   [2:0] add_ln1159_20_fu_3046_p2;
wire   [3:0] zext_ln1159_12_fu_3052_p1;
wire   [3:0] zext_ln1159_9_fu_3010_p1;
wire   [3:0] add_ln1159_21_fu_3056_p2;
wire   [4:0] zext_ln1159_13_fu_3062_p1;
wire   [4:0] zext_ln1159_6_fu_2968_p1;
wire   [4:0] add_ln1159_22_fu_3066_p2;
wire   [1:0] zext_ln1158_22_fu_1998_p1;
wire   [1:0] zext_ln1158_25_fu_2034_p1;
wire   [1:0] add_ln1159_23_fu_3076_p2;
wire   [1:0] zext_ln1158_23_fu_2010_p1;
wire   [1:0] add_ln1159_24_fu_3082_p2;
wire   [1:0] zext_ln1158_27_fu_2058_p1;
wire   [1:0] zext_ln1158_26_fu_2046_p1;
wire   [1:0] add_ln1159_25_fu_3092_p2;
wire   [1:0] zext_ln1158_24_fu_2022_p1;
wire   [1:0] add_ln1159_26_fu_3098_p2;
wire   [2:0] zext_ln1159_16_fu_3104_p1;
wire   [2:0] zext_ln1159_15_fu_3088_p1;
wire   [2:0] add_ln1159_27_fu_3108_p2;
wire   [1:0] zext_ln1158_28_fu_2070_p1;
wire   [1:0] zext_ln1158_30_fu_2094_p1;
wire   [1:0] add_ln1159_28_fu_3118_p2;
wire   [1:0] zext_ln1158_29_fu_2082_p1;
wire   [1:0] add_ln1159_29_fu_3124_p2;
wire   [1:0] zext_ln1158_32_fu_2118_p1;
wire   [1:0] zext_ln1158_35_fu_2154_p1;
wire   [1:0] add_ln1159_30_fu_3134_p2;
wire   [1:0] zext_ln1158_33_fu_2130_p1;
wire   [1:0] add_ln1159_31_fu_3140_p2;
wire   [2:0] zext_ln1159_19_fu_3146_p1;
wire   [2:0] zext_ln1159_18_fu_3130_p1;
wire   [2:0] add_ln1159_32_fu_3150_p2;
wire   [3:0] zext_ln1159_20_fu_3156_p1;
wire   [3:0] zext_ln1159_17_fu_3114_p1;
wire   [3:0] add_ln1159_33_fu_3160_p2;
wire   [1:0] zext_ln1158_37_fu_2178_p1;
wire   [1:0] zext_ln1158_36_fu_2166_p1;
wire   [1:0] add_ln1159_34_fu_3170_p2;
wire   [1:0] zext_ln1158_34_fu_2142_p1;
wire   [1:0] add_ln1159_35_fu_3176_p2;
wire   [1:0] zext_ln1158_38_fu_2190_p1;
wire   [1:0] zext_ln1158_41_fu_2226_p1;
wire   [1:0] add_ln1159_36_fu_3186_p2;
wire   [1:0] zext_ln1158_39_fu_2202_p1;
wire   [1:0] add_ln1159_37_fu_3192_p2;
wire   [2:0] zext_ln1159_23_fu_3198_p1;
wire   [2:0] zext_ln1159_22_fu_3182_p1;
wire   [2:0] add_ln1159_38_fu_3202_p2;
wire   [1:0] zext_ln1158_43_fu_2250_p1;
wire   [1:0] zext_ln1158_42_fu_2238_p1;
wire   [1:0] add_ln1159_39_fu_3212_p2;
wire   [1:0] zext_ln1158_40_fu_2214_p1;
wire   [1:0] add_ln1159_40_fu_3218_p2;
wire   [1:0] zext_ln1158_44_fu_2262_p1;
wire   [1:0] zext_ln1158_47_fu_2298_p1;
wire   [1:0] add_ln1159_41_fu_3228_p2;
wire   [1:0] zext_ln1158_45_fu_2274_p1;
wire   [1:0] add_ln1159_42_fu_3234_p2;
wire   [2:0] zext_ln1159_26_fu_3240_p1;
wire   [2:0] zext_ln1159_25_fu_3224_p1;
wire   [2:0] add_ln1159_43_fu_3244_p2;
wire   [3:0] zext_ln1159_27_fu_3250_p1;
wire   [3:0] zext_ln1159_24_fu_3208_p1;
wire   [3:0] add_ln1159_44_fu_3254_p2;
wire   [4:0] zext_ln1159_28_fu_3260_p1;
wire   [4:0] zext_ln1159_21_fu_3166_p1;
wire   [4:0] add_ln1159_45_fu_3264_p2;
wire   [5:0] zext_ln1159_29_fu_3270_p1;
wire   [5:0] zext_ln1159_14_fu_3072_p1;
wire   [5:0] add_ln1159_46_fu_3274_p2;
wire   [1:0] zext_ln1158_49_fu_2322_p1;
wire   [1:0] zext_ln1158_48_fu_2310_p1;
wire   [1:0] add_ln1159_47_fu_3284_p2;
wire   [1:0] zext_ln1158_46_fu_2286_p1;
wire   [1:0] add_ln1159_48_fu_3290_p2;
wire   [1:0] zext_ln1158_50_fu_2334_p1;
wire   [1:0] zext_ln1158_53_fu_2370_p1;
wire   [1:0] add_ln1159_49_fu_3300_p2;
wire   [1:0] zext_ln1158_51_fu_2346_p1;
wire   [1:0] add_ln1159_50_fu_3306_p2;
wire   [2:0] zext_ln1159_32_fu_3312_p1;
wire   [2:0] zext_ln1159_31_fu_3296_p1;
wire   [2:0] add_ln1159_51_fu_3316_p2;
wire   [1:0] zext_ln1158_55_fu_2394_p1;
wire   [1:0] zext_ln1158_54_fu_2382_p1;
wire   [1:0] add_ln1159_52_fu_3326_p2;
wire   [1:0] zext_ln1158_52_fu_2358_p1;
wire   [1:0] add_ln1159_53_fu_3332_p2;
wire   [1:0] zext_ln1158_56_fu_2406_p1;
wire   [1:0] zext_ln1158_59_fu_2442_p1;
wire   [1:0] add_ln1159_54_fu_3342_p2;
wire   [1:0] zext_ln1158_57_fu_2418_p1;
wire   [1:0] add_ln1159_55_fu_3348_p2;
wire   [2:0] zext_ln1159_35_fu_3354_p1;
wire   [2:0] zext_ln1159_34_fu_3338_p1;
wire   [2:0] add_ln1159_56_fu_3358_p2;
wire   [3:0] zext_ln1159_36_fu_3364_p1;
wire   [3:0] zext_ln1159_33_fu_3322_p1;
wire   [3:0] add_ln1159_57_fu_3368_p2;
wire   [1:0] zext_ln1158_61_fu_2466_p1;
wire   [1:0] zext_ln1158_60_fu_2454_p1;
wire   [1:0] add_ln1159_58_fu_3378_p2;
wire   [1:0] zext_ln1158_58_fu_2430_p1;
wire   [1:0] add_ln1159_59_fu_3384_p2;
wire   [1:0] zext_ln1158_62_fu_2478_p1;
wire   [1:0] zext_ln1158_65_fu_2514_p1;
wire   [1:0] add_ln1159_60_fu_3394_p2;
wire   [1:0] zext_ln1158_63_fu_2490_p1;
wire   [1:0] add_ln1159_61_fu_3400_p2;
wire   [2:0] zext_ln1159_39_fu_3406_p1;
wire   [2:0] zext_ln1159_38_fu_3390_p1;
wire   [2:0] add_ln1159_62_fu_3410_p2;
wire   [1:0] zext_ln1158_67_fu_2538_p1;
wire   [1:0] zext_ln1158_66_fu_2526_p1;
wire   [1:0] add_ln1159_63_fu_3420_p2;
wire   [1:0] zext_ln1158_64_fu_2502_p1;
wire   [1:0] add_ln1159_64_fu_3426_p2;
wire   [1:0] zext_ln1158_68_fu_2550_p1;
wire   [1:0] zext_ln1158_71_fu_2586_p1;
wire   [1:0] add_ln1159_65_fu_3436_p2;
wire   [1:0] zext_ln1158_69_fu_2562_p1;
wire   [1:0] add_ln1159_66_fu_3442_p2;
wire   [2:0] zext_ln1159_42_fu_3448_p1;
wire   [2:0] zext_ln1159_41_fu_3432_p1;
wire   [2:0] add_ln1159_67_fu_3452_p2;
wire   [3:0] zext_ln1159_43_fu_3458_p1;
wire   [3:0] zext_ln1159_40_fu_3416_p1;
wire   [3:0] add_ln1159_68_fu_3462_p2;
wire   [4:0] zext_ln1159_44_fu_3468_p1;
wire   [4:0] zext_ln1159_37_fu_3374_p1;
wire   [4:0] add_ln1159_69_fu_3472_p2;
wire   [1:0] zext_ln1158_73_fu_2610_p1;
wire   [1:0] zext_ln1158_72_fu_2598_p1;
wire   [1:0] add_ln1159_70_fu_3482_p2;
wire   [1:0] zext_ln1158_70_fu_2574_p1;
wire   [1:0] add_ln1159_71_fu_3488_p2;
wire   [1:0] zext_ln1158_74_fu_2622_p1;
wire   [1:0] zext_ln1158_77_fu_2658_p1;
wire   [1:0] add_ln1159_72_fu_3498_p2;
wire   [1:0] zext_ln1158_75_fu_2634_p1;
wire   [1:0] add_ln1159_73_fu_3504_p2;
wire   [2:0] zext_ln1159_47_fu_3510_p1;
wire   [2:0] zext_ln1159_46_fu_3494_p1;
wire   [2:0] add_ln1159_74_fu_3514_p2;
wire   [1:0] zext_ln1158_79_fu_2682_p1;
wire   [1:0] zext_ln1158_78_fu_2670_p1;
wire   [1:0] add_ln1159_75_fu_3524_p2;
wire   [1:0] zext_ln1158_76_fu_2646_p1;
wire   [1:0] add_ln1159_76_fu_3530_p2;
wire   [1:0] zext_ln1158_80_fu_2694_p1;
wire   [1:0] zext_ln1158_83_fu_2730_p1;
wire   [1:0] add_ln1159_77_fu_3540_p2;
wire   [1:0] zext_ln1158_81_fu_2706_p1;
wire   [1:0] add_ln1159_78_fu_3546_p2;
wire   [2:0] zext_ln1159_50_fu_3552_p1;
wire   [2:0] zext_ln1159_49_fu_3536_p1;
wire   [2:0] add_ln1159_79_fu_3556_p2;
wire   [3:0] zext_ln1159_51_fu_3562_p1;
wire   [3:0] zext_ln1159_48_fu_3520_p1;
wire   [3:0] add_ln1159_80_fu_3566_p2;
wire   [1:0] zext_ln1158_85_fu_2754_p1;
wire   [1:0] zext_ln1158_84_fu_2742_p1;
wire   [1:0] add_ln1159_81_fu_3576_p2;
wire   [1:0] zext_ln1158_82_fu_2718_p1;
wire   [1:0] add_ln1159_82_fu_3582_p2;
wire   [1:0] zext_ln1158_86_fu_2766_p1;
wire   [1:0] zext_ln1158_89_fu_2802_p1;
wire   [1:0] add_ln1159_83_fu_3592_p2;
wire   [1:0] zext_ln1158_87_fu_2778_p1;
wire   [1:0] add_ln1159_84_fu_3598_p2;
wire   [2:0] zext_ln1159_54_fu_3604_p1;
wire   [2:0] zext_ln1159_53_fu_3588_p1;
wire   [2:0] add_ln1159_85_fu_3608_p2;
wire   [1:0] zext_ln1158_91_fu_2826_p1;
wire   [1:0] zext_ln1158_90_fu_2814_p1;
wire   [1:0] add_ln1159_86_fu_3618_p2;
wire   [1:0] zext_ln1158_88_fu_2790_p1;
wire   [1:0] add_ln1159_87_fu_3624_p2;
wire   [1:0] zext_ln1158_92_fu_2838_p1;
wire   [1:0] zext_ln1158_94_fu_2862_p1;
wire   [1:0] add_ln1159_88_fu_3634_p2;
wire   [1:0] zext_ln1158_93_fu_2850_p1;
wire   [1:0] add_ln1159_89_fu_3640_p2;
wire   [2:0] zext_ln1159_57_fu_3646_p1;
wire   [2:0] zext_ln1159_56_fu_3630_p1;
wire   [2:0] add_ln1159_90_fu_3650_p2;
wire   [3:0] zext_ln1159_58_fu_3656_p1;
wire   [3:0] zext_ln1159_55_fu_3614_p1;
wire   [3:0] add_ln1159_91_fu_3660_p2;
wire   [4:0] zext_ln1159_59_fu_3666_p1;
wire   [4:0] zext_ln1159_52_fu_3572_p1;
wire   [4:0] add_ln1159_92_fu_3670_p2;
wire   [5:0] zext_ln1159_60_fu_3676_p1;
wire   [5:0] zext_ln1159_45_fu_3478_p1;
wire   [5:0] add_ln1159_93_fu_3680_p2;
wire   [6:0] zext_ln1159_61_fu_3686_p1;
wire   [6:0] zext_ln1159_30_fu_3280_p1;

assign add_ln1159_10_fu_2962_p2 = (zext_ln1159_5_fu_2958_p1 + zext_ln1159_2_fu_2916_p1);

assign add_ln1159_11_fu_2972_p2 = (zext_ln1158_10_fu_1854_p1 + zext_ln1158_13_fu_1890_p1);

assign add_ln1159_12_fu_2978_p2 = (add_ln1159_11_fu_2972_p2 + zext_ln1158_11_fu_1866_p1);

assign add_ln1159_13_fu_2988_p2 = (zext_ln1158_15_fu_1914_p1 + zext_ln1158_14_fu_1902_p1);

assign add_ln1159_14_fu_2994_p2 = (add_ln1159_13_fu_2988_p2 + zext_ln1158_12_fu_1878_p1);

assign add_ln1159_15_fu_3004_p2 = (zext_ln1159_8_fu_3000_p1 + zext_ln1159_7_fu_2984_p1);

assign add_ln1159_16_fu_3014_p2 = (zext_ln1158_16_fu_1926_p1 + zext_ln1158_19_fu_1962_p1);

assign add_ln1159_17_fu_3020_p2 = (add_ln1159_16_fu_3014_p2 + zext_ln1158_17_fu_1938_p1);

assign add_ln1159_18_fu_3030_p2 = (zext_ln1158_21_fu_1986_p1 + zext_ln1158_20_fu_1974_p1);

assign add_ln1159_19_fu_3036_p2 = (add_ln1159_18_fu_3030_p2 + zext_ln1158_18_fu_1950_p1);

assign add_ln1159_1_fu_2884_p2 = (add_ln1159_fu_2878_p2 + zext_ln1159_62_fu_2874_p1);

assign add_ln1159_20_fu_3046_p2 = (zext_ln1159_11_fu_3042_p1 + zext_ln1159_10_fu_3026_p1);

assign add_ln1159_21_fu_3056_p2 = (zext_ln1159_12_fu_3052_p1 + zext_ln1159_9_fu_3010_p1);

assign add_ln1159_22_fu_3066_p2 = (zext_ln1159_13_fu_3062_p1 + zext_ln1159_6_fu_2968_p1);

assign add_ln1159_23_fu_3076_p2 = (zext_ln1158_22_fu_1998_p1 + zext_ln1158_25_fu_2034_p1);

assign add_ln1159_24_fu_3082_p2 = (add_ln1159_23_fu_3076_p2 + zext_ln1158_23_fu_2010_p1);

assign add_ln1159_25_fu_3092_p2 = (zext_ln1158_27_fu_2058_p1 + zext_ln1158_26_fu_2046_p1);

assign add_ln1159_26_fu_3098_p2 = (add_ln1159_25_fu_3092_p2 + zext_ln1158_24_fu_2022_p1);

assign add_ln1159_27_fu_3108_p2 = (zext_ln1159_16_fu_3104_p1 + zext_ln1159_15_fu_3088_p1);

assign add_ln1159_28_fu_3118_p2 = (zext_ln1158_28_fu_2070_p1 + zext_ln1158_30_fu_2094_p1);

assign add_ln1159_29_fu_3124_p2 = (add_ln1159_28_fu_3118_p2 + zext_ln1158_29_fu_2082_p1);

assign add_ln1159_2_fu_2894_p2 = (zext_ln1158_3_fu_1770_p1 + zext_ln1158_2_fu_1758_p1);

assign add_ln1159_30_fu_3134_p2 = (zext_ln1158_32_fu_2118_p1 + zext_ln1158_35_fu_2154_p1);

assign add_ln1159_31_fu_3140_p2 = (add_ln1159_30_fu_3134_p2 + zext_ln1158_33_fu_2130_p1);

assign add_ln1159_32_fu_3150_p2 = (zext_ln1159_19_fu_3146_p1 + zext_ln1159_18_fu_3130_p1);

assign add_ln1159_33_fu_3160_p2 = (zext_ln1159_20_fu_3156_p1 + zext_ln1159_17_fu_3114_p1);

assign add_ln1159_34_fu_3170_p2 = (zext_ln1158_37_fu_2178_p1 + zext_ln1158_36_fu_2166_p1);

assign add_ln1159_35_fu_3176_p2 = (add_ln1159_34_fu_3170_p2 + zext_ln1158_34_fu_2142_p1);

assign add_ln1159_36_fu_3186_p2 = (zext_ln1158_38_fu_2190_p1 + zext_ln1158_41_fu_2226_p1);

assign add_ln1159_37_fu_3192_p2 = (add_ln1159_36_fu_3186_p2 + zext_ln1158_39_fu_2202_p1);

assign add_ln1159_38_fu_3202_p2 = (zext_ln1159_23_fu_3198_p1 + zext_ln1159_22_fu_3182_p1);

assign add_ln1159_39_fu_3212_p2 = (zext_ln1158_43_fu_2250_p1 + zext_ln1158_42_fu_2238_p1);

assign add_ln1159_3_fu_2900_p2 = (add_ln1159_2_fu_2894_p2 + zext_ln1158_1_fu_1746_p1);

assign add_ln1159_40_fu_3218_p2 = (add_ln1159_39_fu_3212_p2 + zext_ln1158_40_fu_2214_p1);

assign add_ln1159_41_fu_3228_p2 = (zext_ln1158_44_fu_2262_p1 + zext_ln1158_47_fu_2298_p1);

assign add_ln1159_42_fu_3234_p2 = (add_ln1159_41_fu_3228_p2 + zext_ln1158_45_fu_2274_p1);

assign add_ln1159_43_fu_3244_p2 = (zext_ln1159_26_fu_3240_p1 + zext_ln1159_25_fu_3224_p1);

assign add_ln1159_44_fu_3254_p2 = (zext_ln1159_27_fu_3250_p1 + zext_ln1159_24_fu_3208_p1);

assign add_ln1159_45_fu_3264_p2 = (zext_ln1159_28_fu_3260_p1 + zext_ln1159_21_fu_3166_p1);

assign add_ln1159_46_fu_3274_p2 = (zext_ln1159_29_fu_3270_p1 + zext_ln1159_14_fu_3072_p1);

assign add_ln1159_47_fu_3284_p2 = (zext_ln1158_49_fu_2322_p1 + zext_ln1158_48_fu_2310_p1);

assign add_ln1159_48_fu_3290_p2 = (add_ln1159_47_fu_3284_p2 + zext_ln1158_46_fu_2286_p1);

assign add_ln1159_49_fu_3300_p2 = (zext_ln1158_50_fu_2334_p1 + zext_ln1158_53_fu_2370_p1);

assign add_ln1159_4_fu_2910_p2 = (zext_ln1159_1_fu_2906_p1 + zext_ln1159_fu_2890_p1);

assign add_ln1159_50_fu_3306_p2 = (add_ln1159_49_fu_3300_p2 + zext_ln1158_51_fu_2346_p1);

assign add_ln1159_51_fu_3316_p2 = (zext_ln1159_32_fu_3312_p1 + zext_ln1159_31_fu_3296_p1);

assign add_ln1159_52_fu_3326_p2 = (zext_ln1158_55_fu_2394_p1 + zext_ln1158_54_fu_2382_p1);

assign add_ln1159_53_fu_3332_p2 = (add_ln1159_52_fu_3326_p2 + zext_ln1158_52_fu_2358_p1);

assign add_ln1159_54_fu_3342_p2 = (zext_ln1158_56_fu_2406_p1 + zext_ln1158_59_fu_2442_p1);

assign add_ln1159_55_fu_3348_p2 = (add_ln1159_54_fu_3342_p2 + zext_ln1158_57_fu_2418_p1);

assign add_ln1159_56_fu_3358_p2 = (zext_ln1159_35_fu_3354_p1 + zext_ln1159_34_fu_3338_p1);

assign add_ln1159_57_fu_3368_p2 = (zext_ln1159_36_fu_3364_p1 + zext_ln1159_33_fu_3322_p1);

assign add_ln1159_58_fu_3378_p2 = (zext_ln1158_61_fu_2466_p1 + zext_ln1158_60_fu_2454_p1);

assign add_ln1159_59_fu_3384_p2 = (add_ln1159_58_fu_3378_p2 + zext_ln1158_58_fu_2430_p1);

assign add_ln1159_5_fu_2920_p2 = (zext_ln1158_4_fu_1782_p1 + zext_ln1158_7_fu_1818_p1);

assign add_ln1159_60_fu_3394_p2 = (zext_ln1158_62_fu_2478_p1 + zext_ln1158_65_fu_2514_p1);

assign add_ln1159_61_fu_3400_p2 = (add_ln1159_60_fu_3394_p2 + zext_ln1158_63_fu_2490_p1);

assign add_ln1159_62_fu_3410_p2 = (zext_ln1159_39_fu_3406_p1 + zext_ln1159_38_fu_3390_p1);

assign add_ln1159_63_fu_3420_p2 = (zext_ln1158_67_fu_2538_p1 + zext_ln1158_66_fu_2526_p1);

assign add_ln1159_64_fu_3426_p2 = (add_ln1159_63_fu_3420_p2 + zext_ln1158_64_fu_2502_p1);

assign add_ln1159_65_fu_3436_p2 = (zext_ln1158_68_fu_2550_p1 + zext_ln1158_71_fu_2586_p1);

assign add_ln1159_66_fu_3442_p2 = (add_ln1159_65_fu_3436_p2 + zext_ln1158_69_fu_2562_p1);

assign add_ln1159_67_fu_3452_p2 = (zext_ln1159_42_fu_3448_p1 + zext_ln1159_41_fu_3432_p1);

assign add_ln1159_68_fu_3462_p2 = (zext_ln1159_43_fu_3458_p1 + zext_ln1159_40_fu_3416_p1);

assign add_ln1159_69_fu_3472_p2 = (zext_ln1159_44_fu_3468_p1 + zext_ln1159_37_fu_3374_p1);

assign add_ln1159_6_fu_2926_p2 = (add_ln1159_5_fu_2920_p2 + zext_ln1158_5_fu_1794_p1);

assign add_ln1159_70_fu_3482_p2 = (zext_ln1158_73_fu_2610_p1 + zext_ln1158_72_fu_2598_p1);

assign add_ln1159_71_fu_3488_p2 = (add_ln1159_70_fu_3482_p2 + zext_ln1158_70_fu_2574_p1);

assign add_ln1159_72_fu_3498_p2 = (zext_ln1158_74_fu_2622_p1 + zext_ln1158_77_fu_2658_p1);

assign add_ln1159_73_fu_3504_p2 = (add_ln1159_72_fu_3498_p2 + zext_ln1158_75_fu_2634_p1);

assign add_ln1159_74_fu_3514_p2 = (zext_ln1159_47_fu_3510_p1 + zext_ln1159_46_fu_3494_p1);

assign add_ln1159_75_fu_3524_p2 = (zext_ln1158_79_fu_2682_p1 + zext_ln1158_78_fu_2670_p1);

assign add_ln1159_76_fu_3530_p2 = (add_ln1159_75_fu_3524_p2 + zext_ln1158_76_fu_2646_p1);

assign add_ln1159_77_fu_3540_p2 = (zext_ln1158_80_fu_2694_p1 + zext_ln1158_83_fu_2730_p1);

assign add_ln1159_78_fu_3546_p2 = (add_ln1159_77_fu_3540_p2 + zext_ln1158_81_fu_2706_p1);

assign add_ln1159_79_fu_3556_p2 = (zext_ln1159_50_fu_3552_p1 + zext_ln1159_49_fu_3536_p1);

assign add_ln1159_7_fu_2936_p2 = (zext_ln1158_9_fu_1842_p1 + zext_ln1158_8_fu_1830_p1);

assign add_ln1159_80_fu_3566_p2 = (zext_ln1159_51_fu_3562_p1 + zext_ln1159_48_fu_3520_p1);

assign add_ln1159_81_fu_3576_p2 = (zext_ln1158_85_fu_2754_p1 + zext_ln1158_84_fu_2742_p1);

assign add_ln1159_82_fu_3582_p2 = (add_ln1159_81_fu_3576_p2 + zext_ln1158_82_fu_2718_p1);

assign add_ln1159_83_fu_3592_p2 = (zext_ln1158_86_fu_2766_p1 + zext_ln1158_89_fu_2802_p1);

assign add_ln1159_84_fu_3598_p2 = (add_ln1159_83_fu_3592_p2 + zext_ln1158_87_fu_2778_p1);

assign add_ln1159_85_fu_3608_p2 = (zext_ln1159_54_fu_3604_p1 + zext_ln1159_53_fu_3588_p1);

assign add_ln1159_86_fu_3618_p2 = (zext_ln1158_91_fu_2826_p1 + zext_ln1158_90_fu_2814_p1);

assign add_ln1159_87_fu_3624_p2 = (add_ln1159_86_fu_3618_p2 + zext_ln1158_88_fu_2790_p1);

assign add_ln1159_88_fu_3634_p2 = (zext_ln1158_92_fu_2838_p1 + zext_ln1158_94_fu_2862_p1);

assign add_ln1159_89_fu_3640_p2 = (add_ln1159_88_fu_3634_p2 + zext_ln1158_93_fu_2850_p1);

assign add_ln1159_8_fu_2942_p2 = (add_ln1159_7_fu_2936_p2 + zext_ln1158_6_fu_1806_p1);

assign add_ln1159_90_fu_3650_p2 = (zext_ln1159_57_fu_3646_p1 + zext_ln1159_56_fu_3630_p1);

assign add_ln1159_91_fu_3660_p2 = (zext_ln1159_58_fu_3656_p1 + zext_ln1159_55_fu_3614_p1);

assign add_ln1159_92_fu_3670_p2 = (zext_ln1159_59_fu_3666_p1 + zext_ln1159_52_fu_3572_p1);

assign add_ln1159_93_fu_3680_p2 = (zext_ln1159_60_fu_3676_p1 + zext_ln1159_45_fu_3478_p1);

assign add_ln1159_9_fu_2952_p2 = (zext_ln1159_4_fu_2948_p1 + zext_ln1159_3_fu_2932_p1);

assign add_ln1159_fu_2878_p2 = (zext_ln1158_fu_1734_p1 + zext_ln1158_31_fu_2106_p1);

assign ap_ready = 1'b1;

assign ap_return = (zext_ln1159_61_fu_3686_p1 + zext_ln1159_30_fu_3280_p1);

assign ret_fu_910_p2 = (temp_flame96_V_read ^ flame96);

assign tmp_100_fu_2266_p3 = xor_ln1350_50_fu_1210_p2[32'd45];

assign tmp_101_fu_2278_p3 = xor_ln1350_49_fu_1204_p2[32'd46];

assign tmp_102_fu_2290_p3 = xor_ln1350_48_fu_1198_p2[32'd47];

assign tmp_103_fu_2302_p3 = xor_ln1350_47_fu_1192_p2[32'd48];

assign tmp_104_fu_2314_p3 = xor_ln1350_46_fu_1186_p2[32'd49];

assign tmp_105_fu_2326_p3 = xor_ln1350_45_fu_1180_p2[32'd50];

assign tmp_106_fu_2338_p3 = xor_ln1350_44_fu_1174_p2[32'd51];

assign tmp_107_fu_2350_p3 = xor_ln1350_43_fu_1168_p2[32'd52];

assign tmp_108_fu_2362_p3 = xor_ln1350_42_fu_1162_p2[32'd53];

assign tmp_109_fu_2374_p3 = xor_ln1350_41_fu_1156_p2[32'd54];

assign tmp_110_fu_2386_p3 = xor_ln1350_40_fu_1150_p2[32'd55];

assign tmp_111_fu_2398_p3 = xor_ln1350_39_fu_1144_p2[32'd56];

assign tmp_112_fu_2410_p3 = xor_ln1350_38_fu_1138_p2[32'd57];

assign tmp_113_fu_2422_p3 = xor_ln1350_37_fu_1132_p2[32'd58];

assign tmp_114_fu_2434_p3 = xor_ln1350_36_fu_1126_p2[32'd59];

assign tmp_115_fu_2446_p3 = xor_ln1350_35_fu_1120_p2[32'd60];

assign tmp_116_fu_2458_p3 = xor_ln1350_34_fu_1114_p2[32'd61];

assign tmp_117_fu_2470_p3 = xor_ln1350_33_fu_1108_p2[32'd62];

assign tmp_118_fu_2482_p3 = xor_ln1350_32_fu_1102_p2[32'd63];

assign tmp_119_fu_2494_p3 = xor_ln1350_31_fu_1096_p2[32'd64];

assign tmp_120_fu_2506_p3 = xor_ln1350_30_fu_1090_p2[32'd65];

assign tmp_121_fu_2518_p3 = xor_ln1350_29_fu_1084_p2[32'd66];

assign tmp_122_fu_2530_p3 = xor_ln1350_28_fu_1078_p2[32'd67];

assign tmp_123_fu_2542_p3 = xor_ln1350_27_fu_1072_p2[32'd68];

assign tmp_124_fu_2554_p3 = xor_ln1350_26_fu_1066_p2[32'd69];

assign tmp_125_fu_2566_p3 = xor_ln1350_25_fu_1060_p2[32'd70];

assign tmp_126_fu_2578_p3 = xor_ln1350_24_fu_1054_p2[32'd71];

assign tmp_127_fu_2590_p3 = xor_ln1350_23_fu_1048_p2[32'd72];

assign tmp_128_fu_2602_p3 = xor_ln1350_22_fu_1042_p2[32'd73];

assign tmp_129_fu_2614_p3 = xor_ln1350_21_fu_1036_p2[32'd74];

assign tmp_130_fu_2626_p3 = xor_ln1350_20_fu_1030_p2[32'd75];

assign tmp_131_fu_2638_p3 = xor_ln1350_19_fu_1024_p2[32'd76];

assign tmp_132_fu_2650_p3 = xor_ln1350_18_fu_1018_p2[32'd77];

assign tmp_133_fu_2662_p3 = xor_ln1350_17_fu_1012_p2[32'd78];

assign tmp_134_fu_2674_p3 = xor_ln1350_16_fu_1006_p2[32'd79];

assign tmp_135_fu_2686_p3 = xor_ln1350_15_fu_1000_p2[32'd80];

assign tmp_136_fu_2698_p3 = xor_ln1350_14_fu_994_p2[32'd81];

assign tmp_137_fu_2710_p3 = xor_ln1350_13_fu_988_p2[32'd82];

assign tmp_138_fu_2722_p3 = xor_ln1350_12_fu_982_p2[32'd83];

assign tmp_139_fu_2734_p3 = xor_ln1350_11_fu_976_p2[32'd84];

assign tmp_140_fu_2746_p3 = xor_ln1350_10_fu_970_p2[32'd85];

assign tmp_141_fu_2758_p3 = xor_ln1350_9_fu_964_p2[32'd86];

assign tmp_142_fu_2770_p3 = xor_ln1350_8_fu_958_p2[32'd87];

assign tmp_143_fu_2782_p3 = xor_ln1350_7_fu_952_p2[32'd88];

assign tmp_144_fu_2794_p3 = xor_ln1350_6_fu_946_p2[32'd89];

assign tmp_145_fu_2806_p3 = xor_ln1350_5_fu_940_p2[32'd90];

assign tmp_146_fu_2818_p3 = xor_ln1350_4_fu_934_p2[32'd91];

assign tmp_147_fu_2830_p3 = xor_ln1350_3_fu_928_p2[32'd92];

assign tmp_148_fu_2842_p3 = xor_ln1350_2_fu_922_p2[32'd93];

assign tmp_149_fu_2854_p3 = xor_ln1350_1_fu_916_p2[32'd94];

assign tmp_150_fu_2866_p3 = ret_fu_910_p2[32'd95];

assign tmp_57_fu_1750_p3 = xor_ln1158_28_fu_1716_p2[32'd2];

assign tmp_58_fu_1762_p3 = xor_ln1158_27_fu_1710_p2[32'd3];

assign tmp_59_fu_1774_p3 = xor_ln1158_26_fu_1704_p2[32'd4];

assign tmp_60_fu_1786_p3 = xor_ln1158_25_fu_1698_p2[32'd5];

assign tmp_61_fu_1798_p3 = xor_ln1158_24_fu_1692_p2[32'd6];

assign tmp_62_fu_1810_p3 = xor_ln1158_23_fu_1686_p2[32'd7];

assign tmp_63_fu_1822_p3 = xor_ln1158_22_fu_1680_p2[32'd8];

assign tmp_64_fu_1834_p3 = xor_ln1158_21_fu_1674_p2[32'd9];

assign tmp_65_fu_1846_p3 = xor_ln1158_20_fu_1668_p2[32'd10];

assign tmp_66_fu_1858_p3 = xor_ln1158_19_fu_1662_p2[32'd11];

assign tmp_67_fu_1870_p3 = xor_ln1158_18_fu_1656_p2[32'd12];

assign tmp_68_fu_1882_p3 = xor_ln1158_17_fu_1650_p2[32'd13];

assign tmp_69_fu_1894_p3 = xor_ln1158_16_fu_1644_p2[32'd14];

assign tmp_70_fu_1906_p3 = xor_ln1158_15_fu_1638_p2[32'd15];

assign tmp_71_fu_1918_p3 = xor_ln1158_14_fu_1632_p2[32'd16];

assign tmp_72_fu_1930_p3 = xor_ln1158_13_fu_1626_p2[32'd17];

assign tmp_73_fu_1942_p3 = xor_ln1158_12_fu_1620_p2[32'd18];

assign tmp_74_fu_1954_p3 = xor_ln1158_11_fu_1614_p2[32'd19];

assign tmp_75_fu_1966_p3 = xor_ln1158_10_fu_1608_p2[32'd20];

assign tmp_76_fu_1978_p3 = xor_ln1158_9_fu_1602_p2[32'd21];

assign tmp_77_fu_1990_p3 = xor_ln1158_8_fu_1596_p2[32'd22];

assign tmp_78_fu_2002_p3 = xor_ln1158_7_fu_1590_p2[32'd23];

assign tmp_79_fu_2014_p3 = xor_ln1158_6_fu_1584_p2[32'd24];

assign tmp_80_fu_2026_p3 = xor_ln1158_5_fu_1578_p2[32'd25];

assign tmp_81_fu_2038_p3 = xor_ln1158_4_fu_1572_p2[32'd26];

assign tmp_82_fu_2050_p3 = xor_ln1158_3_fu_1566_p2[32'd27];

assign tmp_83_fu_2062_p3 = xor_ln1158_2_fu_1560_p2[32'd28];

assign tmp_84_fu_2074_p3 = xor_ln1158_1_fu_1554_p2[32'd29];

assign tmp_85_fu_2086_p3 = xor_ln1158_fu_1548_p2[32'd30];

assign tmp_86_fu_2098_p3 = xor_ln819_fu_1542_p2[32'd31];

assign tmp_87_fu_2110_p3 = xor_ln1350_63_fu_1288_p2[32'd32];

assign tmp_88_fu_2122_p3 = xor_ln1350_62_fu_1282_p2[32'd33];

assign tmp_89_fu_2134_p3 = xor_ln1350_61_fu_1276_p2[32'd34];

assign tmp_90_fu_2146_p3 = xor_ln1350_60_fu_1270_p2[32'd35];

assign tmp_91_fu_2158_p3 = xor_ln1350_59_fu_1264_p2[32'd36];

assign tmp_92_fu_2170_p3 = xor_ln1350_58_fu_1258_p2[32'd37];

assign tmp_93_fu_2182_p3 = xor_ln1350_57_fu_1252_p2[32'd38];

assign tmp_94_fu_2194_p3 = xor_ln1350_56_fu_1246_p2[32'd39];

assign tmp_95_fu_2206_p3 = xor_ln1350_55_fu_1240_p2[32'd40];

assign tmp_96_fu_2218_p3 = xor_ln1350_54_fu_1234_p2[32'd41];

assign tmp_97_fu_2230_p3 = xor_ln1350_53_fu_1228_p2[32'd42];

assign tmp_98_fu_2242_p3 = xor_ln1350_52_fu_1222_p2[32'd43];

assign tmp_99_fu_2254_p3 = xor_ln1350_51_fu_1216_p2[32'd44];

assign tmp_fu_1738_p3 = xor_ln1158_29_fu_1722_p2[32'd1];

assign trunc_ln1350_100_fu_798_p1 = flame96[81:0];

assign trunc_ln1350_101_fu_802_p1 = temp_flame96_V_read[81:0];

assign trunc_ln1350_102_fu_806_p1 = flame96[82:0];

assign trunc_ln1350_103_fu_810_p1 = temp_flame96_V_read[82:0];

assign trunc_ln1350_104_fu_814_p1 = flame96[83:0];

assign trunc_ln1350_105_fu_818_p1 = temp_flame96_V_read[83:0];

assign trunc_ln1350_106_fu_822_p1 = flame96[84:0];

assign trunc_ln1350_107_fu_826_p1 = temp_flame96_V_read[84:0];

assign trunc_ln1350_108_fu_830_p1 = flame96[85:0];

assign trunc_ln1350_109_fu_834_p1 = temp_flame96_V_read[85:0];

assign trunc_ln1350_10_fu_438_p1 = flame96[36:0];

assign trunc_ln1350_110_fu_838_p1 = flame96[86:0];

assign trunc_ln1350_111_fu_842_p1 = temp_flame96_V_read[86:0];

assign trunc_ln1350_112_fu_846_p1 = flame96[87:0];

assign trunc_ln1350_113_fu_850_p1 = temp_flame96_V_read[87:0];

assign trunc_ln1350_114_fu_854_p1 = flame96[88:0];

assign trunc_ln1350_115_fu_858_p1 = temp_flame96_V_read[88:0];

assign trunc_ln1350_116_fu_862_p1 = flame96[89:0];

assign trunc_ln1350_117_fu_866_p1 = temp_flame96_V_read[89:0];

assign trunc_ln1350_118_fu_870_p1 = flame96[90:0];

assign trunc_ln1350_119_fu_874_p1 = temp_flame96_V_read[90:0];

assign trunc_ln1350_11_fu_442_p1 = temp_flame96_V_read[36:0];

assign trunc_ln1350_120_fu_878_p1 = flame96[91:0];

assign trunc_ln1350_121_fu_882_p1 = temp_flame96_V_read[91:0];

assign trunc_ln1350_122_fu_886_p1 = flame96[92:0];

assign trunc_ln1350_123_fu_890_p1 = temp_flame96_V_read[92:0];

assign trunc_ln1350_124_fu_894_p1 = flame96[93:0];

assign trunc_ln1350_125_fu_898_p1 = temp_flame96_V_read[93:0];

assign trunc_ln1350_126_fu_902_p1 = flame96[94:0];

assign trunc_ln1350_127_fu_906_p1 = temp_flame96_V_read[94:0];

assign trunc_ln1350_12_fu_446_p1 = flame96[37:0];

assign trunc_ln1350_13_fu_450_p1 = temp_flame96_V_read[37:0];

assign trunc_ln1350_14_fu_454_p1 = flame96[38:0];

assign trunc_ln1350_15_fu_458_p1 = temp_flame96_V_read[38:0];

assign trunc_ln1350_16_fu_462_p1 = flame96[39:0];

assign trunc_ln1350_17_fu_466_p1 = temp_flame96_V_read[39:0];

assign trunc_ln1350_18_fu_470_p1 = flame96[40:0];

assign trunc_ln1350_19_fu_474_p1 = temp_flame96_V_read[40:0];

assign trunc_ln1350_1_fu_402_p1 = temp_flame96_V_read[31:0];

assign trunc_ln1350_20_fu_478_p1 = flame96[41:0];

assign trunc_ln1350_21_fu_482_p1 = temp_flame96_V_read[41:0];

assign trunc_ln1350_22_fu_486_p1 = flame96[42:0];

assign trunc_ln1350_23_fu_490_p1 = temp_flame96_V_read[42:0];

assign trunc_ln1350_24_fu_494_p1 = flame96[43:0];

assign trunc_ln1350_25_fu_498_p1 = temp_flame96_V_read[43:0];

assign trunc_ln1350_26_fu_502_p1 = flame96[44:0];

assign trunc_ln1350_27_fu_506_p1 = temp_flame96_V_read[44:0];

assign trunc_ln1350_28_fu_510_p1 = flame96[45:0];

assign trunc_ln1350_29_fu_514_p1 = temp_flame96_V_read[45:0];

assign trunc_ln1350_2_fu_406_p1 = flame96[32:0];

assign trunc_ln1350_30_fu_518_p1 = flame96[46:0];

assign trunc_ln1350_31_fu_522_p1 = temp_flame96_V_read[46:0];

assign trunc_ln1350_32_fu_526_p1 = flame96[47:0];

assign trunc_ln1350_33_fu_530_p1 = temp_flame96_V_read[47:0];

assign trunc_ln1350_34_fu_534_p1 = flame96[48:0];

assign trunc_ln1350_35_fu_538_p1 = temp_flame96_V_read[48:0];

assign trunc_ln1350_36_fu_542_p1 = flame96[49:0];

assign trunc_ln1350_37_fu_546_p1 = temp_flame96_V_read[49:0];

assign trunc_ln1350_38_fu_550_p1 = flame96[50:0];

assign trunc_ln1350_39_fu_554_p1 = temp_flame96_V_read[50:0];

assign trunc_ln1350_3_fu_410_p1 = temp_flame96_V_read[32:0];

assign trunc_ln1350_40_fu_558_p1 = flame96[51:0];

assign trunc_ln1350_41_fu_562_p1 = temp_flame96_V_read[51:0];

assign trunc_ln1350_42_fu_566_p1 = flame96[52:0];

assign trunc_ln1350_43_fu_570_p1 = temp_flame96_V_read[52:0];

assign trunc_ln1350_44_fu_574_p1 = flame96[53:0];

assign trunc_ln1350_45_fu_578_p1 = temp_flame96_V_read[53:0];

assign trunc_ln1350_46_fu_582_p1 = flame96[54:0];

assign trunc_ln1350_47_fu_586_p1 = temp_flame96_V_read[54:0];

assign trunc_ln1350_48_fu_590_p1 = flame96[55:0];

assign trunc_ln1350_49_fu_594_p1 = temp_flame96_V_read[55:0];

assign trunc_ln1350_4_fu_414_p1 = flame96[33:0];

assign trunc_ln1350_50_fu_598_p1 = flame96[56:0];

assign trunc_ln1350_51_fu_602_p1 = temp_flame96_V_read[56:0];

assign trunc_ln1350_52_fu_606_p1 = flame96[57:0];

assign trunc_ln1350_53_fu_610_p1 = temp_flame96_V_read[57:0];

assign trunc_ln1350_54_fu_614_p1 = flame96[58:0];

assign trunc_ln1350_55_fu_618_p1 = temp_flame96_V_read[58:0];

assign trunc_ln1350_56_fu_622_p1 = flame96[59:0];

assign trunc_ln1350_57_fu_626_p1 = temp_flame96_V_read[59:0];

assign trunc_ln1350_58_fu_630_p1 = flame96[60:0];

assign trunc_ln1350_59_fu_634_p1 = temp_flame96_V_read[60:0];

assign trunc_ln1350_5_fu_418_p1 = temp_flame96_V_read[33:0];

assign trunc_ln1350_60_fu_638_p1 = flame96[61:0];

assign trunc_ln1350_61_fu_642_p1 = temp_flame96_V_read[61:0];

assign trunc_ln1350_62_fu_646_p1 = flame96[62:0];

assign trunc_ln1350_63_fu_650_p1 = temp_flame96_V_read[62:0];

assign trunc_ln1350_64_fu_654_p1 = flame96[63:0];

assign trunc_ln1350_65_fu_658_p1 = temp_flame96_V_read[63:0];

assign trunc_ln1350_66_fu_662_p1 = flame96[64:0];

assign trunc_ln1350_67_fu_666_p1 = temp_flame96_V_read[64:0];

assign trunc_ln1350_68_fu_670_p1 = flame96[65:0];

assign trunc_ln1350_69_fu_674_p1 = temp_flame96_V_read[65:0];

assign trunc_ln1350_6_fu_422_p1 = flame96[34:0];

assign trunc_ln1350_70_fu_678_p1 = flame96[66:0];

assign trunc_ln1350_71_fu_682_p1 = temp_flame96_V_read[66:0];

assign trunc_ln1350_72_fu_686_p1 = flame96[67:0];

assign trunc_ln1350_73_fu_690_p1 = temp_flame96_V_read[67:0];

assign trunc_ln1350_74_fu_694_p1 = flame96[68:0];

assign trunc_ln1350_75_fu_698_p1 = temp_flame96_V_read[68:0];

assign trunc_ln1350_76_fu_702_p1 = flame96[69:0];

assign trunc_ln1350_77_fu_706_p1 = temp_flame96_V_read[69:0];

assign trunc_ln1350_78_fu_710_p1 = flame96[70:0];

assign trunc_ln1350_79_fu_714_p1 = temp_flame96_V_read[70:0];

assign trunc_ln1350_7_fu_426_p1 = temp_flame96_V_read[34:0];

assign trunc_ln1350_80_fu_718_p1 = flame96[71:0];

assign trunc_ln1350_81_fu_722_p1 = temp_flame96_V_read[71:0];

assign trunc_ln1350_82_fu_726_p1 = flame96[72:0];

assign trunc_ln1350_83_fu_730_p1 = temp_flame96_V_read[72:0];

assign trunc_ln1350_84_fu_734_p1 = flame96[73:0];

assign trunc_ln1350_85_fu_738_p1 = temp_flame96_V_read[73:0];

assign trunc_ln1350_86_fu_742_p1 = flame96[74:0];

assign trunc_ln1350_87_fu_746_p1 = temp_flame96_V_read[74:0];

assign trunc_ln1350_88_fu_750_p1 = flame96[75:0];

assign trunc_ln1350_89_fu_754_p1 = temp_flame96_V_read[75:0];

assign trunc_ln1350_8_fu_430_p1 = flame96[35:0];

assign trunc_ln1350_90_fu_758_p1 = flame96[76:0];

assign trunc_ln1350_91_fu_762_p1 = temp_flame96_V_read[76:0];

assign trunc_ln1350_92_fu_766_p1 = flame96[77:0];

assign trunc_ln1350_93_fu_770_p1 = temp_flame96_V_read[77:0];

assign trunc_ln1350_94_fu_774_p1 = flame96[78:0];

assign trunc_ln1350_95_fu_778_p1 = temp_flame96_V_read[78:0];

assign trunc_ln1350_96_fu_782_p1 = flame96[79:0];

assign trunc_ln1350_97_fu_786_p1 = temp_flame96_V_read[79:0];

assign trunc_ln1350_98_fu_790_p1 = flame96[80:0];

assign trunc_ln1350_99_fu_794_p1 = temp_flame96_V_read[80:0];

assign trunc_ln1350_9_fu_434_p1 = temp_flame96_V_read[35:0];

assign trunc_ln1350_fu_398_p1 = flame96[31:0];

assign trunc_ln819_10_fu_1334_p1 = flame96[5:0];

assign trunc_ln819_11_fu_1338_p1 = temp_flame96_V_read[5:0];

assign trunc_ln819_12_fu_1342_p1 = flame96[6:0];

assign trunc_ln819_13_fu_1346_p1 = temp_flame96_V_read[6:0];

assign trunc_ln819_14_fu_1350_p1 = flame96[7:0];

assign trunc_ln819_15_fu_1354_p1 = temp_flame96_V_read[7:0];

assign trunc_ln819_16_fu_1358_p1 = flame96[8:0];

assign trunc_ln819_17_fu_1362_p1 = temp_flame96_V_read[8:0];

assign trunc_ln819_18_fu_1366_p1 = flame96[9:0];

assign trunc_ln819_19_fu_1370_p1 = temp_flame96_V_read[9:0];

assign trunc_ln819_1_fu_1298_p1 = temp_flame96_V_read[0:0];

assign trunc_ln819_20_fu_1374_p1 = flame96[10:0];

assign trunc_ln819_21_fu_1378_p1 = temp_flame96_V_read[10:0];

assign trunc_ln819_22_fu_1382_p1 = flame96[11:0];

assign trunc_ln819_23_fu_1386_p1 = temp_flame96_V_read[11:0];

assign trunc_ln819_24_fu_1390_p1 = flame96[12:0];

assign trunc_ln819_25_fu_1394_p1 = temp_flame96_V_read[12:0];

assign trunc_ln819_26_fu_1398_p1 = flame96[13:0];

assign trunc_ln819_27_fu_1402_p1 = temp_flame96_V_read[13:0];

assign trunc_ln819_28_fu_1406_p1 = flame96[14:0];

assign trunc_ln819_29_fu_1410_p1 = temp_flame96_V_read[14:0];

assign trunc_ln819_2_fu_1302_p1 = flame96[1:0];

assign trunc_ln819_30_fu_1414_p1 = flame96[15:0];

assign trunc_ln819_31_fu_1418_p1 = temp_flame96_V_read[15:0];

assign trunc_ln819_32_fu_1422_p1 = flame96[16:0];

assign trunc_ln819_33_fu_1426_p1 = temp_flame96_V_read[16:0];

assign trunc_ln819_34_fu_1430_p1 = flame96[17:0];

assign trunc_ln819_35_fu_1434_p1 = temp_flame96_V_read[17:0];

assign trunc_ln819_36_fu_1438_p1 = flame96[18:0];

assign trunc_ln819_37_fu_1442_p1 = temp_flame96_V_read[18:0];

assign trunc_ln819_38_fu_1446_p1 = flame96[19:0];

assign trunc_ln819_39_fu_1450_p1 = temp_flame96_V_read[19:0];

assign trunc_ln819_3_fu_1306_p1 = temp_flame96_V_read[1:0];

assign trunc_ln819_40_fu_1454_p1 = flame96[20:0];

assign trunc_ln819_41_fu_1458_p1 = temp_flame96_V_read[20:0];

assign trunc_ln819_42_fu_1462_p1 = flame96[21:0];

assign trunc_ln819_43_fu_1466_p1 = temp_flame96_V_read[21:0];

assign trunc_ln819_44_fu_1470_p1 = flame96[22:0];

assign trunc_ln819_45_fu_1474_p1 = temp_flame96_V_read[22:0];

assign trunc_ln819_46_fu_1478_p1 = flame96[23:0];

assign trunc_ln819_47_fu_1482_p1 = temp_flame96_V_read[23:0];

assign trunc_ln819_48_fu_1486_p1 = flame96[24:0];

assign trunc_ln819_49_fu_1490_p1 = temp_flame96_V_read[24:0];

assign trunc_ln819_4_fu_1310_p1 = flame96[2:0];

assign trunc_ln819_50_fu_1494_p1 = flame96[25:0];

assign trunc_ln819_51_fu_1498_p1 = temp_flame96_V_read[25:0];

assign trunc_ln819_52_fu_1502_p1 = flame96[26:0];

assign trunc_ln819_53_fu_1506_p1 = temp_flame96_V_read[26:0];

assign trunc_ln819_54_fu_1510_p1 = flame96[27:0];

assign trunc_ln819_55_fu_1514_p1 = temp_flame96_V_read[27:0];

assign trunc_ln819_56_fu_1518_p1 = flame96[28:0];

assign trunc_ln819_57_fu_1522_p1 = temp_flame96_V_read[28:0];

assign trunc_ln819_58_fu_1526_p1 = flame96[29:0];

assign trunc_ln819_59_fu_1530_p1 = temp_flame96_V_read[29:0];

assign trunc_ln819_5_fu_1314_p1 = temp_flame96_V_read[2:0];

assign trunc_ln819_60_fu_1534_p1 = flame96[30:0];

assign trunc_ln819_61_fu_1538_p1 = temp_flame96_V_read[30:0];

assign trunc_ln819_6_fu_1318_p1 = flame96[3:0];

assign trunc_ln819_7_fu_1322_p1 = temp_flame96_V_read[3:0];

assign trunc_ln819_8_fu_1326_p1 = flame96[4:0];

assign trunc_ln819_9_fu_1330_p1 = temp_flame96_V_read[4:0];

assign trunc_ln819_fu_1294_p1 = flame96[0:0];

assign xor_ln1158_10_fu_1608_p2 = (trunc_ln819_41_fu_1458_p1 ^ trunc_ln819_40_fu_1454_p1);

assign xor_ln1158_11_fu_1614_p2 = (trunc_ln819_39_fu_1450_p1 ^ trunc_ln819_38_fu_1446_p1);

assign xor_ln1158_12_fu_1620_p2 = (trunc_ln819_37_fu_1442_p1 ^ trunc_ln819_36_fu_1438_p1);

assign xor_ln1158_13_fu_1626_p2 = (trunc_ln819_35_fu_1434_p1 ^ trunc_ln819_34_fu_1430_p1);

assign xor_ln1158_14_fu_1632_p2 = (trunc_ln819_33_fu_1426_p1 ^ trunc_ln819_32_fu_1422_p1);

assign xor_ln1158_15_fu_1638_p2 = (trunc_ln819_31_fu_1418_p1 ^ trunc_ln819_30_fu_1414_p1);

assign xor_ln1158_16_fu_1644_p2 = (trunc_ln819_29_fu_1410_p1 ^ trunc_ln819_28_fu_1406_p1);

assign xor_ln1158_17_fu_1650_p2 = (trunc_ln819_27_fu_1402_p1 ^ trunc_ln819_26_fu_1398_p1);

assign xor_ln1158_18_fu_1656_p2 = (trunc_ln819_25_fu_1394_p1 ^ trunc_ln819_24_fu_1390_p1);

assign xor_ln1158_19_fu_1662_p2 = (trunc_ln819_23_fu_1386_p1 ^ trunc_ln819_22_fu_1382_p1);

assign xor_ln1158_1_fu_1554_p2 = (trunc_ln819_59_fu_1530_p1 ^ trunc_ln819_58_fu_1526_p1);

assign xor_ln1158_20_fu_1668_p2 = (trunc_ln819_21_fu_1378_p1 ^ trunc_ln819_20_fu_1374_p1);

assign xor_ln1158_21_fu_1674_p2 = (trunc_ln819_19_fu_1370_p1 ^ trunc_ln819_18_fu_1366_p1);

assign xor_ln1158_22_fu_1680_p2 = (trunc_ln819_17_fu_1362_p1 ^ trunc_ln819_16_fu_1358_p1);

assign xor_ln1158_23_fu_1686_p2 = (trunc_ln819_15_fu_1354_p1 ^ trunc_ln819_14_fu_1350_p1);

assign xor_ln1158_24_fu_1692_p2 = (trunc_ln819_13_fu_1346_p1 ^ trunc_ln819_12_fu_1342_p1);

assign xor_ln1158_25_fu_1698_p2 = (trunc_ln819_11_fu_1338_p1 ^ trunc_ln819_10_fu_1334_p1);

assign xor_ln1158_26_fu_1704_p2 = (trunc_ln819_9_fu_1330_p1 ^ trunc_ln819_8_fu_1326_p1);

assign xor_ln1158_27_fu_1710_p2 = (trunc_ln819_7_fu_1322_p1 ^ trunc_ln819_6_fu_1318_p1);

assign xor_ln1158_28_fu_1716_p2 = (trunc_ln819_5_fu_1314_p1 ^ trunc_ln819_4_fu_1310_p1);

assign xor_ln1158_29_fu_1722_p2 = (trunc_ln819_3_fu_1306_p1 ^ trunc_ln819_2_fu_1302_p1);

assign xor_ln1158_2_fu_1560_p2 = (trunc_ln819_57_fu_1522_p1 ^ trunc_ln819_56_fu_1518_p1);

assign xor_ln1158_30_fu_1728_p2 = (trunc_ln819_fu_1294_p1 ^ trunc_ln819_1_fu_1298_p1);

assign xor_ln1158_3_fu_1566_p2 = (trunc_ln819_55_fu_1514_p1 ^ trunc_ln819_54_fu_1510_p1);

assign xor_ln1158_4_fu_1572_p2 = (trunc_ln819_53_fu_1506_p1 ^ trunc_ln819_52_fu_1502_p1);

assign xor_ln1158_5_fu_1578_p2 = (trunc_ln819_51_fu_1498_p1 ^ trunc_ln819_50_fu_1494_p1);

assign xor_ln1158_6_fu_1584_p2 = (trunc_ln819_49_fu_1490_p1 ^ trunc_ln819_48_fu_1486_p1);

assign xor_ln1158_7_fu_1590_p2 = (trunc_ln819_47_fu_1482_p1 ^ trunc_ln819_46_fu_1478_p1);

assign xor_ln1158_8_fu_1596_p2 = (trunc_ln819_45_fu_1474_p1 ^ trunc_ln819_44_fu_1470_p1);

assign xor_ln1158_9_fu_1602_p2 = (trunc_ln819_43_fu_1466_p1 ^ trunc_ln819_42_fu_1462_p1);

assign xor_ln1158_fu_1548_p2 = (trunc_ln819_61_fu_1538_p1 ^ trunc_ln819_60_fu_1534_p1);

assign xor_ln1350_10_fu_970_p2 = (trunc_ln1350_109_fu_834_p1 ^ trunc_ln1350_108_fu_830_p1);

assign xor_ln1350_11_fu_976_p2 = (trunc_ln1350_107_fu_826_p1 ^ trunc_ln1350_106_fu_822_p1);

assign xor_ln1350_12_fu_982_p2 = (trunc_ln1350_105_fu_818_p1 ^ trunc_ln1350_104_fu_814_p1);

assign xor_ln1350_13_fu_988_p2 = (trunc_ln1350_103_fu_810_p1 ^ trunc_ln1350_102_fu_806_p1);

assign xor_ln1350_14_fu_994_p2 = (trunc_ln1350_101_fu_802_p1 ^ trunc_ln1350_100_fu_798_p1);

assign xor_ln1350_15_fu_1000_p2 = (trunc_ln1350_99_fu_794_p1 ^ trunc_ln1350_98_fu_790_p1);

assign xor_ln1350_16_fu_1006_p2 = (trunc_ln1350_97_fu_786_p1 ^ trunc_ln1350_96_fu_782_p1);

assign xor_ln1350_17_fu_1012_p2 = (trunc_ln1350_95_fu_778_p1 ^ trunc_ln1350_94_fu_774_p1);

assign xor_ln1350_18_fu_1018_p2 = (trunc_ln1350_93_fu_770_p1 ^ trunc_ln1350_92_fu_766_p1);

assign xor_ln1350_19_fu_1024_p2 = (trunc_ln1350_91_fu_762_p1 ^ trunc_ln1350_90_fu_758_p1);

assign xor_ln1350_1_fu_916_p2 = (trunc_ln1350_127_fu_906_p1 ^ trunc_ln1350_126_fu_902_p1);

assign xor_ln1350_20_fu_1030_p2 = (trunc_ln1350_89_fu_754_p1 ^ trunc_ln1350_88_fu_750_p1);

assign xor_ln1350_21_fu_1036_p2 = (trunc_ln1350_87_fu_746_p1 ^ trunc_ln1350_86_fu_742_p1);

assign xor_ln1350_22_fu_1042_p2 = (trunc_ln1350_85_fu_738_p1 ^ trunc_ln1350_84_fu_734_p1);

assign xor_ln1350_23_fu_1048_p2 = (trunc_ln1350_83_fu_730_p1 ^ trunc_ln1350_82_fu_726_p1);

assign xor_ln1350_24_fu_1054_p2 = (trunc_ln1350_81_fu_722_p1 ^ trunc_ln1350_80_fu_718_p1);

assign xor_ln1350_25_fu_1060_p2 = (trunc_ln1350_79_fu_714_p1 ^ trunc_ln1350_78_fu_710_p1);

assign xor_ln1350_26_fu_1066_p2 = (trunc_ln1350_77_fu_706_p1 ^ trunc_ln1350_76_fu_702_p1);

assign xor_ln1350_27_fu_1072_p2 = (trunc_ln1350_75_fu_698_p1 ^ trunc_ln1350_74_fu_694_p1);

assign xor_ln1350_28_fu_1078_p2 = (trunc_ln1350_73_fu_690_p1 ^ trunc_ln1350_72_fu_686_p1);

assign xor_ln1350_29_fu_1084_p2 = (trunc_ln1350_71_fu_682_p1 ^ trunc_ln1350_70_fu_678_p1);

assign xor_ln1350_2_fu_922_p2 = (trunc_ln1350_125_fu_898_p1 ^ trunc_ln1350_124_fu_894_p1);

assign xor_ln1350_30_fu_1090_p2 = (trunc_ln1350_69_fu_674_p1 ^ trunc_ln1350_68_fu_670_p1);

assign xor_ln1350_31_fu_1096_p2 = (trunc_ln1350_67_fu_666_p1 ^ trunc_ln1350_66_fu_662_p1);

assign xor_ln1350_32_fu_1102_p2 = (trunc_ln1350_65_fu_658_p1 ^ trunc_ln1350_64_fu_654_p1);

assign xor_ln1350_33_fu_1108_p2 = (trunc_ln1350_63_fu_650_p1 ^ trunc_ln1350_62_fu_646_p1);

assign xor_ln1350_34_fu_1114_p2 = (trunc_ln1350_61_fu_642_p1 ^ trunc_ln1350_60_fu_638_p1);

assign xor_ln1350_35_fu_1120_p2 = (trunc_ln1350_59_fu_634_p1 ^ trunc_ln1350_58_fu_630_p1);

assign xor_ln1350_36_fu_1126_p2 = (trunc_ln1350_57_fu_626_p1 ^ trunc_ln1350_56_fu_622_p1);

assign xor_ln1350_37_fu_1132_p2 = (trunc_ln1350_55_fu_618_p1 ^ trunc_ln1350_54_fu_614_p1);

assign xor_ln1350_38_fu_1138_p2 = (trunc_ln1350_53_fu_610_p1 ^ trunc_ln1350_52_fu_606_p1);

assign xor_ln1350_39_fu_1144_p2 = (trunc_ln1350_51_fu_602_p1 ^ trunc_ln1350_50_fu_598_p1);

assign xor_ln1350_3_fu_928_p2 = (trunc_ln1350_123_fu_890_p1 ^ trunc_ln1350_122_fu_886_p1);

assign xor_ln1350_40_fu_1150_p2 = (trunc_ln1350_49_fu_594_p1 ^ trunc_ln1350_48_fu_590_p1);

assign xor_ln1350_41_fu_1156_p2 = (trunc_ln1350_47_fu_586_p1 ^ trunc_ln1350_46_fu_582_p1);

assign xor_ln1350_42_fu_1162_p2 = (trunc_ln1350_45_fu_578_p1 ^ trunc_ln1350_44_fu_574_p1);

assign xor_ln1350_43_fu_1168_p2 = (trunc_ln1350_43_fu_570_p1 ^ trunc_ln1350_42_fu_566_p1);

assign xor_ln1350_44_fu_1174_p2 = (trunc_ln1350_41_fu_562_p1 ^ trunc_ln1350_40_fu_558_p1);

assign xor_ln1350_45_fu_1180_p2 = (trunc_ln1350_39_fu_554_p1 ^ trunc_ln1350_38_fu_550_p1);

assign xor_ln1350_46_fu_1186_p2 = (trunc_ln1350_37_fu_546_p1 ^ trunc_ln1350_36_fu_542_p1);

assign xor_ln1350_47_fu_1192_p2 = (trunc_ln1350_35_fu_538_p1 ^ trunc_ln1350_34_fu_534_p1);

assign xor_ln1350_48_fu_1198_p2 = (trunc_ln1350_33_fu_530_p1 ^ trunc_ln1350_32_fu_526_p1);

assign xor_ln1350_49_fu_1204_p2 = (trunc_ln1350_31_fu_522_p1 ^ trunc_ln1350_30_fu_518_p1);

assign xor_ln1350_4_fu_934_p2 = (trunc_ln1350_121_fu_882_p1 ^ trunc_ln1350_120_fu_878_p1);

assign xor_ln1350_50_fu_1210_p2 = (trunc_ln1350_29_fu_514_p1 ^ trunc_ln1350_28_fu_510_p1);

assign xor_ln1350_51_fu_1216_p2 = (trunc_ln1350_27_fu_506_p1 ^ trunc_ln1350_26_fu_502_p1);

assign xor_ln1350_52_fu_1222_p2 = (trunc_ln1350_25_fu_498_p1 ^ trunc_ln1350_24_fu_494_p1);

assign xor_ln1350_53_fu_1228_p2 = (trunc_ln1350_23_fu_490_p1 ^ trunc_ln1350_22_fu_486_p1);

assign xor_ln1350_54_fu_1234_p2 = (trunc_ln1350_21_fu_482_p1 ^ trunc_ln1350_20_fu_478_p1);

assign xor_ln1350_55_fu_1240_p2 = (trunc_ln1350_19_fu_474_p1 ^ trunc_ln1350_18_fu_470_p1);

assign xor_ln1350_56_fu_1246_p2 = (trunc_ln1350_17_fu_466_p1 ^ trunc_ln1350_16_fu_462_p1);

assign xor_ln1350_57_fu_1252_p2 = (trunc_ln1350_15_fu_458_p1 ^ trunc_ln1350_14_fu_454_p1);

assign xor_ln1350_58_fu_1258_p2 = (trunc_ln1350_13_fu_450_p1 ^ trunc_ln1350_12_fu_446_p1);

assign xor_ln1350_59_fu_1264_p2 = (trunc_ln1350_11_fu_442_p1 ^ trunc_ln1350_10_fu_438_p1);

assign xor_ln1350_5_fu_940_p2 = (trunc_ln1350_119_fu_874_p1 ^ trunc_ln1350_118_fu_870_p1);

assign xor_ln1350_60_fu_1270_p2 = (trunc_ln1350_9_fu_434_p1 ^ trunc_ln1350_8_fu_430_p1);

assign xor_ln1350_61_fu_1276_p2 = (trunc_ln1350_7_fu_426_p1 ^ trunc_ln1350_6_fu_422_p1);

assign xor_ln1350_62_fu_1282_p2 = (trunc_ln1350_5_fu_418_p1 ^ trunc_ln1350_4_fu_414_p1);

assign xor_ln1350_63_fu_1288_p2 = (trunc_ln1350_3_fu_410_p1 ^ trunc_ln1350_2_fu_406_p1);

assign xor_ln1350_6_fu_946_p2 = (trunc_ln1350_117_fu_866_p1 ^ trunc_ln1350_116_fu_862_p1);

assign xor_ln1350_7_fu_952_p2 = (trunc_ln1350_115_fu_858_p1 ^ trunc_ln1350_114_fu_854_p1);

assign xor_ln1350_8_fu_958_p2 = (trunc_ln1350_113_fu_850_p1 ^ trunc_ln1350_112_fu_846_p1);

assign xor_ln1350_9_fu_964_p2 = (trunc_ln1350_111_fu_842_p1 ^ trunc_ln1350_110_fu_838_p1);

assign xor_ln819_fu_1542_p2 = (trunc_ln1350_fu_398_p1 ^ trunc_ln1350_1_fu_402_p1);

assign zext_ln1158_10_fu_1854_p1 = tmp_65_fu_1846_p3;

assign zext_ln1158_11_fu_1866_p1 = tmp_66_fu_1858_p3;

assign zext_ln1158_12_fu_1878_p1 = tmp_67_fu_1870_p3;

assign zext_ln1158_13_fu_1890_p1 = tmp_68_fu_1882_p3;

assign zext_ln1158_14_fu_1902_p1 = tmp_69_fu_1894_p3;

assign zext_ln1158_15_fu_1914_p1 = tmp_70_fu_1906_p3;

assign zext_ln1158_16_fu_1926_p1 = tmp_71_fu_1918_p3;

assign zext_ln1158_17_fu_1938_p1 = tmp_72_fu_1930_p3;

assign zext_ln1158_18_fu_1950_p1 = tmp_73_fu_1942_p3;

assign zext_ln1158_19_fu_1962_p1 = tmp_74_fu_1954_p3;

assign zext_ln1158_1_fu_1746_p1 = tmp_fu_1738_p3;

assign zext_ln1158_20_fu_1974_p1 = tmp_75_fu_1966_p3;

assign zext_ln1158_21_fu_1986_p1 = tmp_76_fu_1978_p3;

assign zext_ln1158_22_fu_1998_p1 = tmp_77_fu_1990_p3;

assign zext_ln1158_23_fu_2010_p1 = tmp_78_fu_2002_p3;

assign zext_ln1158_24_fu_2022_p1 = tmp_79_fu_2014_p3;

assign zext_ln1158_25_fu_2034_p1 = tmp_80_fu_2026_p3;

assign zext_ln1158_26_fu_2046_p1 = tmp_81_fu_2038_p3;

assign zext_ln1158_27_fu_2058_p1 = tmp_82_fu_2050_p3;

assign zext_ln1158_28_fu_2070_p1 = tmp_83_fu_2062_p3;

assign zext_ln1158_29_fu_2082_p1 = tmp_84_fu_2074_p3;

assign zext_ln1158_2_fu_1758_p1 = tmp_57_fu_1750_p3;

assign zext_ln1158_30_fu_2094_p1 = tmp_85_fu_2086_p3;

assign zext_ln1158_31_fu_2106_p1 = tmp_86_fu_2098_p3;

assign zext_ln1158_32_fu_2118_p1 = tmp_87_fu_2110_p3;

assign zext_ln1158_33_fu_2130_p1 = tmp_88_fu_2122_p3;

assign zext_ln1158_34_fu_2142_p1 = tmp_89_fu_2134_p3;

assign zext_ln1158_35_fu_2154_p1 = tmp_90_fu_2146_p3;

assign zext_ln1158_36_fu_2166_p1 = tmp_91_fu_2158_p3;

assign zext_ln1158_37_fu_2178_p1 = tmp_92_fu_2170_p3;

assign zext_ln1158_38_fu_2190_p1 = tmp_93_fu_2182_p3;

assign zext_ln1158_39_fu_2202_p1 = tmp_94_fu_2194_p3;

assign zext_ln1158_3_fu_1770_p1 = tmp_58_fu_1762_p3;

assign zext_ln1158_40_fu_2214_p1 = tmp_95_fu_2206_p3;

assign zext_ln1158_41_fu_2226_p1 = tmp_96_fu_2218_p3;

assign zext_ln1158_42_fu_2238_p1 = tmp_97_fu_2230_p3;

assign zext_ln1158_43_fu_2250_p1 = tmp_98_fu_2242_p3;

assign zext_ln1158_44_fu_2262_p1 = tmp_99_fu_2254_p3;

assign zext_ln1158_45_fu_2274_p1 = tmp_100_fu_2266_p3;

assign zext_ln1158_46_fu_2286_p1 = tmp_101_fu_2278_p3;

assign zext_ln1158_47_fu_2298_p1 = tmp_102_fu_2290_p3;

assign zext_ln1158_48_fu_2310_p1 = tmp_103_fu_2302_p3;

assign zext_ln1158_49_fu_2322_p1 = tmp_104_fu_2314_p3;

assign zext_ln1158_4_fu_1782_p1 = tmp_59_fu_1774_p3;

assign zext_ln1158_50_fu_2334_p1 = tmp_105_fu_2326_p3;

assign zext_ln1158_51_fu_2346_p1 = tmp_106_fu_2338_p3;

assign zext_ln1158_52_fu_2358_p1 = tmp_107_fu_2350_p3;

assign zext_ln1158_53_fu_2370_p1 = tmp_108_fu_2362_p3;

assign zext_ln1158_54_fu_2382_p1 = tmp_109_fu_2374_p3;

assign zext_ln1158_55_fu_2394_p1 = tmp_110_fu_2386_p3;

assign zext_ln1158_56_fu_2406_p1 = tmp_111_fu_2398_p3;

assign zext_ln1158_57_fu_2418_p1 = tmp_112_fu_2410_p3;

assign zext_ln1158_58_fu_2430_p1 = tmp_113_fu_2422_p3;

assign zext_ln1158_59_fu_2442_p1 = tmp_114_fu_2434_p3;

assign zext_ln1158_5_fu_1794_p1 = tmp_60_fu_1786_p3;

assign zext_ln1158_60_fu_2454_p1 = tmp_115_fu_2446_p3;

assign zext_ln1158_61_fu_2466_p1 = tmp_116_fu_2458_p3;

assign zext_ln1158_62_fu_2478_p1 = tmp_117_fu_2470_p3;

assign zext_ln1158_63_fu_2490_p1 = tmp_118_fu_2482_p3;

assign zext_ln1158_64_fu_2502_p1 = tmp_119_fu_2494_p3;

assign zext_ln1158_65_fu_2514_p1 = tmp_120_fu_2506_p3;

assign zext_ln1158_66_fu_2526_p1 = tmp_121_fu_2518_p3;

assign zext_ln1158_67_fu_2538_p1 = tmp_122_fu_2530_p3;

assign zext_ln1158_68_fu_2550_p1 = tmp_123_fu_2542_p3;

assign zext_ln1158_69_fu_2562_p1 = tmp_124_fu_2554_p3;

assign zext_ln1158_6_fu_1806_p1 = tmp_61_fu_1798_p3;

assign zext_ln1158_70_fu_2574_p1 = tmp_125_fu_2566_p3;

assign zext_ln1158_71_fu_2586_p1 = tmp_126_fu_2578_p3;

assign zext_ln1158_72_fu_2598_p1 = tmp_127_fu_2590_p3;

assign zext_ln1158_73_fu_2610_p1 = tmp_128_fu_2602_p3;

assign zext_ln1158_74_fu_2622_p1 = tmp_129_fu_2614_p3;

assign zext_ln1158_75_fu_2634_p1 = tmp_130_fu_2626_p3;

assign zext_ln1158_76_fu_2646_p1 = tmp_131_fu_2638_p3;

assign zext_ln1158_77_fu_2658_p1 = tmp_132_fu_2650_p3;

assign zext_ln1158_78_fu_2670_p1 = tmp_133_fu_2662_p3;

assign zext_ln1158_79_fu_2682_p1 = tmp_134_fu_2674_p3;

assign zext_ln1158_7_fu_1818_p1 = tmp_62_fu_1810_p3;

assign zext_ln1158_80_fu_2694_p1 = tmp_135_fu_2686_p3;

assign zext_ln1158_81_fu_2706_p1 = tmp_136_fu_2698_p3;

assign zext_ln1158_82_fu_2718_p1 = tmp_137_fu_2710_p3;

assign zext_ln1158_83_fu_2730_p1 = tmp_138_fu_2722_p3;

assign zext_ln1158_84_fu_2742_p1 = tmp_139_fu_2734_p3;

assign zext_ln1158_85_fu_2754_p1 = tmp_140_fu_2746_p3;

assign zext_ln1158_86_fu_2766_p1 = tmp_141_fu_2758_p3;

assign zext_ln1158_87_fu_2778_p1 = tmp_142_fu_2770_p3;

assign zext_ln1158_88_fu_2790_p1 = tmp_143_fu_2782_p3;

assign zext_ln1158_89_fu_2802_p1 = tmp_144_fu_2794_p3;

assign zext_ln1158_8_fu_1830_p1 = tmp_63_fu_1822_p3;

assign zext_ln1158_90_fu_2814_p1 = tmp_145_fu_2806_p3;

assign zext_ln1158_91_fu_2826_p1 = tmp_146_fu_2818_p3;

assign zext_ln1158_92_fu_2838_p1 = tmp_147_fu_2830_p3;

assign zext_ln1158_93_fu_2850_p1 = tmp_148_fu_2842_p3;

assign zext_ln1158_94_fu_2862_p1 = tmp_149_fu_2854_p3;

assign zext_ln1158_9_fu_1842_p1 = tmp_64_fu_1834_p3;

assign zext_ln1158_fu_1734_p1 = xor_ln1158_30_fu_1728_p2;

assign zext_ln1159_10_fu_3026_p1 = add_ln1159_17_fu_3020_p2;

assign zext_ln1159_11_fu_3042_p1 = add_ln1159_19_fu_3036_p2;

assign zext_ln1159_12_fu_3052_p1 = add_ln1159_20_fu_3046_p2;

assign zext_ln1159_13_fu_3062_p1 = add_ln1159_21_fu_3056_p2;

assign zext_ln1159_14_fu_3072_p1 = add_ln1159_22_fu_3066_p2;

assign zext_ln1159_15_fu_3088_p1 = add_ln1159_24_fu_3082_p2;

assign zext_ln1159_16_fu_3104_p1 = add_ln1159_26_fu_3098_p2;

assign zext_ln1159_17_fu_3114_p1 = add_ln1159_27_fu_3108_p2;

assign zext_ln1159_18_fu_3130_p1 = add_ln1159_29_fu_3124_p2;

assign zext_ln1159_19_fu_3146_p1 = add_ln1159_31_fu_3140_p2;

assign zext_ln1159_1_fu_2906_p1 = add_ln1159_3_fu_2900_p2;

assign zext_ln1159_20_fu_3156_p1 = add_ln1159_32_fu_3150_p2;

assign zext_ln1159_21_fu_3166_p1 = add_ln1159_33_fu_3160_p2;

assign zext_ln1159_22_fu_3182_p1 = add_ln1159_35_fu_3176_p2;

assign zext_ln1159_23_fu_3198_p1 = add_ln1159_37_fu_3192_p2;

assign zext_ln1159_24_fu_3208_p1 = add_ln1159_38_fu_3202_p2;

assign zext_ln1159_25_fu_3224_p1 = add_ln1159_40_fu_3218_p2;

assign zext_ln1159_26_fu_3240_p1 = add_ln1159_42_fu_3234_p2;

assign zext_ln1159_27_fu_3250_p1 = add_ln1159_43_fu_3244_p2;

assign zext_ln1159_28_fu_3260_p1 = add_ln1159_44_fu_3254_p2;

assign zext_ln1159_29_fu_3270_p1 = add_ln1159_45_fu_3264_p2;

assign zext_ln1159_2_fu_2916_p1 = add_ln1159_4_fu_2910_p2;

assign zext_ln1159_30_fu_3280_p1 = add_ln1159_46_fu_3274_p2;

assign zext_ln1159_31_fu_3296_p1 = add_ln1159_48_fu_3290_p2;

assign zext_ln1159_32_fu_3312_p1 = add_ln1159_50_fu_3306_p2;

assign zext_ln1159_33_fu_3322_p1 = add_ln1159_51_fu_3316_p2;

assign zext_ln1159_34_fu_3338_p1 = add_ln1159_53_fu_3332_p2;

assign zext_ln1159_35_fu_3354_p1 = add_ln1159_55_fu_3348_p2;

assign zext_ln1159_36_fu_3364_p1 = add_ln1159_56_fu_3358_p2;

assign zext_ln1159_37_fu_3374_p1 = add_ln1159_57_fu_3368_p2;

assign zext_ln1159_38_fu_3390_p1 = add_ln1159_59_fu_3384_p2;

assign zext_ln1159_39_fu_3406_p1 = add_ln1159_61_fu_3400_p2;

assign zext_ln1159_3_fu_2932_p1 = add_ln1159_6_fu_2926_p2;

assign zext_ln1159_40_fu_3416_p1 = add_ln1159_62_fu_3410_p2;

assign zext_ln1159_41_fu_3432_p1 = add_ln1159_64_fu_3426_p2;

assign zext_ln1159_42_fu_3448_p1 = add_ln1159_66_fu_3442_p2;

assign zext_ln1159_43_fu_3458_p1 = add_ln1159_67_fu_3452_p2;

assign zext_ln1159_44_fu_3468_p1 = add_ln1159_68_fu_3462_p2;

assign zext_ln1159_45_fu_3478_p1 = add_ln1159_69_fu_3472_p2;

assign zext_ln1159_46_fu_3494_p1 = add_ln1159_71_fu_3488_p2;

assign zext_ln1159_47_fu_3510_p1 = add_ln1159_73_fu_3504_p2;

assign zext_ln1159_48_fu_3520_p1 = add_ln1159_74_fu_3514_p2;

assign zext_ln1159_49_fu_3536_p1 = add_ln1159_76_fu_3530_p2;

assign zext_ln1159_4_fu_2948_p1 = add_ln1159_8_fu_2942_p2;

assign zext_ln1159_50_fu_3552_p1 = add_ln1159_78_fu_3546_p2;

assign zext_ln1159_51_fu_3562_p1 = add_ln1159_79_fu_3556_p2;

assign zext_ln1159_52_fu_3572_p1 = add_ln1159_80_fu_3566_p2;

assign zext_ln1159_53_fu_3588_p1 = add_ln1159_82_fu_3582_p2;

assign zext_ln1159_54_fu_3604_p1 = add_ln1159_84_fu_3598_p2;

assign zext_ln1159_55_fu_3614_p1 = add_ln1159_85_fu_3608_p2;

assign zext_ln1159_56_fu_3630_p1 = add_ln1159_87_fu_3624_p2;

assign zext_ln1159_57_fu_3646_p1 = add_ln1159_89_fu_3640_p2;

assign zext_ln1159_58_fu_3656_p1 = add_ln1159_90_fu_3650_p2;

assign zext_ln1159_59_fu_3666_p1 = add_ln1159_91_fu_3660_p2;

assign zext_ln1159_5_fu_2958_p1 = add_ln1159_9_fu_2952_p2;

assign zext_ln1159_60_fu_3676_p1 = add_ln1159_92_fu_3670_p2;

assign zext_ln1159_61_fu_3686_p1 = add_ln1159_93_fu_3680_p2;

assign zext_ln1159_62_fu_2874_p1 = tmp_150_fu_2866_p3;

assign zext_ln1159_6_fu_2968_p1 = add_ln1159_10_fu_2962_p2;

assign zext_ln1159_7_fu_2984_p1 = add_ln1159_12_fu_2978_p2;

assign zext_ln1159_8_fu_3000_p1 = add_ln1159_14_fu_2994_p2;

assign zext_ln1159_9_fu_3010_p1 = add_ln1159_15_fu_3004_p2;

assign zext_ln1159_fu_2890_p1 = add_ln1159_1_fu_2884_p2;

endmodule //table_serch_hd_cal96
