// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module table_serch_hd_cal962339 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        flame96,
        temp_flame96,
        hash_table,
        query,
        FP_DB,
        backet_location,
        hash_table_out_din,
        hash_table_out_full_n,
        hash_table_out_write,
        query_out_din,
        query_out_full_n,
        query_out_write,
        FP_DB_out_din,
        FP_DB_out_full_n,
        FP_DB_out_write,
        backet_location_out_din,
        backet_location_out_full_n,
        backet_location_out_write,
        ap_return
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [95:0] flame96;
input  [95:0] temp_flame96;
input  [63:0] hash_table;
input  [63:0] query;
input  [63:0] FP_DB;
input  [31:0] backet_location;
output  [63:0] hash_table_out_din;
input   hash_table_out_full_n;
output   hash_table_out_write;
output  [63:0] query_out_din;
input   query_out_full_n;
output   query_out_write;
output  [63:0] FP_DB_out_din;
input   FP_DB_out_full_n;
output   FP_DB_out_write;
output  [31:0] backet_location_out_din;
input   backet_location_out_full_n;
output   backet_location_out_write;
output  [6:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg hash_table_out_write;
reg query_out_write;
reg FP_DB_out_write;
reg backet_location_out_write;
reg[6:0] ap_return;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    hash_table_out_blk_n;
reg    query_out_blk_n;
reg    FP_DB_out_blk_n;
reg    backet_location_out_blk_n;
reg    ap_block_state1;
wire   [94:0] trunc_ln1350_254_fu_1002_p1;
wire   [94:0] trunc_ln1350_253_fu_998_p1;
wire   [93:0] trunc_ln1350_252_fu_994_p1;
wire   [93:0] trunc_ln1350_251_fu_990_p1;
wire   [92:0] trunc_ln1350_250_fu_986_p1;
wire   [92:0] trunc_ln1350_249_fu_982_p1;
wire   [91:0] trunc_ln1350_248_fu_978_p1;
wire   [91:0] trunc_ln1350_247_fu_974_p1;
wire   [90:0] trunc_ln1350_246_fu_970_p1;
wire   [90:0] trunc_ln1350_245_fu_966_p1;
wire   [89:0] trunc_ln1350_244_fu_962_p1;
wire   [89:0] trunc_ln1350_243_fu_958_p1;
wire   [88:0] trunc_ln1350_242_fu_954_p1;
wire   [88:0] trunc_ln1350_241_fu_950_p1;
wire   [87:0] trunc_ln1350_240_fu_946_p1;
wire   [87:0] trunc_ln1350_239_fu_942_p1;
wire   [86:0] trunc_ln1350_238_fu_938_p1;
wire   [86:0] trunc_ln1350_237_fu_934_p1;
wire   [85:0] trunc_ln1350_236_fu_930_p1;
wire   [85:0] trunc_ln1350_235_fu_926_p1;
wire   [84:0] trunc_ln1350_234_fu_922_p1;
wire   [84:0] trunc_ln1350_233_fu_918_p1;
wire   [83:0] trunc_ln1350_232_fu_914_p1;
wire   [83:0] trunc_ln1350_231_fu_910_p1;
wire   [82:0] trunc_ln1350_230_fu_906_p1;
wire   [82:0] trunc_ln1350_229_fu_902_p1;
wire   [81:0] trunc_ln1350_228_fu_898_p1;
wire   [81:0] trunc_ln1350_227_fu_894_p1;
wire   [80:0] trunc_ln1350_226_fu_890_p1;
wire   [80:0] trunc_ln1350_225_fu_886_p1;
wire   [79:0] trunc_ln1350_224_fu_882_p1;
wire   [79:0] trunc_ln1350_223_fu_878_p1;
wire   [78:0] trunc_ln1350_222_fu_874_p1;
wire   [78:0] trunc_ln1350_221_fu_870_p1;
wire   [77:0] trunc_ln1350_220_fu_866_p1;
wire   [77:0] trunc_ln1350_219_fu_862_p1;
wire   [76:0] trunc_ln1350_218_fu_858_p1;
wire   [76:0] trunc_ln1350_217_fu_854_p1;
wire   [75:0] trunc_ln1350_216_fu_850_p1;
wire   [75:0] trunc_ln1350_215_fu_846_p1;
wire   [74:0] trunc_ln1350_214_fu_842_p1;
wire   [74:0] trunc_ln1350_213_fu_838_p1;
wire   [73:0] trunc_ln1350_212_fu_834_p1;
wire   [73:0] trunc_ln1350_211_fu_830_p1;
wire   [72:0] trunc_ln1350_210_fu_826_p1;
wire   [72:0] trunc_ln1350_209_fu_822_p1;
wire   [71:0] trunc_ln1350_208_fu_818_p1;
wire   [71:0] trunc_ln1350_207_fu_814_p1;
wire   [70:0] trunc_ln1350_206_fu_810_p1;
wire   [70:0] trunc_ln1350_205_fu_806_p1;
wire   [69:0] trunc_ln1350_204_fu_802_p1;
wire   [69:0] trunc_ln1350_203_fu_798_p1;
wire   [68:0] trunc_ln1350_202_fu_794_p1;
wire   [68:0] trunc_ln1350_201_fu_790_p1;
wire   [67:0] trunc_ln1350_200_fu_786_p1;
wire   [67:0] trunc_ln1350_199_fu_782_p1;
wire   [66:0] trunc_ln1350_198_fu_778_p1;
wire   [66:0] trunc_ln1350_197_fu_774_p1;
wire   [65:0] trunc_ln1350_196_fu_770_p1;
wire   [65:0] trunc_ln1350_195_fu_766_p1;
wire   [64:0] trunc_ln1350_194_fu_762_p1;
wire   [64:0] trunc_ln1350_193_fu_758_p1;
wire   [63:0] trunc_ln1350_192_fu_754_p1;
wire   [63:0] trunc_ln1350_191_fu_750_p1;
wire   [62:0] trunc_ln1350_190_fu_746_p1;
wire   [62:0] trunc_ln1350_189_fu_742_p1;
wire   [61:0] trunc_ln1350_188_fu_738_p1;
wire   [61:0] trunc_ln1350_187_fu_734_p1;
wire   [60:0] trunc_ln1350_186_fu_730_p1;
wire   [60:0] trunc_ln1350_185_fu_726_p1;
wire   [59:0] trunc_ln1350_184_fu_722_p1;
wire   [59:0] trunc_ln1350_183_fu_718_p1;
wire   [58:0] trunc_ln1350_182_fu_714_p1;
wire   [58:0] trunc_ln1350_181_fu_710_p1;
wire   [57:0] trunc_ln1350_180_fu_706_p1;
wire   [57:0] trunc_ln1350_179_fu_702_p1;
wire   [56:0] trunc_ln1350_178_fu_698_p1;
wire   [56:0] trunc_ln1350_177_fu_694_p1;
wire   [55:0] trunc_ln1350_176_fu_690_p1;
wire   [55:0] trunc_ln1350_175_fu_686_p1;
wire   [54:0] trunc_ln1350_174_fu_682_p1;
wire   [54:0] trunc_ln1350_173_fu_678_p1;
wire   [53:0] trunc_ln1350_172_fu_674_p1;
wire   [53:0] trunc_ln1350_171_fu_670_p1;
wire   [52:0] trunc_ln1350_170_fu_666_p1;
wire   [52:0] trunc_ln1350_169_fu_662_p1;
wire   [51:0] trunc_ln1350_168_fu_658_p1;
wire   [51:0] trunc_ln1350_167_fu_654_p1;
wire   [50:0] trunc_ln1350_166_fu_650_p1;
wire   [50:0] trunc_ln1350_165_fu_646_p1;
wire   [49:0] trunc_ln1350_164_fu_642_p1;
wire   [49:0] trunc_ln1350_163_fu_638_p1;
wire   [48:0] trunc_ln1350_162_fu_634_p1;
wire   [48:0] trunc_ln1350_161_fu_630_p1;
wire   [47:0] trunc_ln1350_160_fu_626_p1;
wire   [47:0] trunc_ln1350_159_fu_622_p1;
wire   [46:0] trunc_ln1350_158_fu_618_p1;
wire   [46:0] trunc_ln1350_157_fu_614_p1;
wire   [45:0] trunc_ln1350_156_fu_610_p1;
wire   [45:0] trunc_ln1350_155_fu_606_p1;
wire   [44:0] trunc_ln1350_154_fu_602_p1;
wire   [44:0] trunc_ln1350_153_fu_598_p1;
wire   [43:0] trunc_ln1350_152_fu_594_p1;
wire   [43:0] trunc_ln1350_151_fu_590_p1;
wire   [42:0] trunc_ln1350_150_fu_586_p1;
wire   [42:0] trunc_ln1350_149_fu_582_p1;
wire   [41:0] trunc_ln1350_148_fu_578_p1;
wire   [41:0] trunc_ln1350_147_fu_574_p1;
wire   [40:0] trunc_ln1350_146_fu_570_p1;
wire   [40:0] trunc_ln1350_145_fu_566_p1;
wire   [39:0] trunc_ln1350_144_fu_562_p1;
wire   [39:0] trunc_ln1350_143_fu_558_p1;
wire   [38:0] trunc_ln1350_142_fu_554_p1;
wire   [38:0] trunc_ln1350_141_fu_550_p1;
wire   [37:0] trunc_ln1350_140_fu_546_p1;
wire   [37:0] trunc_ln1350_139_fu_542_p1;
wire   [36:0] trunc_ln1350_138_fu_538_p1;
wire   [36:0] trunc_ln1350_137_fu_534_p1;
wire   [35:0] trunc_ln1350_136_fu_530_p1;
wire   [35:0] trunc_ln1350_135_fu_526_p1;
wire   [34:0] trunc_ln1350_134_fu_522_p1;
wire   [34:0] trunc_ln1350_133_fu_518_p1;
wire   [33:0] trunc_ln1350_132_fu_514_p1;
wire   [33:0] trunc_ln1350_131_fu_510_p1;
wire   [32:0] trunc_ln1350_130_fu_506_p1;
wire   [32:0] trunc_ln1350_129_fu_502_p1;
wire   [31:0] trunc_ln1350_128_fu_498_p1;
wire   [31:0] trunc_ln1350_fu_494_p1;
wire   [30:0] trunc_ln819_122_fu_1634_p1;
wire   [30:0] trunc_ln819_121_fu_1630_p1;
wire   [29:0] trunc_ln819_120_fu_1626_p1;
wire   [29:0] trunc_ln819_119_fu_1622_p1;
wire   [28:0] trunc_ln819_118_fu_1618_p1;
wire   [28:0] trunc_ln819_117_fu_1614_p1;
wire   [27:0] trunc_ln819_116_fu_1610_p1;
wire   [27:0] trunc_ln819_115_fu_1606_p1;
wire   [26:0] trunc_ln819_114_fu_1602_p1;
wire   [26:0] trunc_ln819_113_fu_1598_p1;
wire   [25:0] trunc_ln819_112_fu_1594_p1;
wire   [25:0] trunc_ln819_111_fu_1590_p1;
wire   [24:0] trunc_ln819_110_fu_1586_p1;
wire   [24:0] trunc_ln819_109_fu_1582_p1;
wire   [23:0] trunc_ln819_108_fu_1578_p1;
wire   [23:0] trunc_ln819_107_fu_1574_p1;
wire   [22:0] trunc_ln819_106_fu_1570_p1;
wire   [22:0] trunc_ln819_105_fu_1566_p1;
wire   [21:0] trunc_ln819_104_fu_1562_p1;
wire   [21:0] trunc_ln819_103_fu_1558_p1;
wire   [20:0] trunc_ln819_102_fu_1554_p1;
wire   [20:0] trunc_ln819_101_fu_1550_p1;
wire   [19:0] trunc_ln819_100_fu_1546_p1;
wire   [19:0] trunc_ln819_99_fu_1542_p1;
wire   [18:0] trunc_ln819_98_fu_1538_p1;
wire   [18:0] trunc_ln819_97_fu_1534_p1;
wire   [17:0] trunc_ln819_96_fu_1530_p1;
wire   [17:0] trunc_ln819_95_fu_1526_p1;
wire   [16:0] trunc_ln819_94_fu_1522_p1;
wire   [16:0] trunc_ln819_93_fu_1518_p1;
wire   [15:0] trunc_ln819_92_fu_1514_p1;
wire   [15:0] trunc_ln819_91_fu_1510_p1;
wire   [14:0] trunc_ln819_90_fu_1506_p1;
wire   [14:0] trunc_ln819_89_fu_1502_p1;
wire   [13:0] trunc_ln819_88_fu_1498_p1;
wire   [13:0] trunc_ln819_87_fu_1494_p1;
wire   [12:0] trunc_ln819_86_fu_1490_p1;
wire   [12:0] trunc_ln819_85_fu_1486_p1;
wire   [11:0] trunc_ln819_84_fu_1482_p1;
wire   [11:0] trunc_ln819_83_fu_1478_p1;
wire   [10:0] trunc_ln819_82_fu_1474_p1;
wire   [10:0] trunc_ln819_81_fu_1470_p1;
wire   [9:0] trunc_ln819_80_fu_1466_p1;
wire   [9:0] trunc_ln819_79_fu_1462_p1;
wire   [8:0] trunc_ln819_78_fu_1458_p1;
wire   [8:0] trunc_ln819_77_fu_1454_p1;
wire   [7:0] trunc_ln819_76_fu_1450_p1;
wire   [7:0] trunc_ln819_75_fu_1446_p1;
wire   [6:0] trunc_ln819_74_fu_1442_p1;
wire   [6:0] trunc_ln819_73_fu_1438_p1;
wire   [5:0] trunc_ln819_72_fu_1434_p1;
wire   [5:0] trunc_ln819_71_fu_1430_p1;
wire   [4:0] trunc_ln819_70_fu_1426_p1;
wire   [4:0] trunc_ln819_69_fu_1422_p1;
wire   [3:0] trunc_ln819_68_fu_1418_p1;
wire   [3:0] trunc_ln819_67_fu_1414_p1;
wire   [2:0] trunc_ln819_66_fu_1410_p1;
wire   [2:0] trunc_ln819_65_fu_1406_p1;
wire   [1:0] trunc_ln819_64_fu_1402_p1;
wire   [1:0] trunc_ln819_63_fu_1398_p1;
wire   [0:0] trunc_ln819_62_fu_1394_p1;
wire   [0:0] trunc_ln819_fu_1390_p1;
wire   [0:0] xor_ln1158_60_fu_1824_p2;
wire   [1:0] xor_ln1158_59_fu_1818_p2;
wire   [0:0] tmp_fu_1834_p3;
wire   [2:0] xor_ln1158_58_fu_1812_p2;
wire   [0:0] tmp_246_fu_1846_p3;
wire   [3:0] xor_ln1158_57_fu_1806_p2;
wire   [0:0] tmp_247_fu_1858_p3;
wire   [4:0] xor_ln1158_56_fu_1800_p2;
wire   [0:0] tmp_248_fu_1870_p3;
wire   [5:0] xor_ln1158_55_fu_1794_p2;
wire   [0:0] tmp_249_fu_1882_p3;
wire   [6:0] xor_ln1158_54_fu_1788_p2;
wire   [0:0] tmp_250_fu_1894_p3;
wire   [7:0] xor_ln1158_53_fu_1782_p2;
wire   [0:0] tmp_251_fu_1906_p3;
wire   [8:0] xor_ln1158_52_fu_1776_p2;
wire   [0:0] tmp_252_fu_1918_p3;
wire   [9:0] xor_ln1158_51_fu_1770_p2;
wire   [0:0] tmp_253_fu_1930_p3;
wire   [10:0] xor_ln1158_50_fu_1764_p2;
wire   [0:0] tmp_254_fu_1942_p3;
wire   [11:0] xor_ln1158_49_fu_1758_p2;
wire   [0:0] tmp_255_fu_1954_p3;
wire   [12:0] xor_ln1158_48_fu_1752_p2;
wire   [0:0] tmp_256_fu_1966_p3;
wire   [13:0] xor_ln1158_47_fu_1746_p2;
wire   [0:0] tmp_257_fu_1978_p3;
wire   [14:0] xor_ln1158_46_fu_1740_p2;
wire   [0:0] tmp_258_fu_1990_p3;
wire   [15:0] xor_ln1158_45_fu_1734_p2;
wire   [0:0] tmp_259_fu_2002_p3;
wire   [16:0] xor_ln1158_44_fu_1728_p2;
wire   [0:0] tmp_260_fu_2014_p3;
wire   [17:0] xor_ln1158_43_fu_1722_p2;
wire   [0:0] tmp_261_fu_2026_p3;
wire   [18:0] xor_ln1158_42_fu_1716_p2;
wire   [0:0] tmp_262_fu_2038_p3;
wire   [19:0] xor_ln1158_41_fu_1710_p2;
wire   [0:0] tmp_263_fu_2050_p3;
wire   [20:0] xor_ln1158_40_fu_1704_p2;
wire   [0:0] tmp_264_fu_2062_p3;
wire   [21:0] xor_ln1158_39_fu_1698_p2;
wire   [0:0] tmp_265_fu_2074_p3;
wire   [22:0] xor_ln1158_38_fu_1692_p2;
wire   [0:0] tmp_266_fu_2086_p3;
wire   [23:0] xor_ln1158_37_fu_1686_p2;
wire   [0:0] tmp_267_fu_2098_p3;
wire   [24:0] xor_ln1158_36_fu_1680_p2;
wire   [0:0] tmp_268_fu_2110_p3;
wire   [25:0] xor_ln1158_35_fu_1674_p2;
wire   [0:0] tmp_269_fu_2122_p3;
wire   [26:0] xor_ln1158_34_fu_1668_p2;
wire   [0:0] tmp_270_fu_2134_p3;
wire   [27:0] xor_ln1158_33_fu_1662_p2;
wire   [0:0] tmp_271_fu_2146_p3;
wire   [28:0] xor_ln1158_32_fu_1656_p2;
wire   [0:0] tmp_272_fu_2158_p3;
wire   [29:0] xor_ln1158_31_fu_1650_p2;
wire   [0:0] tmp_273_fu_2170_p3;
wire   [30:0] xor_ln1158_fu_1644_p2;
wire   [0:0] tmp_274_fu_2182_p3;
wire   [31:0] xor_ln819_fu_1638_p2;
wire   [0:0] tmp_275_fu_2194_p3;
wire   [32:0] xor_ln1350_126_fu_1384_p2;
wire   [0:0] tmp_276_fu_2206_p3;
wire   [33:0] xor_ln1350_125_fu_1378_p2;
wire   [0:0] tmp_277_fu_2218_p3;
wire   [34:0] xor_ln1350_124_fu_1372_p2;
wire   [0:0] tmp_278_fu_2230_p3;
wire   [35:0] xor_ln1350_123_fu_1366_p2;
wire   [0:0] tmp_279_fu_2242_p3;
wire   [36:0] xor_ln1350_122_fu_1360_p2;
wire   [0:0] tmp_280_fu_2254_p3;
wire   [37:0] xor_ln1350_121_fu_1354_p2;
wire   [0:0] tmp_281_fu_2266_p3;
wire   [38:0] xor_ln1350_120_fu_1348_p2;
wire   [0:0] tmp_282_fu_2278_p3;
wire   [39:0] xor_ln1350_119_fu_1342_p2;
wire   [0:0] tmp_283_fu_2290_p3;
wire   [40:0] xor_ln1350_118_fu_1336_p2;
wire   [0:0] tmp_284_fu_2302_p3;
wire   [41:0] xor_ln1350_117_fu_1330_p2;
wire   [0:0] tmp_285_fu_2314_p3;
wire   [42:0] xor_ln1350_116_fu_1324_p2;
wire   [0:0] tmp_286_fu_2326_p3;
wire   [43:0] xor_ln1350_115_fu_1318_p2;
wire   [0:0] tmp_287_fu_2338_p3;
wire   [44:0] xor_ln1350_114_fu_1312_p2;
wire   [0:0] tmp_288_fu_2350_p3;
wire   [45:0] xor_ln1350_113_fu_1306_p2;
wire   [0:0] tmp_289_fu_2362_p3;
wire   [46:0] xor_ln1350_112_fu_1300_p2;
wire   [0:0] tmp_290_fu_2374_p3;
wire   [47:0] xor_ln1350_111_fu_1294_p2;
wire   [0:0] tmp_291_fu_2386_p3;
wire   [48:0] xor_ln1350_110_fu_1288_p2;
wire   [0:0] tmp_292_fu_2398_p3;
wire   [49:0] xor_ln1350_109_fu_1282_p2;
wire   [0:0] tmp_293_fu_2410_p3;
wire   [50:0] xor_ln1350_108_fu_1276_p2;
wire   [0:0] tmp_294_fu_2422_p3;
wire   [51:0] xor_ln1350_107_fu_1270_p2;
wire   [0:0] tmp_295_fu_2434_p3;
wire   [52:0] xor_ln1350_106_fu_1264_p2;
wire   [0:0] tmp_296_fu_2446_p3;
wire   [53:0] xor_ln1350_105_fu_1258_p2;
wire   [0:0] tmp_297_fu_2458_p3;
wire   [54:0] xor_ln1350_104_fu_1252_p2;
wire   [0:0] tmp_298_fu_2470_p3;
wire   [55:0] xor_ln1350_103_fu_1246_p2;
wire   [0:0] tmp_299_fu_2482_p3;
wire   [56:0] xor_ln1350_102_fu_1240_p2;
wire   [0:0] tmp_300_fu_2494_p3;
wire   [57:0] xor_ln1350_101_fu_1234_p2;
wire   [0:0] tmp_301_fu_2506_p3;
wire   [58:0] xor_ln1350_100_fu_1228_p2;
wire   [0:0] tmp_302_fu_2518_p3;
wire   [59:0] xor_ln1350_99_fu_1222_p2;
wire   [0:0] tmp_303_fu_2530_p3;
wire   [60:0] xor_ln1350_98_fu_1216_p2;
wire   [0:0] tmp_304_fu_2542_p3;
wire   [61:0] xor_ln1350_97_fu_1210_p2;
wire   [0:0] tmp_305_fu_2554_p3;
wire   [62:0] xor_ln1350_96_fu_1204_p2;
wire   [0:0] tmp_306_fu_2566_p3;
wire   [63:0] xor_ln1350_95_fu_1198_p2;
wire   [0:0] tmp_307_fu_2578_p3;
wire   [64:0] xor_ln1350_94_fu_1192_p2;
wire   [0:0] tmp_308_fu_2590_p3;
wire   [65:0] xor_ln1350_93_fu_1186_p2;
wire   [0:0] tmp_309_fu_2602_p3;
wire   [66:0] xor_ln1350_92_fu_1180_p2;
wire   [0:0] tmp_310_fu_2614_p3;
wire   [67:0] xor_ln1350_91_fu_1174_p2;
wire   [0:0] tmp_311_fu_2626_p3;
wire   [68:0] xor_ln1350_90_fu_1168_p2;
wire   [0:0] tmp_312_fu_2638_p3;
wire   [69:0] xor_ln1350_89_fu_1162_p2;
wire   [0:0] tmp_313_fu_2650_p3;
wire   [70:0] xor_ln1350_88_fu_1156_p2;
wire   [0:0] tmp_314_fu_2662_p3;
wire   [71:0] xor_ln1350_87_fu_1150_p2;
wire   [0:0] tmp_315_fu_2674_p3;
wire   [72:0] xor_ln1350_86_fu_1144_p2;
wire   [0:0] tmp_316_fu_2686_p3;
wire   [73:0] xor_ln1350_85_fu_1138_p2;
wire   [0:0] tmp_317_fu_2698_p3;
wire   [74:0] xor_ln1350_84_fu_1132_p2;
wire   [0:0] tmp_318_fu_2710_p3;
wire   [75:0] xor_ln1350_83_fu_1126_p2;
wire   [0:0] tmp_319_fu_2722_p3;
wire   [76:0] xor_ln1350_82_fu_1120_p2;
wire   [0:0] tmp_320_fu_2734_p3;
wire   [77:0] xor_ln1350_81_fu_1114_p2;
wire   [0:0] tmp_321_fu_2746_p3;
wire   [78:0] xor_ln1350_80_fu_1108_p2;
wire   [0:0] tmp_322_fu_2758_p3;
wire   [79:0] xor_ln1350_79_fu_1102_p2;
wire   [0:0] tmp_323_fu_2770_p3;
wire   [80:0] xor_ln1350_78_fu_1096_p2;
wire   [0:0] tmp_324_fu_2782_p3;
wire   [81:0] xor_ln1350_77_fu_1090_p2;
wire   [0:0] tmp_325_fu_2794_p3;
wire   [82:0] xor_ln1350_76_fu_1084_p2;
wire   [0:0] tmp_326_fu_2806_p3;
wire   [83:0] xor_ln1350_75_fu_1078_p2;
wire   [0:0] tmp_327_fu_2818_p3;
wire   [84:0] xor_ln1350_74_fu_1072_p2;
wire   [0:0] tmp_328_fu_2830_p3;
wire   [85:0] xor_ln1350_73_fu_1066_p2;
wire   [0:0] tmp_329_fu_2842_p3;
wire   [86:0] xor_ln1350_72_fu_1060_p2;
wire   [0:0] tmp_330_fu_2854_p3;
wire   [87:0] xor_ln1350_71_fu_1054_p2;
wire   [0:0] tmp_331_fu_2866_p3;
wire   [88:0] xor_ln1350_70_fu_1048_p2;
wire   [0:0] tmp_332_fu_2878_p3;
wire   [89:0] xor_ln1350_69_fu_1042_p2;
wire   [0:0] tmp_333_fu_2890_p3;
wire   [90:0] xor_ln1350_68_fu_1036_p2;
wire   [0:0] tmp_334_fu_2902_p3;
wire   [91:0] xor_ln1350_67_fu_1030_p2;
wire   [0:0] tmp_335_fu_2914_p3;
wire   [92:0] xor_ln1350_66_fu_1024_p2;
wire   [0:0] tmp_336_fu_2926_p3;
wire   [93:0] xor_ln1350_65_fu_1018_p2;
wire   [0:0] tmp_337_fu_2938_p3;
wire   [94:0] xor_ln1350_64_fu_1012_p2;
wire   [0:0] tmp_338_fu_2950_p3;
wire   [95:0] ret_fu_1006_p2;
wire   [0:0] tmp_339_fu_2962_p3;
wire   [1:0] zext_ln1158_fu_1830_p1;
wire   [1:0] zext_ln1148_3_fu_2202_p1;
wire   [1:0] add_ln1158_fu_2974_p2;
wire   [1:0] zext_ln1148_5_fu_2970_p1;
wire   [1:0] add_ln1158_48_fu_2980_p2;
wire   [2:0] zext_ln1159_fu_2986_p1;
wire   [2:0] zext_ln1148_fu_1842_p1;
wire   [1:0] zext_ln1158_134_fu_1854_p1;
wire   [1:0] zext_ln1158_137_fu_1890_p1;
wire   [1:0] add_ln1158_64_fu_2996_p2;
wire   [1:0] zext_ln1158_135_fu_1866_p1;
wire   [1:0] add_ln1158_65_fu_3002_p2;
wire   [2:0] zext_ln1158_225_fu_3008_p1;
wire   [2:0] add_ln1158_63_fu_2990_p2;
wire   [2:0] add_ln1158_50_fu_3012_p2;
wire   [3:0] zext_ln1159_5_fu_3018_p1;
wire   [3:0] zext_ln1158_136_fu_1878_p1;
wire   [1:0] zext_ln1158_139_fu_1914_p1;
wire   [1:0] zext_ln1158_138_fu_1902_p1;
wire   [1:0] add_ln1158_67_fu_3028_p2;
wire   [3:0] zext_ln1158_226_fu_3034_p1;
wire   [3:0] add_ln1158_66_fu_3022_p2;
wire   [1:0] zext_ln1158_141_fu_1938_p1;
wire   [1:0] zext_ln1158_140_fu_1926_p1;
wire   [1:0] add_ln1158_69_fu_3044_p2;
wire   [1:0] zext_ln1158_142_fu_1950_p1;
wire   [1:0] zext_ln1158_145_fu_1986_p1;
wire   [1:0] add_ln1158_70_fu_3054_p2;
wire   [1:0] zext_ln1158_143_fu_1962_p1;
wire   [1:0] add_ln1158_71_fu_3060_p2;
wire   [2:0] zext_ln1158_228_fu_3066_p1;
wire   [2:0] zext_ln1158_227_fu_3050_p1;
wire   [2:0] add_ln1158_72_fu_3070_p2;
wire   [3:0] zext_ln1158_229_fu_3076_p1;
wire   [3:0] add_ln1158_68_fu_3038_p2;
wire   [3:0] add_ln1158_54_fu_3080_p2;
wire   [4:0] zext_ln1159_6_fu_3086_p1;
wire   [4:0] zext_ln1158_144_fu_1974_p1;
wire   [1:0] zext_ln1158_147_fu_2010_p1;
wire   [1:0] zext_ln1158_146_fu_1998_p1;
wire   [1:0] add_ln1158_74_fu_3096_p2;
wire   [4:0] zext_ln1158_230_fu_3102_p1;
wire   [4:0] add_ln1158_73_fu_3090_p2;
wire   [1:0] zext_ln1158_149_fu_2034_p1;
wire   [1:0] zext_ln1158_148_fu_2022_p1;
wire   [1:0] add_ln1158_76_fu_3112_p2;
wire   [1:0] zext_ln1158_151_fu_2058_p1;
wire   [1:0] zext_ln1158_150_fu_2046_p1;
wire   [1:0] add_ln1158_77_fu_3122_p2;
wire   [2:0] zext_ln1158_232_fu_3128_p1;
wire   [2:0] zext_ln1158_231_fu_3118_p1;
wire   [2:0] add_ln1158_79_fu_3132_p2;
wire   [4:0] zext_ln1158_233_fu_3138_p1;
wire   [4:0] add_ln1158_75_fu_3106_p2;
wire   [1:0] zext_ln1158_153_fu_2082_p1;
wire   [1:0] zext_ln1158_152_fu_2070_p1;
wire   [1:0] add_ln1158_81_fu_3148_p2;
wire   [1:0] zext_ln1158_155_fu_2106_p1;
wire   [1:0] zext_ln1158_154_fu_2094_p1;
wire   [1:0] add_ln1158_82_fu_3158_p2;
wire   [2:0] zext_ln1158_235_fu_3164_p1;
wire   [2:0] zext_ln1158_234_fu_3154_p1;
wire   [2:0] add_ln1158_83_fu_3168_p2;
wire   [1:0] zext_ln1158_157_fu_2130_p1;
wire   [1:0] zext_ln1158_156_fu_2118_p1;
wire   [1:0] add_ln1158_84_fu_3178_p2;
wire   [1:0] zext_ln1158_158_fu_2142_p1;
wire   [1:0] zext_ln1158_161_fu_2178_p1;
wire   [1:0] add_ln1158_85_fu_3188_p2;
wire   [1:0] zext_ln1158_159_fu_2154_p1;
wire   [1:0] add_ln1158_86_fu_3194_p2;
wire   [2:0] zext_ln1158_238_fu_3200_p1;
wire   [2:0] zext_ln1158_237_fu_3184_p1;
wire   [2:0] add_ln1158_87_fu_3204_p2;
wire   [3:0] zext_ln1158_239_fu_3210_p1;
wire   [3:0] zext_ln1158_236_fu_3174_p1;
wire   [3:0] add_ln1158_88_fu_3214_p2;
wire   [4:0] zext_ln1158_240_fu_3220_p1;
wire   [4:0] add_ln1158_80_fu_3142_p2;
wire   [4:0] add_ln1158_62_fu_3224_p2;
wire   [5:0] zext_ln1159_7_fu_3230_p1;
wire   [5:0] zext_ln1158_160_fu_2166_p1;
wire   [1:0] zext_ln1158_162_fu_2190_p1;
wire   [1:0] zext_ln1158_164_fu_2226_p1;
wire   [1:0] add_ln1158_90_fu_3240_p2;
wire   [5:0] zext_ln1158_241_fu_3246_p1;
wire   [5:0] add_ln1158_89_fu_3234_p2;
wire   [1:0] zext_ln1158_163_fu_2214_p1;
wire   [1:0] zext_ln1158_166_fu_2250_p1;
wire   [1:0] add_ln1158_92_fu_3256_p2;
wire   [1:0] zext_ln1158_165_fu_2238_p1;
wire   [1:0] zext_ln1158_168_fu_2274_p1;
wire   [1:0] add_ln1158_93_fu_3266_p2;
wire   [2:0] zext_ln1158_243_fu_3272_p1;
wire   [2:0] zext_ln1158_242_fu_3262_p1;
wire   [2:0] add_ln1158_94_fu_3276_p2;
wire   [5:0] zext_ln1158_244_fu_3282_p1;
wire   [5:0] add_ln1158_91_fu_3250_p2;
wire   [1:0] zext_ln1158_167_fu_2262_p1;
wire   [1:0] zext_ln1158_170_fu_2298_p1;
wire   [1:0] add_ln1158_96_fu_3292_p2;
wire   [1:0] zext_ln1158_169_fu_2286_p1;
wire   [1:0] zext_ln1158_172_fu_2322_p1;
wire   [1:0] add_ln1158_97_fu_3302_p2;
wire   [2:0] zext_ln1158_246_fu_3308_p1;
wire   [2:0] zext_ln1158_245_fu_3298_p1;
wire   [2:0] add_ln1158_98_fu_3312_p2;
wire   [1:0] zext_ln1158_171_fu_2310_p1;
wire   [1:0] zext_ln1158_174_fu_2346_p1;
wire   [1:0] add_ln1158_99_fu_3322_p2;
wire   [1:0] zext_ln1158_173_fu_2334_p1;
wire   [1:0] zext_ln1158_176_fu_2370_p1;
wire   [1:0] add_ln1158_100_fu_3332_p2;
wire   [2:0] zext_ln1158_249_fu_3338_p1;
wire   [2:0] zext_ln1158_248_fu_3328_p1;
wire   [2:0] add_ln1158_101_fu_3342_p2;
wire   [3:0] zext_ln1158_250_fu_3348_p1;
wire   [3:0] zext_ln1158_247_fu_3318_p1;
wire   [3:0] add_ln1158_102_fu_3352_p2;
wire   [5:0] zext_ln1158_251_fu_3358_p1;
wire   [5:0] add_ln1158_95_fu_3286_p2;
wire   [1:0] zext_ln1158_175_fu_2358_p1;
wire   [1:0] zext_ln1158_178_fu_2394_p1;
wire   [1:0] add_ln1158_104_fu_3368_p2;
wire   [1:0] zext_ln1158_177_fu_2382_p1;
wire   [1:0] zext_ln1158_180_fu_2418_p1;
wire   [1:0] add_ln1158_105_fu_3378_p2;
wire   [2:0] zext_ln1158_253_fu_3384_p1;
wire   [2:0] zext_ln1158_252_fu_3374_p1;
wire   [2:0] add_ln1158_106_fu_3388_p2;
wire   [1:0] zext_ln1158_179_fu_2406_p1;
wire   [1:0] zext_ln1158_182_fu_2442_p1;
wire   [1:0] add_ln1158_107_fu_3398_p2;
wire   [1:0] zext_ln1158_181_fu_2430_p1;
wire   [1:0] zext_ln1158_184_fu_2466_p1;
wire   [1:0] add_ln1158_108_fu_3408_p2;
wire   [2:0] zext_ln1158_256_fu_3414_p1;
wire   [2:0] zext_ln1158_255_fu_3404_p1;
wire   [2:0] add_ln1158_109_fu_3418_p2;
wire   [3:0] zext_ln1158_257_fu_3424_p1;
wire   [3:0] zext_ln1158_254_fu_3394_p1;
wire   [3:0] add_ln1158_110_fu_3428_p2;
wire   [1:0] zext_ln1158_183_fu_2454_p1;
wire   [1:0] zext_ln1158_186_fu_2490_p1;
wire   [1:0] add_ln1158_111_fu_3438_p2;
wire   [1:0] zext_ln1158_185_fu_2478_p1;
wire   [1:0] zext_ln1158_188_fu_2514_p1;
wire   [1:0] add_ln1158_112_fu_3448_p2;
wire   [2:0] zext_ln1158_260_fu_3454_p1;
wire   [2:0] zext_ln1158_259_fu_3444_p1;
wire   [2:0] add_ln1158_113_fu_3458_p2;
wire   [1:0] zext_ln1158_187_fu_2502_p1;
wire   [1:0] zext_ln1158_190_fu_2538_p1;
wire   [1:0] add_ln1158_114_fu_3468_p2;
wire   [1:0] zext_ln1158_192_fu_2562_p1;
wire   [1:0] zext_ln1158_191_fu_2550_p1;
wire   [1:0] add_ln1158_115_fu_3478_p2;
wire   [1:0] zext_ln1158_189_fu_2526_p1;
wire   [1:0] add_ln1158_116_fu_3484_p2;
wire   [2:0] zext_ln1158_263_fu_3490_p1;
wire   [2:0] zext_ln1158_262_fu_3474_p1;
wire   [2:0] add_ln1158_117_fu_3494_p2;
wire   [3:0] zext_ln1158_264_fu_3500_p1;
wire   [3:0] zext_ln1158_261_fu_3464_p1;
wire   [3:0] add_ln1158_118_fu_3504_p2;
wire   [4:0] zext_ln1158_265_fu_3510_p1;
wire   [4:0] zext_ln1158_258_fu_3434_p1;
wire   [4:0] add_ln1158_119_fu_3514_p2;
wire   [5:0] zext_ln1158_266_fu_3520_p1;
wire   [5:0] add_ln1158_103_fu_3362_p2;
wire   [5:0] add_ln1158_78_fu_3524_p2;
wire   [6:0] zext_ln1159_8_fu_3530_p1;
wire   [6:0] zext_ln1148_4_fu_2586_p1;
wire   [1:0] zext_ln1158_193_fu_2574_p1;
wire   [1:0] zext_ln1158_195_fu_2610_p1;
wire   [1:0] add_ln1159_33_fu_3540_p2;
wire   [6:0] zext_ln1159_31_fu_3546_p1;
wire   [6:0] add_ln1159_fu_3534_p2;
wire   [1:0] zext_ln1158_194_fu_2598_p1;
wire   [1:0] zext_ln1158_197_fu_2634_p1;
wire   [1:0] add_ln1159_35_fu_3556_p2;
wire   [1:0] zext_ln1158_196_fu_2622_p1;
wire   [1:0] zext_ln1158_199_fu_2658_p1;
wire   [1:0] add_ln1159_36_fu_3566_p2;
wire   [2:0] zext_ln1159_33_fu_3572_p1;
wire   [2:0] zext_ln1159_32_fu_3562_p1;
wire   [2:0] add_ln1159_37_fu_3576_p2;
wire   [6:0] zext_ln1159_34_fu_3582_p1;
wire   [6:0] add_ln1159_34_fu_3550_p2;
wire   [1:0] zext_ln1158_198_fu_2646_p1;
wire   [1:0] zext_ln1158_201_fu_2682_p1;
wire   [1:0] add_ln1159_39_fu_3592_p2;
wire   [1:0] zext_ln1158_200_fu_2670_p1;
wire   [1:0] zext_ln1158_203_fu_2706_p1;
wire   [1:0] add_ln1159_40_fu_3602_p2;
wire   [2:0] zext_ln1159_36_fu_3608_p1;
wire   [2:0] zext_ln1159_35_fu_3598_p1;
wire   [2:0] add_ln1159_41_fu_3612_p2;
wire   [1:0] zext_ln1158_202_fu_2694_p1;
wire   [1:0] zext_ln1158_205_fu_2730_p1;
wire   [1:0] add_ln1159_42_fu_3622_p2;
wire   [1:0] zext_ln1158_207_fu_2754_p1;
wire   [1:0] zext_ln1158_206_fu_2742_p1;
wire   [1:0] add_ln1159_43_fu_3632_p2;
wire   [1:0] zext_ln1158_204_fu_2718_p1;
wire   [1:0] add_ln1159_44_fu_3638_p2;
wire   [2:0] zext_ln1159_39_fu_3644_p1;
wire   [2:0] zext_ln1159_38_fu_3628_p1;
wire   [2:0] add_ln1159_45_fu_3648_p2;
wire   [3:0] zext_ln1159_40_fu_3654_p1;
wire   [3:0] zext_ln1159_37_fu_3618_p1;
wire   [3:0] add_ln1159_46_fu_3658_p2;
wire   [6:0] zext_ln1159_41_fu_3664_p1;
wire   [6:0] add_ln1159_38_fu_3586_p2;
wire   [1:0] zext_ln1158_209_fu_2778_p1;
wire   [1:0] zext_ln1158_208_fu_2766_p1;
wire   [1:0] add_ln1159_48_fu_3674_p2;
wire   [1:0] zext_ln1158_211_fu_2802_p1;
wire   [1:0] zext_ln1158_210_fu_2790_p1;
wire   [1:0] add_ln1159_49_fu_3684_p2;
wire   [2:0] zext_ln1159_43_fu_3690_p1;
wire   [2:0] zext_ln1159_42_fu_3680_p1;
wire   [2:0] add_ln1159_50_fu_3694_p2;
wire   [1:0] zext_ln1158_213_fu_2826_p1;
wire   [1:0] zext_ln1158_212_fu_2814_p1;
wire   [1:0] add_ln1159_51_fu_3704_p2;
wire   [1:0] zext_ln1158_215_fu_2850_p1;
wire   [1:0] zext_ln1158_214_fu_2838_p1;
wire   [1:0] add_ln1159_52_fu_3714_p2;
wire   [2:0] zext_ln1159_46_fu_3720_p1;
wire   [2:0] zext_ln1159_45_fu_3710_p1;
wire   [2:0] add_ln1159_53_fu_3724_p2;
wire   [3:0] zext_ln1159_47_fu_3730_p1;
wire   [3:0] zext_ln1159_44_fu_3700_p1;
wire   [3:0] add_ln1159_54_fu_3734_p2;
wire   [1:0] zext_ln1158_217_fu_2874_p1;
wire   [1:0] zext_ln1158_216_fu_2862_p1;
wire   [1:0] add_ln1159_55_fu_3744_p2;
wire   [1:0] zext_ln1158_219_fu_2898_p1;
wire   [1:0] zext_ln1158_218_fu_2886_p1;
wire   [1:0] add_ln1159_56_fu_3754_p2;
wire   [2:0] zext_ln1159_50_fu_3760_p1;
wire   [2:0] zext_ln1159_49_fu_3750_p1;
wire   [2:0] add_ln1159_57_fu_3764_p2;
wire   [1:0] zext_ln1158_221_fu_2922_p1;
wire   [1:0] zext_ln1158_220_fu_2910_p1;
wire   [1:0] add_ln1159_58_fu_3774_p2;
wire   [1:0] zext_ln1158_222_fu_2934_p1;
wire   [1:0] zext_ln1158_224_fu_2958_p1;
wire   [1:0] add_ln1159_59_fu_3784_p2;
wire   [1:0] zext_ln1158_223_fu_2946_p1;
wire   [1:0] add_ln1159_60_fu_3790_p2;
wire   [2:0] zext_ln1159_53_fu_3796_p1;
wire   [2:0] zext_ln1159_52_fu_3780_p1;
wire   [2:0] add_ln1159_61_fu_3800_p2;
wire   [3:0] zext_ln1159_54_fu_3806_p1;
wire   [3:0] zext_ln1159_51_fu_3770_p1;
wire   [3:0] add_ln1159_62_fu_3810_p2;
wire   [4:0] zext_ln1159_55_fu_3816_p1;
wire   [4:0] zext_ln1159_48_fu_3740_p1;
wire   [4:0] add_ln1159_63_fu_3820_p2;
wire   [6:0] zext_ln1159_56_fu_3826_p1;
wire   [6:0] add_ln1159_47_fu_3668_p2;
wire   [6:0] haming_dis_fu_3830_p2;
reg   [6:0] ap_return_preg;
reg   [0:0] ap_NS_fsm;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
#0 ap_return_preg = 7'd0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((ap_start == 1'b0) | (backet_location_out_full_n == 1'b0) | (query_out_full_n == 1'b0) | (hash_table_out_full_n == 1'b0) | (1'b0 == FP_DB_out_full_n) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_preg <= 7'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (backet_location_out_full_n == 1'b0) | (query_out_full_n == 1'b0) | (hash_table_out_full_n == 1'b0) | (1'b0 == FP_DB_out_full_n) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_preg <= haming_dis_fu_3830_p2;
        end
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        FP_DB_out_blk_n = FP_DB_out_full_n;
    end else begin
        FP_DB_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (backet_location_out_full_n == 1'b0) | (query_out_full_n == 1'b0) | (hash_table_out_full_n == 1'b0) | (1'b0 == FP_DB_out_full_n) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        FP_DB_out_write = 1'b1;
    end else begin
        FP_DB_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (backet_location_out_full_n == 1'b0) | (query_out_full_n == 1'b0) | (hash_table_out_full_n == 1'b0) | (1'b0 == FP_DB_out_full_n) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (backet_location_out_full_n == 1'b0) | (query_out_full_n == 1'b0) | (hash_table_out_full_n == 1'b0) | (1'b0 == FP_DB_out_full_n) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (backet_location_out_full_n == 1'b0) | (query_out_full_n == 1'b0) | (hash_table_out_full_n == 1'b0) | (1'b0 == FP_DB_out_full_n) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return = haming_dis_fu_3830_p2;
    end else begin
        ap_return = ap_return_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        backet_location_out_blk_n = backet_location_out_full_n;
    end else begin
        backet_location_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (backet_location_out_full_n == 1'b0) | (query_out_full_n == 1'b0) | (hash_table_out_full_n == 1'b0) | (1'b0 == FP_DB_out_full_n) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        backet_location_out_write = 1'b1;
    end else begin
        backet_location_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        hash_table_out_blk_n = hash_table_out_full_n;
    end else begin
        hash_table_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (backet_location_out_full_n == 1'b0) | (query_out_full_n == 1'b0) | (hash_table_out_full_n == 1'b0) | (1'b0 == FP_DB_out_full_n) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        hash_table_out_write = 1'b1;
    end else begin
        hash_table_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        query_out_blk_n = query_out_full_n;
    end else begin
        query_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (backet_location_out_full_n == 1'b0) | (query_out_full_n == 1'b0) | (hash_table_out_full_n == 1'b0) | (1'b0 == FP_DB_out_full_n) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        query_out_write = 1'b1;
    end else begin
        query_out_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign FP_DB_out_din = FP_DB;

assign add_ln1158_100_fu_3332_p2 = (zext_ln1158_173_fu_2334_p1 + zext_ln1158_176_fu_2370_p1);

assign add_ln1158_101_fu_3342_p2 = (zext_ln1158_249_fu_3338_p1 + zext_ln1158_248_fu_3328_p1);

assign add_ln1158_102_fu_3352_p2 = (zext_ln1158_250_fu_3348_p1 + zext_ln1158_247_fu_3318_p1);

assign add_ln1158_103_fu_3362_p2 = (zext_ln1158_251_fu_3358_p1 + add_ln1158_95_fu_3286_p2);

assign add_ln1158_104_fu_3368_p2 = (zext_ln1158_175_fu_2358_p1 + zext_ln1158_178_fu_2394_p1);

assign add_ln1158_105_fu_3378_p2 = (zext_ln1158_177_fu_2382_p1 + zext_ln1158_180_fu_2418_p1);

assign add_ln1158_106_fu_3388_p2 = (zext_ln1158_253_fu_3384_p1 + zext_ln1158_252_fu_3374_p1);

assign add_ln1158_107_fu_3398_p2 = (zext_ln1158_179_fu_2406_p1 + zext_ln1158_182_fu_2442_p1);

assign add_ln1158_108_fu_3408_p2 = (zext_ln1158_181_fu_2430_p1 + zext_ln1158_184_fu_2466_p1);

assign add_ln1158_109_fu_3418_p2 = (zext_ln1158_256_fu_3414_p1 + zext_ln1158_255_fu_3404_p1);

assign add_ln1158_110_fu_3428_p2 = (zext_ln1158_257_fu_3424_p1 + zext_ln1158_254_fu_3394_p1);

assign add_ln1158_111_fu_3438_p2 = (zext_ln1158_183_fu_2454_p1 + zext_ln1158_186_fu_2490_p1);

assign add_ln1158_112_fu_3448_p2 = (zext_ln1158_185_fu_2478_p1 + zext_ln1158_188_fu_2514_p1);

assign add_ln1158_113_fu_3458_p2 = (zext_ln1158_260_fu_3454_p1 + zext_ln1158_259_fu_3444_p1);

assign add_ln1158_114_fu_3468_p2 = (zext_ln1158_187_fu_2502_p1 + zext_ln1158_190_fu_2538_p1);

assign add_ln1158_115_fu_3478_p2 = (zext_ln1158_192_fu_2562_p1 + zext_ln1158_191_fu_2550_p1);

assign add_ln1158_116_fu_3484_p2 = (add_ln1158_115_fu_3478_p2 + zext_ln1158_189_fu_2526_p1);

assign add_ln1158_117_fu_3494_p2 = (zext_ln1158_263_fu_3490_p1 + zext_ln1158_262_fu_3474_p1);

assign add_ln1158_118_fu_3504_p2 = (zext_ln1158_264_fu_3500_p1 + zext_ln1158_261_fu_3464_p1);

assign add_ln1158_119_fu_3514_p2 = (zext_ln1158_265_fu_3510_p1 + zext_ln1158_258_fu_3434_p1);

assign add_ln1158_48_fu_2980_p2 = (add_ln1158_fu_2974_p2 + zext_ln1148_5_fu_2970_p1);

assign add_ln1158_50_fu_3012_p2 = (zext_ln1158_225_fu_3008_p1 + add_ln1158_63_fu_2990_p2);

assign add_ln1158_54_fu_3080_p2 = (zext_ln1158_229_fu_3076_p1 + add_ln1158_68_fu_3038_p2);

assign add_ln1158_62_fu_3224_p2 = (zext_ln1158_240_fu_3220_p1 + add_ln1158_80_fu_3142_p2);

assign add_ln1158_63_fu_2990_p2 = (zext_ln1159_fu_2986_p1 + zext_ln1148_fu_1842_p1);

assign add_ln1158_64_fu_2996_p2 = (zext_ln1158_134_fu_1854_p1 + zext_ln1158_137_fu_1890_p1);

assign add_ln1158_65_fu_3002_p2 = (add_ln1158_64_fu_2996_p2 + zext_ln1158_135_fu_1866_p1);

assign add_ln1158_66_fu_3022_p2 = (zext_ln1159_5_fu_3018_p1 + zext_ln1158_136_fu_1878_p1);

assign add_ln1158_67_fu_3028_p2 = (zext_ln1158_139_fu_1914_p1 + zext_ln1158_138_fu_1902_p1);

assign add_ln1158_68_fu_3038_p2 = (zext_ln1158_226_fu_3034_p1 + add_ln1158_66_fu_3022_p2);

assign add_ln1158_69_fu_3044_p2 = (zext_ln1158_141_fu_1938_p1 + zext_ln1158_140_fu_1926_p1);

assign add_ln1158_70_fu_3054_p2 = (zext_ln1158_142_fu_1950_p1 + zext_ln1158_145_fu_1986_p1);

assign add_ln1158_71_fu_3060_p2 = (add_ln1158_70_fu_3054_p2 + zext_ln1158_143_fu_1962_p1);

assign add_ln1158_72_fu_3070_p2 = (zext_ln1158_228_fu_3066_p1 + zext_ln1158_227_fu_3050_p1);

assign add_ln1158_73_fu_3090_p2 = (zext_ln1159_6_fu_3086_p1 + zext_ln1158_144_fu_1974_p1);

assign add_ln1158_74_fu_3096_p2 = (zext_ln1158_147_fu_2010_p1 + zext_ln1158_146_fu_1998_p1);

assign add_ln1158_75_fu_3106_p2 = (zext_ln1158_230_fu_3102_p1 + add_ln1158_73_fu_3090_p2);

assign add_ln1158_76_fu_3112_p2 = (zext_ln1158_149_fu_2034_p1 + zext_ln1158_148_fu_2022_p1);

assign add_ln1158_77_fu_3122_p2 = (zext_ln1158_151_fu_2058_p1 + zext_ln1158_150_fu_2046_p1);

assign add_ln1158_78_fu_3524_p2 = (zext_ln1158_266_fu_3520_p1 + add_ln1158_103_fu_3362_p2);

assign add_ln1158_79_fu_3132_p2 = (zext_ln1158_232_fu_3128_p1 + zext_ln1158_231_fu_3118_p1);

assign add_ln1158_80_fu_3142_p2 = (zext_ln1158_233_fu_3138_p1 + add_ln1158_75_fu_3106_p2);

assign add_ln1158_81_fu_3148_p2 = (zext_ln1158_153_fu_2082_p1 + zext_ln1158_152_fu_2070_p1);

assign add_ln1158_82_fu_3158_p2 = (zext_ln1158_155_fu_2106_p1 + zext_ln1158_154_fu_2094_p1);

assign add_ln1158_83_fu_3168_p2 = (zext_ln1158_235_fu_3164_p1 + zext_ln1158_234_fu_3154_p1);

assign add_ln1158_84_fu_3178_p2 = (zext_ln1158_157_fu_2130_p1 + zext_ln1158_156_fu_2118_p1);

assign add_ln1158_85_fu_3188_p2 = (zext_ln1158_158_fu_2142_p1 + zext_ln1158_161_fu_2178_p1);

assign add_ln1158_86_fu_3194_p2 = (add_ln1158_85_fu_3188_p2 + zext_ln1158_159_fu_2154_p1);

assign add_ln1158_87_fu_3204_p2 = (zext_ln1158_238_fu_3200_p1 + zext_ln1158_237_fu_3184_p1);

assign add_ln1158_88_fu_3214_p2 = (zext_ln1158_239_fu_3210_p1 + zext_ln1158_236_fu_3174_p1);

assign add_ln1158_89_fu_3234_p2 = (zext_ln1159_7_fu_3230_p1 + zext_ln1158_160_fu_2166_p1);

assign add_ln1158_90_fu_3240_p2 = (zext_ln1158_162_fu_2190_p1 + zext_ln1158_164_fu_2226_p1);

assign add_ln1158_91_fu_3250_p2 = (zext_ln1158_241_fu_3246_p1 + add_ln1158_89_fu_3234_p2);

assign add_ln1158_92_fu_3256_p2 = (zext_ln1158_163_fu_2214_p1 + zext_ln1158_166_fu_2250_p1);

assign add_ln1158_93_fu_3266_p2 = (zext_ln1158_165_fu_2238_p1 + zext_ln1158_168_fu_2274_p1);

assign add_ln1158_94_fu_3276_p2 = (zext_ln1158_243_fu_3272_p1 + zext_ln1158_242_fu_3262_p1);

assign add_ln1158_95_fu_3286_p2 = (zext_ln1158_244_fu_3282_p1 + add_ln1158_91_fu_3250_p2);

assign add_ln1158_96_fu_3292_p2 = (zext_ln1158_167_fu_2262_p1 + zext_ln1158_170_fu_2298_p1);

assign add_ln1158_97_fu_3302_p2 = (zext_ln1158_169_fu_2286_p1 + zext_ln1158_172_fu_2322_p1);

assign add_ln1158_98_fu_3312_p2 = (zext_ln1158_246_fu_3308_p1 + zext_ln1158_245_fu_3298_p1);

assign add_ln1158_99_fu_3322_p2 = (zext_ln1158_171_fu_2310_p1 + zext_ln1158_174_fu_2346_p1);

assign add_ln1158_fu_2974_p2 = (zext_ln1158_fu_1830_p1 + zext_ln1148_3_fu_2202_p1);

assign add_ln1159_33_fu_3540_p2 = (zext_ln1158_193_fu_2574_p1 + zext_ln1158_195_fu_2610_p1);

assign add_ln1159_34_fu_3550_p2 = (zext_ln1159_31_fu_3546_p1 + add_ln1159_fu_3534_p2);

assign add_ln1159_35_fu_3556_p2 = (zext_ln1158_194_fu_2598_p1 + zext_ln1158_197_fu_2634_p1);

assign add_ln1159_36_fu_3566_p2 = (zext_ln1158_196_fu_2622_p1 + zext_ln1158_199_fu_2658_p1);

assign add_ln1159_37_fu_3576_p2 = (zext_ln1159_33_fu_3572_p1 + zext_ln1159_32_fu_3562_p1);

assign add_ln1159_38_fu_3586_p2 = (zext_ln1159_34_fu_3582_p1 + add_ln1159_34_fu_3550_p2);

assign add_ln1159_39_fu_3592_p2 = (zext_ln1158_198_fu_2646_p1 + zext_ln1158_201_fu_2682_p1);

assign add_ln1159_40_fu_3602_p2 = (zext_ln1158_200_fu_2670_p1 + zext_ln1158_203_fu_2706_p1);

assign add_ln1159_41_fu_3612_p2 = (zext_ln1159_36_fu_3608_p1 + zext_ln1159_35_fu_3598_p1);

assign add_ln1159_42_fu_3622_p2 = (zext_ln1158_202_fu_2694_p1 + zext_ln1158_205_fu_2730_p1);

assign add_ln1159_43_fu_3632_p2 = (zext_ln1158_207_fu_2754_p1 + zext_ln1158_206_fu_2742_p1);

assign add_ln1159_44_fu_3638_p2 = (add_ln1159_43_fu_3632_p2 + zext_ln1158_204_fu_2718_p1);

assign add_ln1159_45_fu_3648_p2 = (zext_ln1159_39_fu_3644_p1 + zext_ln1159_38_fu_3628_p1);

assign add_ln1159_46_fu_3658_p2 = (zext_ln1159_40_fu_3654_p1 + zext_ln1159_37_fu_3618_p1);

assign add_ln1159_47_fu_3668_p2 = (zext_ln1159_41_fu_3664_p1 + add_ln1159_38_fu_3586_p2);

assign add_ln1159_48_fu_3674_p2 = (zext_ln1158_209_fu_2778_p1 + zext_ln1158_208_fu_2766_p1);

assign add_ln1159_49_fu_3684_p2 = (zext_ln1158_211_fu_2802_p1 + zext_ln1158_210_fu_2790_p1);

assign add_ln1159_50_fu_3694_p2 = (zext_ln1159_43_fu_3690_p1 + zext_ln1159_42_fu_3680_p1);

assign add_ln1159_51_fu_3704_p2 = (zext_ln1158_213_fu_2826_p1 + zext_ln1158_212_fu_2814_p1);

assign add_ln1159_52_fu_3714_p2 = (zext_ln1158_215_fu_2850_p1 + zext_ln1158_214_fu_2838_p1);

assign add_ln1159_53_fu_3724_p2 = (zext_ln1159_46_fu_3720_p1 + zext_ln1159_45_fu_3710_p1);

assign add_ln1159_54_fu_3734_p2 = (zext_ln1159_47_fu_3730_p1 + zext_ln1159_44_fu_3700_p1);

assign add_ln1159_55_fu_3744_p2 = (zext_ln1158_217_fu_2874_p1 + zext_ln1158_216_fu_2862_p1);

assign add_ln1159_56_fu_3754_p2 = (zext_ln1158_219_fu_2898_p1 + zext_ln1158_218_fu_2886_p1);

assign add_ln1159_57_fu_3764_p2 = (zext_ln1159_50_fu_3760_p1 + zext_ln1159_49_fu_3750_p1);

assign add_ln1159_58_fu_3774_p2 = (zext_ln1158_221_fu_2922_p1 + zext_ln1158_220_fu_2910_p1);

assign add_ln1159_59_fu_3784_p2 = (zext_ln1158_222_fu_2934_p1 + zext_ln1158_224_fu_2958_p1);

assign add_ln1159_60_fu_3790_p2 = (add_ln1159_59_fu_3784_p2 + zext_ln1158_223_fu_2946_p1);

assign add_ln1159_61_fu_3800_p2 = (zext_ln1159_53_fu_3796_p1 + zext_ln1159_52_fu_3780_p1);

assign add_ln1159_62_fu_3810_p2 = (zext_ln1159_54_fu_3806_p1 + zext_ln1159_51_fu_3770_p1);

assign add_ln1159_63_fu_3820_p2 = (zext_ln1159_55_fu_3816_p1 + zext_ln1159_48_fu_3740_p1);

assign add_ln1159_fu_3534_p2 = (zext_ln1159_8_fu_3530_p1 + zext_ln1148_4_fu_2586_p1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (backet_location_out_full_n == 1'b0) | (query_out_full_n == 1'b0) | (hash_table_out_full_n == 1'b0) | (1'b0 == FP_DB_out_full_n) | (ap_done_reg == 1'b1));
end

assign backet_location_out_din = backet_location;

assign haming_dis_fu_3830_p2 = (zext_ln1159_56_fu_3826_p1 + add_ln1159_47_fu_3668_p2);

assign hash_table_out_din = hash_table;

assign query_out_din = query;

assign ret_fu_1006_p2 = (temp_flame96 ^ flame96);

assign tmp_246_fu_1846_p3 = xor_ln1158_58_fu_1812_p2[32'd2];

assign tmp_247_fu_1858_p3 = xor_ln1158_57_fu_1806_p2[32'd3];

assign tmp_248_fu_1870_p3 = xor_ln1158_56_fu_1800_p2[32'd4];

assign tmp_249_fu_1882_p3 = xor_ln1158_55_fu_1794_p2[32'd5];

assign tmp_250_fu_1894_p3 = xor_ln1158_54_fu_1788_p2[32'd6];

assign tmp_251_fu_1906_p3 = xor_ln1158_53_fu_1782_p2[32'd7];

assign tmp_252_fu_1918_p3 = xor_ln1158_52_fu_1776_p2[32'd8];

assign tmp_253_fu_1930_p3 = xor_ln1158_51_fu_1770_p2[32'd9];

assign tmp_254_fu_1942_p3 = xor_ln1158_50_fu_1764_p2[32'd10];

assign tmp_255_fu_1954_p3 = xor_ln1158_49_fu_1758_p2[32'd11];

assign tmp_256_fu_1966_p3 = xor_ln1158_48_fu_1752_p2[32'd12];

assign tmp_257_fu_1978_p3 = xor_ln1158_47_fu_1746_p2[32'd13];

assign tmp_258_fu_1990_p3 = xor_ln1158_46_fu_1740_p2[32'd14];

assign tmp_259_fu_2002_p3 = xor_ln1158_45_fu_1734_p2[32'd15];

assign tmp_260_fu_2014_p3 = xor_ln1158_44_fu_1728_p2[32'd16];

assign tmp_261_fu_2026_p3 = xor_ln1158_43_fu_1722_p2[32'd17];

assign tmp_262_fu_2038_p3 = xor_ln1158_42_fu_1716_p2[32'd18];

assign tmp_263_fu_2050_p3 = xor_ln1158_41_fu_1710_p2[32'd19];

assign tmp_264_fu_2062_p3 = xor_ln1158_40_fu_1704_p2[32'd20];

assign tmp_265_fu_2074_p3 = xor_ln1158_39_fu_1698_p2[32'd21];

assign tmp_266_fu_2086_p3 = xor_ln1158_38_fu_1692_p2[32'd22];

assign tmp_267_fu_2098_p3 = xor_ln1158_37_fu_1686_p2[32'd23];

assign tmp_268_fu_2110_p3 = xor_ln1158_36_fu_1680_p2[32'd24];

assign tmp_269_fu_2122_p3 = xor_ln1158_35_fu_1674_p2[32'd25];

assign tmp_270_fu_2134_p3 = xor_ln1158_34_fu_1668_p2[32'd26];

assign tmp_271_fu_2146_p3 = xor_ln1158_33_fu_1662_p2[32'd27];

assign tmp_272_fu_2158_p3 = xor_ln1158_32_fu_1656_p2[32'd28];

assign tmp_273_fu_2170_p3 = xor_ln1158_31_fu_1650_p2[32'd29];

assign tmp_274_fu_2182_p3 = xor_ln1158_fu_1644_p2[32'd30];

assign tmp_275_fu_2194_p3 = xor_ln819_fu_1638_p2[32'd31];

assign tmp_276_fu_2206_p3 = xor_ln1350_126_fu_1384_p2[32'd32];

assign tmp_277_fu_2218_p3 = xor_ln1350_125_fu_1378_p2[32'd33];

assign tmp_278_fu_2230_p3 = xor_ln1350_124_fu_1372_p2[32'd34];

assign tmp_279_fu_2242_p3 = xor_ln1350_123_fu_1366_p2[32'd35];

assign tmp_280_fu_2254_p3 = xor_ln1350_122_fu_1360_p2[32'd36];

assign tmp_281_fu_2266_p3 = xor_ln1350_121_fu_1354_p2[32'd37];

assign tmp_282_fu_2278_p3 = xor_ln1350_120_fu_1348_p2[32'd38];

assign tmp_283_fu_2290_p3 = xor_ln1350_119_fu_1342_p2[32'd39];

assign tmp_284_fu_2302_p3 = xor_ln1350_118_fu_1336_p2[32'd40];

assign tmp_285_fu_2314_p3 = xor_ln1350_117_fu_1330_p2[32'd41];

assign tmp_286_fu_2326_p3 = xor_ln1350_116_fu_1324_p2[32'd42];

assign tmp_287_fu_2338_p3 = xor_ln1350_115_fu_1318_p2[32'd43];

assign tmp_288_fu_2350_p3 = xor_ln1350_114_fu_1312_p2[32'd44];

assign tmp_289_fu_2362_p3 = xor_ln1350_113_fu_1306_p2[32'd45];

assign tmp_290_fu_2374_p3 = xor_ln1350_112_fu_1300_p2[32'd46];

assign tmp_291_fu_2386_p3 = xor_ln1350_111_fu_1294_p2[32'd47];

assign tmp_292_fu_2398_p3 = xor_ln1350_110_fu_1288_p2[32'd48];

assign tmp_293_fu_2410_p3 = xor_ln1350_109_fu_1282_p2[32'd49];

assign tmp_294_fu_2422_p3 = xor_ln1350_108_fu_1276_p2[32'd50];

assign tmp_295_fu_2434_p3 = xor_ln1350_107_fu_1270_p2[32'd51];

assign tmp_296_fu_2446_p3 = xor_ln1350_106_fu_1264_p2[32'd52];

assign tmp_297_fu_2458_p3 = xor_ln1350_105_fu_1258_p2[32'd53];

assign tmp_298_fu_2470_p3 = xor_ln1350_104_fu_1252_p2[32'd54];

assign tmp_299_fu_2482_p3 = xor_ln1350_103_fu_1246_p2[32'd55];

assign tmp_300_fu_2494_p3 = xor_ln1350_102_fu_1240_p2[32'd56];

assign tmp_301_fu_2506_p3 = xor_ln1350_101_fu_1234_p2[32'd57];

assign tmp_302_fu_2518_p3 = xor_ln1350_100_fu_1228_p2[32'd58];

assign tmp_303_fu_2530_p3 = xor_ln1350_99_fu_1222_p2[32'd59];

assign tmp_304_fu_2542_p3 = xor_ln1350_98_fu_1216_p2[32'd60];

assign tmp_305_fu_2554_p3 = xor_ln1350_97_fu_1210_p2[32'd61];

assign tmp_306_fu_2566_p3 = xor_ln1350_96_fu_1204_p2[32'd62];

assign tmp_307_fu_2578_p3 = xor_ln1350_95_fu_1198_p2[32'd63];

assign tmp_308_fu_2590_p3 = xor_ln1350_94_fu_1192_p2[32'd64];

assign tmp_309_fu_2602_p3 = xor_ln1350_93_fu_1186_p2[32'd65];

assign tmp_310_fu_2614_p3 = xor_ln1350_92_fu_1180_p2[32'd66];

assign tmp_311_fu_2626_p3 = xor_ln1350_91_fu_1174_p2[32'd67];

assign tmp_312_fu_2638_p3 = xor_ln1350_90_fu_1168_p2[32'd68];

assign tmp_313_fu_2650_p3 = xor_ln1350_89_fu_1162_p2[32'd69];

assign tmp_314_fu_2662_p3 = xor_ln1350_88_fu_1156_p2[32'd70];

assign tmp_315_fu_2674_p3 = xor_ln1350_87_fu_1150_p2[32'd71];

assign tmp_316_fu_2686_p3 = xor_ln1350_86_fu_1144_p2[32'd72];

assign tmp_317_fu_2698_p3 = xor_ln1350_85_fu_1138_p2[32'd73];

assign tmp_318_fu_2710_p3 = xor_ln1350_84_fu_1132_p2[32'd74];

assign tmp_319_fu_2722_p3 = xor_ln1350_83_fu_1126_p2[32'd75];

assign tmp_320_fu_2734_p3 = xor_ln1350_82_fu_1120_p2[32'd76];

assign tmp_321_fu_2746_p3 = xor_ln1350_81_fu_1114_p2[32'd77];

assign tmp_322_fu_2758_p3 = xor_ln1350_80_fu_1108_p2[32'd78];

assign tmp_323_fu_2770_p3 = xor_ln1350_79_fu_1102_p2[32'd79];

assign tmp_324_fu_2782_p3 = xor_ln1350_78_fu_1096_p2[32'd80];

assign tmp_325_fu_2794_p3 = xor_ln1350_77_fu_1090_p2[32'd81];

assign tmp_326_fu_2806_p3 = xor_ln1350_76_fu_1084_p2[32'd82];

assign tmp_327_fu_2818_p3 = xor_ln1350_75_fu_1078_p2[32'd83];

assign tmp_328_fu_2830_p3 = xor_ln1350_74_fu_1072_p2[32'd84];

assign tmp_329_fu_2842_p3 = xor_ln1350_73_fu_1066_p2[32'd85];

assign tmp_330_fu_2854_p3 = xor_ln1350_72_fu_1060_p2[32'd86];

assign tmp_331_fu_2866_p3 = xor_ln1350_71_fu_1054_p2[32'd87];

assign tmp_332_fu_2878_p3 = xor_ln1350_70_fu_1048_p2[32'd88];

assign tmp_333_fu_2890_p3 = xor_ln1350_69_fu_1042_p2[32'd89];

assign tmp_334_fu_2902_p3 = xor_ln1350_68_fu_1036_p2[32'd90];

assign tmp_335_fu_2914_p3 = xor_ln1350_67_fu_1030_p2[32'd91];

assign tmp_336_fu_2926_p3 = xor_ln1350_66_fu_1024_p2[32'd92];

assign tmp_337_fu_2938_p3 = xor_ln1350_65_fu_1018_p2[32'd93];

assign tmp_338_fu_2950_p3 = xor_ln1350_64_fu_1012_p2[32'd94];

assign tmp_339_fu_2962_p3 = ret_fu_1006_p2[32'd95];

assign tmp_fu_1834_p3 = xor_ln1158_59_fu_1818_p2[32'd1];

assign trunc_ln1350_128_fu_498_p1 = temp_flame96[31:0];

assign trunc_ln1350_129_fu_502_p1 = flame96[32:0];

assign trunc_ln1350_130_fu_506_p1 = temp_flame96[32:0];

assign trunc_ln1350_131_fu_510_p1 = flame96[33:0];

assign trunc_ln1350_132_fu_514_p1 = temp_flame96[33:0];

assign trunc_ln1350_133_fu_518_p1 = flame96[34:0];

assign trunc_ln1350_134_fu_522_p1 = temp_flame96[34:0];

assign trunc_ln1350_135_fu_526_p1 = flame96[35:0];

assign trunc_ln1350_136_fu_530_p1 = temp_flame96[35:0];

assign trunc_ln1350_137_fu_534_p1 = flame96[36:0];

assign trunc_ln1350_138_fu_538_p1 = temp_flame96[36:0];

assign trunc_ln1350_139_fu_542_p1 = flame96[37:0];

assign trunc_ln1350_140_fu_546_p1 = temp_flame96[37:0];

assign trunc_ln1350_141_fu_550_p1 = flame96[38:0];

assign trunc_ln1350_142_fu_554_p1 = temp_flame96[38:0];

assign trunc_ln1350_143_fu_558_p1 = flame96[39:0];

assign trunc_ln1350_144_fu_562_p1 = temp_flame96[39:0];

assign trunc_ln1350_145_fu_566_p1 = flame96[40:0];

assign trunc_ln1350_146_fu_570_p1 = temp_flame96[40:0];

assign trunc_ln1350_147_fu_574_p1 = flame96[41:0];

assign trunc_ln1350_148_fu_578_p1 = temp_flame96[41:0];

assign trunc_ln1350_149_fu_582_p1 = flame96[42:0];

assign trunc_ln1350_150_fu_586_p1 = temp_flame96[42:0];

assign trunc_ln1350_151_fu_590_p1 = flame96[43:0];

assign trunc_ln1350_152_fu_594_p1 = temp_flame96[43:0];

assign trunc_ln1350_153_fu_598_p1 = flame96[44:0];

assign trunc_ln1350_154_fu_602_p1 = temp_flame96[44:0];

assign trunc_ln1350_155_fu_606_p1 = flame96[45:0];

assign trunc_ln1350_156_fu_610_p1 = temp_flame96[45:0];

assign trunc_ln1350_157_fu_614_p1 = flame96[46:0];

assign trunc_ln1350_158_fu_618_p1 = temp_flame96[46:0];

assign trunc_ln1350_159_fu_622_p1 = flame96[47:0];

assign trunc_ln1350_160_fu_626_p1 = temp_flame96[47:0];

assign trunc_ln1350_161_fu_630_p1 = flame96[48:0];

assign trunc_ln1350_162_fu_634_p1 = temp_flame96[48:0];

assign trunc_ln1350_163_fu_638_p1 = flame96[49:0];

assign trunc_ln1350_164_fu_642_p1 = temp_flame96[49:0];

assign trunc_ln1350_165_fu_646_p1 = flame96[50:0];

assign trunc_ln1350_166_fu_650_p1 = temp_flame96[50:0];

assign trunc_ln1350_167_fu_654_p1 = flame96[51:0];

assign trunc_ln1350_168_fu_658_p1 = temp_flame96[51:0];

assign trunc_ln1350_169_fu_662_p1 = flame96[52:0];

assign trunc_ln1350_170_fu_666_p1 = temp_flame96[52:0];

assign trunc_ln1350_171_fu_670_p1 = flame96[53:0];

assign trunc_ln1350_172_fu_674_p1 = temp_flame96[53:0];

assign trunc_ln1350_173_fu_678_p1 = flame96[54:0];

assign trunc_ln1350_174_fu_682_p1 = temp_flame96[54:0];

assign trunc_ln1350_175_fu_686_p1 = flame96[55:0];

assign trunc_ln1350_176_fu_690_p1 = temp_flame96[55:0];

assign trunc_ln1350_177_fu_694_p1 = flame96[56:0];

assign trunc_ln1350_178_fu_698_p1 = temp_flame96[56:0];

assign trunc_ln1350_179_fu_702_p1 = flame96[57:0];

assign trunc_ln1350_180_fu_706_p1 = temp_flame96[57:0];

assign trunc_ln1350_181_fu_710_p1 = flame96[58:0];

assign trunc_ln1350_182_fu_714_p1 = temp_flame96[58:0];

assign trunc_ln1350_183_fu_718_p1 = flame96[59:0];

assign trunc_ln1350_184_fu_722_p1 = temp_flame96[59:0];

assign trunc_ln1350_185_fu_726_p1 = flame96[60:0];

assign trunc_ln1350_186_fu_730_p1 = temp_flame96[60:0];

assign trunc_ln1350_187_fu_734_p1 = flame96[61:0];

assign trunc_ln1350_188_fu_738_p1 = temp_flame96[61:0];

assign trunc_ln1350_189_fu_742_p1 = flame96[62:0];

assign trunc_ln1350_190_fu_746_p1 = temp_flame96[62:0];

assign trunc_ln1350_191_fu_750_p1 = flame96[63:0];

assign trunc_ln1350_192_fu_754_p1 = temp_flame96[63:0];

assign trunc_ln1350_193_fu_758_p1 = flame96[64:0];

assign trunc_ln1350_194_fu_762_p1 = temp_flame96[64:0];

assign trunc_ln1350_195_fu_766_p1 = flame96[65:0];

assign trunc_ln1350_196_fu_770_p1 = temp_flame96[65:0];

assign trunc_ln1350_197_fu_774_p1 = flame96[66:0];

assign trunc_ln1350_198_fu_778_p1 = temp_flame96[66:0];

assign trunc_ln1350_199_fu_782_p1 = flame96[67:0];

assign trunc_ln1350_200_fu_786_p1 = temp_flame96[67:0];

assign trunc_ln1350_201_fu_790_p1 = flame96[68:0];

assign trunc_ln1350_202_fu_794_p1 = temp_flame96[68:0];

assign trunc_ln1350_203_fu_798_p1 = flame96[69:0];

assign trunc_ln1350_204_fu_802_p1 = temp_flame96[69:0];

assign trunc_ln1350_205_fu_806_p1 = flame96[70:0];

assign trunc_ln1350_206_fu_810_p1 = temp_flame96[70:0];

assign trunc_ln1350_207_fu_814_p1 = flame96[71:0];

assign trunc_ln1350_208_fu_818_p1 = temp_flame96[71:0];

assign trunc_ln1350_209_fu_822_p1 = flame96[72:0];

assign trunc_ln1350_210_fu_826_p1 = temp_flame96[72:0];

assign trunc_ln1350_211_fu_830_p1 = flame96[73:0];

assign trunc_ln1350_212_fu_834_p1 = temp_flame96[73:0];

assign trunc_ln1350_213_fu_838_p1 = flame96[74:0];

assign trunc_ln1350_214_fu_842_p1 = temp_flame96[74:0];

assign trunc_ln1350_215_fu_846_p1 = flame96[75:0];

assign trunc_ln1350_216_fu_850_p1 = temp_flame96[75:0];

assign trunc_ln1350_217_fu_854_p1 = flame96[76:0];

assign trunc_ln1350_218_fu_858_p1 = temp_flame96[76:0];

assign trunc_ln1350_219_fu_862_p1 = flame96[77:0];

assign trunc_ln1350_220_fu_866_p1 = temp_flame96[77:0];

assign trunc_ln1350_221_fu_870_p1 = flame96[78:0];

assign trunc_ln1350_222_fu_874_p1 = temp_flame96[78:0];

assign trunc_ln1350_223_fu_878_p1 = flame96[79:0];

assign trunc_ln1350_224_fu_882_p1 = temp_flame96[79:0];

assign trunc_ln1350_225_fu_886_p1 = flame96[80:0];

assign trunc_ln1350_226_fu_890_p1 = temp_flame96[80:0];

assign trunc_ln1350_227_fu_894_p1 = flame96[81:0];

assign trunc_ln1350_228_fu_898_p1 = temp_flame96[81:0];

assign trunc_ln1350_229_fu_902_p1 = flame96[82:0];

assign trunc_ln1350_230_fu_906_p1 = temp_flame96[82:0];

assign trunc_ln1350_231_fu_910_p1 = flame96[83:0];

assign trunc_ln1350_232_fu_914_p1 = temp_flame96[83:0];

assign trunc_ln1350_233_fu_918_p1 = flame96[84:0];

assign trunc_ln1350_234_fu_922_p1 = temp_flame96[84:0];

assign trunc_ln1350_235_fu_926_p1 = flame96[85:0];

assign trunc_ln1350_236_fu_930_p1 = temp_flame96[85:0];

assign trunc_ln1350_237_fu_934_p1 = flame96[86:0];

assign trunc_ln1350_238_fu_938_p1 = temp_flame96[86:0];

assign trunc_ln1350_239_fu_942_p1 = flame96[87:0];

assign trunc_ln1350_240_fu_946_p1 = temp_flame96[87:0];

assign trunc_ln1350_241_fu_950_p1 = flame96[88:0];

assign trunc_ln1350_242_fu_954_p1 = temp_flame96[88:0];

assign trunc_ln1350_243_fu_958_p1 = flame96[89:0];

assign trunc_ln1350_244_fu_962_p1 = temp_flame96[89:0];

assign trunc_ln1350_245_fu_966_p1 = flame96[90:0];

assign trunc_ln1350_246_fu_970_p1 = temp_flame96[90:0];

assign trunc_ln1350_247_fu_974_p1 = flame96[91:0];

assign trunc_ln1350_248_fu_978_p1 = temp_flame96[91:0];

assign trunc_ln1350_249_fu_982_p1 = flame96[92:0];

assign trunc_ln1350_250_fu_986_p1 = temp_flame96[92:0];

assign trunc_ln1350_251_fu_990_p1 = flame96[93:0];

assign trunc_ln1350_252_fu_994_p1 = temp_flame96[93:0];

assign trunc_ln1350_253_fu_998_p1 = flame96[94:0];

assign trunc_ln1350_254_fu_1002_p1 = temp_flame96[94:0];

assign trunc_ln1350_fu_494_p1 = flame96[31:0];

assign trunc_ln819_100_fu_1546_p1 = temp_flame96[19:0];

assign trunc_ln819_101_fu_1550_p1 = flame96[20:0];

assign trunc_ln819_102_fu_1554_p1 = temp_flame96[20:0];

assign trunc_ln819_103_fu_1558_p1 = flame96[21:0];

assign trunc_ln819_104_fu_1562_p1 = temp_flame96[21:0];

assign trunc_ln819_105_fu_1566_p1 = flame96[22:0];

assign trunc_ln819_106_fu_1570_p1 = temp_flame96[22:0];

assign trunc_ln819_107_fu_1574_p1 = flame96[23:0];

assign trunc_ln819_108_fu_1578_p1 = temp_flame96[23:0];

assign trunc_ln819_109_fu_1582_p1 = flame96[24:0];

assign trunc_ln819_110_fu_1586_p1 = temp_flame96[24:0];

assign trunc_ln819_111_fu_1590_p1 = flame96[25:0];

assign trunc_ln819_112_fu_1594_p1 = temp_flame96[25:0];

assign trunc_ln819_113_fu_1598_p1 = flame96[26:0];

assign trunc_ln819_114_fu_1602_p1 = temp_flame96[26:0];

assign trunc_ln819_115_fu_1606_p1 = flame96[27:0];

assign trunc_ln819_116_fu_1610_p1 = temp_flame96[27:0];

assign trunc_ln819_117_fu_1614_p1 = flame96[28:0];

assign trunc_ln819_118_fu_1618_p1 = temp_flame96[28:0];

assign trunc_ln819_119_fu_1622_p1 = flame96[29:0];

assign trunc_ln819_120_fu_1626_p1 = temp_flame96[29:0];

assign trunc_ln819_121_fu_1630_p1 = flame96[30:0];

assign trunc_ln819_122_fu_1634_p1 = temp_flame96[30:0];

assign trunc_ln819_62_fu_1394_p1 = temp_flame96[0:0];

assign trunc_ln819_63_fu_1398_p1 = flame96[1:0];

assign trunc_ln819_64_fu_1402_p1 = temp_flame96[1:0];

assign trunc_ln819_65_fu_1406_p1 = flame96[2:0];

assign trunc_ln819_66_fu_1410_p1 = temp_flame96[2:0];

assign trunc_ln819_67_fu_1414_p1 = flame96[3:0];

assign trunc_ln819_68_fu_1418_p1 = temp_flame96[3:0];

assign trunc_ln819_69_fu_1422_p1 = flame96[4:0];

assign trunc_ln819_70_fu_1426_p1 = temp_flame96[4:0];

assign trunc_ln819_71_fu_1430_p1 = flame96[5:0];

assign trunc_ln819_72_fu_1434_p1 = temp_flame96[5:0];

assign trunc_ln819_73_fu_1438_p1 = flame96[6:0];

assign trunc_ln819_74_fu_1442_p1 = temp_flame96[6:0];

assign trunc_ln819_75_fu_1446_p1 = flame96[7:0];

assign trunc_ln819_76_fu_1450_p1 = temp_flame96[7:0];

assign trunc_ln819_77_fu_1454_p1 = flame96[8:0];

assign trunc_ln819_78_fu_1458_p1 = temp_flame96[8:0];

assign trunc_ln819_79_fu_1462_p1 = flame96[9:0];

assign trunc_ln819_80_fu_1466_p1 = temp_flame96[9:0];

assign trunc_ln819_81_fu_1470_p1 = flame96[10:0];

assign trunc_ln819_82_fu_1474_p1 = temp_flame96[10:0];

assign trunc_ln819_83_fu_1478_p1 = flame96[11:0];

assign trunc_ln819_84_fu_1482_p1 = temp_flame96[11:0];

assign trunc_ln819_85_fu_1486_p1 = flame96[12:0];

assign trunc_ln819_86_fu_1490_p1 = temp_flame96[12:0];

assign trunc_ln819_87_fu_1494_p1 = flame96[13:0];

assign trunc_ln819_88_fu_1498_p1 = temp_flame96[13:0];

assign trunc_ln819_89_fu_1502_p1 = flame96[14:0];

assign trunc_ln819_90_fu_1506_p1 = temp_flame96[14:0];

assign trunc_ln819_91_fu_1510_p1 = flame96[15:0];

assign trunc_ln819_92_fu_1514_p1 = temp_flame96[15:0];

assign trunc_ln819_93_fu_1518_p1 = flame96[16:0];

assign trunc_ln819_94_fu_1522_p1 = temp_flame96[16:0];

assign trunc_ln819_95_fu_1526_p1 = flame96[17:0];

assign trunc_ln819_96_fu_1530_p1 = temp_flame96[17:0];

assign trunc_ln819_97_fu_1534_p1 = flame96[18:0];

assign trunc_ln819_98_fu_1538_p1 = temp_flame96[18:0];

assign trunc_ln819_99_fu_1542_p1 = flame96[19:0];

assign trunc_ln819_fu_1390_p1 = flame96[0:0];

assign xor_ln1158_31_fu_1650_p2 = (trunc_ln819_120_fu_1626_p1 ^ trunc_ln819_119_fu_1622_p1);

assign xor_ln1158_32_fu_1656_p2 = (trunc_ln819_118_fu_1618_p1 ^ trunc_ln819_117_fu_1614_p1);

assign xor_ln1158_33_fu_1662_p2 = (trunc_ln819_116_fu_1610_p1 ^ trunc_ln819_115_fu_1606_p1);

assign xor_ln1158_34_fu_1668_p2 = (trunc_ln819_114_fu_1602_p1 ^ trunc_ln819_113_fu_1598_p1);

assign xor_ln1158_35_fu_1674_p2 = (trunc_ln819_112_fu_1594_p1 ^ trunc_ln819_111_fu_1590_p1);

assign xor_ln1158_36_fu_1680_p2 = (trunc_ln819_110_fu_1586_p1 ^ trunc_ln819_109_fu_1582_p1);

assign xor_ln1158_37_fu_1686_p2 = (trunc_ln819_108_fu_1578_p1 ^ trunc_ln819_107_fu_1574_p1);

assign xor_ln1158_38_fu_1692_p2 = (trunc_ln819_106_fu_1570_p1 ^ trunc_ln819_105_fu_1566_p1);

assign xor_ln1158_39_fu_1698_p2 = (trunc_ln819_104_fu_1562_p1 ^ trunc_ln819_103_fu_1558_p1);

assign xor_ln1158_40_fu_1704_p2 = (trunc_ln819_102_fu_1554_p1 ^ trunc_ln819_101_fu_1550_p1);

assign xor_ln1158_41_fu_1710_p2 = (trunc_ln819_99_fu_1542_p1 ^ trunc_ln819_100_fu_1546_p1);

assign xor_ln1158_42_fu_1716_p2 = (trunc_ln819_98_fu_1538_p1 ^ trunc_ln819_97_fu_1534_p1);

assign xor_ln1158_43_fu_1722_p2 = (trunc_ln819_96_fu_1530_p1 ^ trunc_ln819_95_fu_1526_p1);

assign xor_ln1158_44_fu_1728_p2 = (trunc_ln819_94_fu_1522_p1 ^ trunc_ln819_93_fu_1518_p1);

assign xor_ln1158_45_fu_1734_p2 = (trunc_ln819_92_fu_1514_p1 ^ trunc_ln819_91_fu_1510_p1);

assign xor_ln1158_46_fu_1740_p2 = (trunc_ln819_90_fu_1506_p1 ^ trunc_ln819_89_fu_1502_p1);

assign xor_ln1158_47_fu_1746_p2 = (trunc_ln819_88_fu_1498_p1 ^ trunc_ln819_87_fu_1494_p1);

assign xor_ln1158_48_fu_1752_p2 = (trunc_ln819_86_fu_1490_p1 ^ trunc_ln819_85_fu_1486_p1);

assign xor_ln1158_49_fu_1758_p2 = (trunc_ln819_84_fu_1482_p1 ^ trunc_ln819_83_fu_1478_p1);

assign xor_ln1158_50_fu_1764_p2 = (trunc_ln819_82_fu_1474_p1 ^ trunc_ln819_81_fu_1470_p1);

assign xor_ln1158_51_fu_1770_p2 = (trunc_ln819_80_fu_1466_p1 ^ trunc_ln819_79_fu_1462_p1);

assign xor_ln1158_52_fu_1776_p2 = (trunc_ln819_78_fu_1458_p1 ^ trunc_ln819_77_fu_1454_p1);

assign xor_ln1158_53_fu_1782_p2 = (trunc_ln819_76_fu_1450_p1 ^ trunc_ln819_75_fu_1446_p1);

assign xor_ln1158_54_fu_1788_p2 = (trunc_ln819_74_fu_1442_p1 ^ trunc_ln819_73_fu_1438_p1);

assign xor_ln1158_55_fu_1794_p2 = (trunc_ln819_72_fu_1434_p1 ^ trunc_ln819_71_fu_1430_p1);

assign xor_ln1158_56_fu_1800_p2 = (trunc_ln819_70_fu_1426_p1 ^ trunc_ln819_69_fu_1422_p1);

assign xor_ln1158_57_fu_1806_p2 = (trunc_ln819_68_fu_1418_p1 ^ trunc_ln819_67_fu_1414_p1);

assign xor_ln1158_58_fu_1812_p2 = (trunc_ln819_66_fu_1410_p1 ^ trunc_ln819_65_fu_1406_p1);

assign xor_ln1158_59_fu_1818_p2 = (trunc_ln819_64_fu_1402_p1 ^ trunc_ln819_63_fu_1398_p1);

assign xor_ln1158_60_fu_1824_p2 = (trunc_ln819_fu_1390_p1 ^ trunc_ln819_62_fu_1394_p1);

assign xor_ln1158_fu_1644_p2 = (trunc_ln819_122_fu_1634_p1 ^ trunc_ln819_121_fu_1630_p1);

assign xor_ln1350_100_fu_1228_p2 = (trunc_ln1350_182_fu_714_p1 ^ trunc_ln1350_181_fu_710_p1);

assign xor_ln1350_101_fu_1234_p2 = (trunc_ln1350_180_fu_706_p1 ^ trunc_ln1350_179_fu_702_p1);

assign xor_ln1350_102_fu_1240_p2 = (trunc_ln1350_178_fu_698_p1 ^ trunc_ln1350_177_fu_694_p1);

assign xor_ln1350_103_fu_1246_p2 = (trunc_ln1350_176_fu_690_p1 ^ trunc_ln1350_175_fu_686_p1);

assign xor_ln1350_104_fu_1252_p2 = (trunc_ln1350_174_fu_682_p1 ^ trunc_ln1350_173_fu_678_p1);

assign xor_ln1350_105_fu_1258_p2 = (trunc_ln1350_172_fu_674_p1 ^ trunc_ln1350_171_fu_670_p1);

assign xor_ln1350_106_fu_1264_p2 = (trunc_ln1350_170_fu_666_p1 ^ trunc_ln1350_169_fu_662_p1);

assign xor_ln1350_107_fu_1270_p2 = (trunc_ln1350_168_fu_658_p1 ^ trunc_ln1350_167_fu_654_p1);

assign xor_ln1350_108_fu_1276_p2 = (trunc_ln1350_166_fu_650_p1 ^ trunc_ln1350_165_fu_646_p1);

assign xor_ln1350_109_fu_1282_p2 = (trunc_ln1350_164_fu_642_p1 ^ trunc_ln1350_163_fu_638_p1);

assign xor_ln1350_110_fu_1288_p2 = (trunc_ln1350_162_fu_634_p1 ^ trunc_ln1350_161_fu_630_p1);

assign xor_ln1350_111_fu_1294_p2 = (trunc_ln1350_160_fu_626_p1 ^ trunc_ln1350_159_fu_622_p1);

assign xor_ln1350_112_fu_1300_p2 = (trunc_ln1350_158_fu_618_p1 ^ trunc_ln1350_157_fu_614_p1);

assign xor_ln1350_113_fu_1306_p2 = (trunc_ln1350_156_fu_610_p1 ^ trunc_ln1350_155_fu_606_p1);

assign xor_ln1350_114_fu_1312_p2 = (trunc_ln1350_154_fu_602_p1 ^ trunc_ln1350_153_fu_598_p1);

assign xor_ln1350_115_fu_1318_p2 = (trunc_ln1350_152_fu_594_p1 ^ trunc_ln1350_151_fu_590_p1);

assign xor_ln1350_116_fu_1324_p2 = (trunc_ln1350_150_fu_586_p1 ^ trunc_ln1350_149_fu_582_p1);

assign xor_ln1350_117_fu_1330_p2 = (trunc_ln1350_148_fu_578_p1 ^ trunc_ln1350_147_fu_574_p1);

assign xor_ln1350_118_fu_1336_p2 = (trunc_ln1350_146_fu_570_p1 ^ trunc_ln1350_145_fu_566_p1);

assign xor_ln1350_119_fu_1342_p2 = (trunc_ln1350_144_fu_562_p1 ^ trunc_ln1350_143_fu_558_p1);

assign xor_ln1350_120_fu_1348_p2 = (trunc_ln1350_142_fu_554_p1 ^ trunc_ln1350_141_fu_550_p1);

assign xor_ln1350_121_fu_1354_p2 = (trunc_ln1350_140_fu_546_p1 ^ trunc_ln1350_139_fu_542_p1);

assign xor_ln1350_122_fu_1360_p2 = (trunc_ln1350_138_fu_538_p1 ^ trunc_ln1350_137_fu_534_p1);

assign xor_ln1350_123_fu_1366_p2 = (trunc_ln1350_136_fu_530_p1 ^ trunc_ln1350_135_fu_526_p1);

assign xor_ln1350_124_fu_1372_p2 = (trunc_ln1350_134_fu_522_p1 ^ trunc_ln1350_133_fu_518_p1);

assign xor_ln1350_125_fu_1378_p2 = (trunc_ln1350_132_fu_514_p1 ^ trunc_ln1350_131_fu_510_p1);

assign xor_ln1350_126_fu_1384_p2 = (trunc_ln1350_130_fu_506_p1 ^ trunc_ln1350_129_fu_502_p1);

assign xor_ln1350_64_fu_1012_p2 = (trunc_ln1350_254_fu_1002_p1 ^ trunc_ln1350_253_fu_998_p1);

assign xor_ln1350_65_fu_1018_p2 = (trunc_ln1350_252_fu_994_p1 ^ trunc_ln1350_251_fu_990_p1);

assign xor_ln1350_66_fu_1024_p2 = (trunc_ln1350_250_fu_986_p1 ^ trunc_ln1350_249_fu_982_p1);

assign xor_ln1350_67_fu_1030_p2 = (trunc_ln1350_248_fu_978_p1 ^ trunc_ln1350_247_fu_974_p1);

assign xor_ln1350_68_fu_1036_p2 = (trunc_ln1350_246_fu_970_p1 ^ trunc_ln1350_245_fu_966_p1);

assign xor_ln1350_69_fu_1042_p2 = (trunc_ln1350_244_fu_962_p1 ^ trunc_ln1350_243_fu_958_p1);

assign xor_ln1350_70_fu_1048_p2 = (trunc_ln1350_242_fu_954_p1 ^ trunc_ln1350_241_fu_950_p1);

assign xor_ln1350_71_fu_1054_p2 = (trunc_ln1350_240_fu_946_p1 ^ trunc_ln1350_239_fu_942_p1);

assign xor_ln1350_72_fu_1060_p2 = (trunc_ln1350_238_fu_938_p1 ^ trunc_ln1350_237_fu_934_p1);

assign xor_ln1350_73_fu_1066_p2 = (trunc_ln1350_236_fu_930_p1 ^ trunc_ln1350_235_fu_926_p1);

assign xor_ln1350_74_fu_1072_p2 = (trunc_ln1350_234_fu_922_p1 ^ trunc_ln1350_233_fu_918_p1);

assign xor_ln1350_75_fu_1078_p2 = (trunc_ln1350_232_fu_914_p1 ^ trunc_ln1350_231_fu_910_p1);

assign xor_ln1350_76_fu_1084_p2 = (trunc_ln1350_230_fu_906_p1 ^ trunc_ln1350_229_fu_902_p1);

assign xor_ln1350_77_fu_1090_p2 = (trunc_ln1350_228_fu_898_p1 ^ trunc_ln1350_227_fu_894_p1);

assign xor_ln1350_78_fu_1096_p2 = (trunc_ln1350_226_fu_890_p1 ^ trunc_ln1350_225_fu_886_p1);

assign xor_ln1350_79_fu_1102_p2 = (trunc_ln1350_224_fu_882_p1 ^ trunc_ln1350_223_fu_878_p1);

assign xor_ln1350_80_fu_1108_p2 = (trunc_ln1350_222_fu_874_p1 ^ trunc_ln1350_221_fu_870_p1);

assign xor_ln1350_81_fu_1114_p2 = (trunc_ln1350_220_fu_866_p1 ^ trunc_ln1350_219_fu_862_p1);

assign xor_ln1350_82_fu_1120_p2 = (trunc_ln1350_218_fu_858_p1 ^ trunc_ln1350_217_fu_854_p1);

assign xor_ln1350_83_fu_1126_p2 = (trunc_ln1350_216_fu_850_p1 ^ trunc_ln1350_215_fu_846_p1);

assign xor_ln1350_84_fu_1132_p2 = (trunc_ln1350_214_fu_842_p1 ^ trunc_ln1350_213_fu_838_p1);

assign xor_ln1350_85_fu_1138_p2 = (trunc_ln1350_212_fu_834_p1 ^ trunc_ln1350_211_fu_830_p1);

assign xor_ln1350_86_fu_1144_p2 = (trunc_ln1350_210_fu_826_p1 ^ trunc_ln1350_209_fu_822_p1);

assign xor_ln1350_87_fu_1150_p2 = (trunc_ln1350_208_fu_818_p1 ^ trunc_ln1350_207_fu_814_p1);

assign xor_ln1350_88_fu_1156_p2 = (trunc_ln1350_206_fu_810_p1 ^ trunc_ln1350_205_fu_806_p1);

assign xor_ln1350_89_fu_1162_p2 = (trunc_ln1350_204_fu_802_p1 ^ trunc_ln1350_203_fu_798_p1);

assign xor_ln1350_90_fu_1168_p2 = (trunc_ln1350_202_fu_794_p1 ^ trunc_ln1350_201_fu_790_p1);

assign xor_ln1350_91_fu_1174_p2 = (trunc_ln1350_200_fu_786_p1 ^ trunc_ln1350_199_fu_782_p1);

assign xor_ln1350_92_fu_1180_p2 = (trunc_ln1350_198_fu_778_p1 ^ trunc_ln1350_197_fu_774_p1);

assign xor_ln1350_93_fu_1186_p2 = (trunc_ln1350_196_fu_770_p1 ^ trunc_ln1350_195_fu_766_p1);

assign xor_ln1350_94_fu_1192_p2 = (trunc_ln1350_194_fu_762_p1 ^ trunc_ln1350_193_fu_758_p1);

assign xor_ln1350_95_fu_1198_p2 = (trunc_ln1350_192_fu_754_p1 ^ trunc_ln1350_191_fu_750_p1);

assign xor_ln1350_96_fu_1204_p2 = (trunc_ln1350_190_fu_746_p1 ^ trunc_ln1350_189_fu_742_p1);

assign xor_ln1350_97_fu_1210_p2 = (trunc_ln1350_188_fu_738_p1 ^ trunc_ln1350_187_fu_734_p1);

assign xor_ln1350_98_fu_1216_p2 = (trunc_ln1350_186_fu_730_p1 ^ trunc_ln1350_185_fu_726_p1);

assign xor_ln1350_99_fu_1222_p2 = (trunc_ln1350_184_fu_722_p1 ^ trunc_ln1350_183_fu_718_p1);

assign xor_ln819_fu_1638_p2 = (trunc_ln1350_fu_494_p1 ^ trunc_ln1350_128_fu_498_p1);

assign zext_ln1148_3_fu_2202_p1 = tmp_275_fu_2194_p3;

assign zext_ln1148_4_fu_2586_p1 = tmp_307_fu_2578_p3;

assign zext_ln1148_5_fu_2970_p1 = tmp_339_fu_2962_p3;

assign zext_ln1148_fu_1842_p1 = tmp_fu_1834_p3;

assign zext_ln1158_134_fu_1854_p1 = tmp_246_fu_1846_p3;

assign zext_ln1158_135_fu_1866_p1 = tmp_247_fu_1858_p3;

assign zext_ln1158_136_fu_1878_p1 = tmp_248_fu_1870_p3;

assign zext_ln1158_137_fu_1890_p1 = tmp_249_fu_1882_p3;

assign zext_ln1158_138_fu_1902_p1 = tmp_250_fu_1894_p3;

assign zext_ln1158_139_fu_1914_p1 = tmp_251_fu_1906_p3;

assign zext_ln1158_140_fu_1926_p1 = tmp_252_fu_1918_p3;

assign zext_ln1158_141_fu_1938_p1 = tmp_253_fu_1930_p3;

assign zext_ln1158_142_fu_1950_p1 = tmp_254_fu_1942_p3;

assign zext_ln1158_143_fu_1962_p1 = tmp_255_fu_1954_p3;

assign zext_ln1158_144_fu_1974_p1 = tmp_256_fu_1966_p3;

assign zext_ln1158_145_fu_1986_p1 = tmp_257_fu_1978_p3;

assign zext_ln1158_146_fu_1998_p1 = tmp_258_fu_1990_p3;

assign zext_ln1158_147_fu_2010_p1 = tmp_259_fu_2002_p3;

assign zext_ln1158_148_fu_2022_p1 = tmp_260_fu_2014_p3;

assign zext_ln1158_149_fu_2034_p1 = tmp_261_fu_2026_p3;

assign zext_ln1158_150_fu_2046_p1 = tmp_262_fu_2038_p3;

assign zext_ln1158_151_fu_2058_p1 = tmp_263_fu_2050_p3;

assign zext_ln1158_152_fu_2070_p1 = tmp_264_fu_2062_p3;

assign zext_ln1158_153_fu_2082_p1 = tmp_265_fu_2074_p3;

assign zext_ln1158_154_fu_2094_p1 = tmp_266_fu_2086_p3;

assign zext_ln1158_155_fu_2106_p1 = tmp_267_fu_2098_p3;

assign zext_ln1158_156_fu_2118_p1 = tmp_268_fu_2110_p3;

assign zext_ln1158_157_fu_2130_p1 = tmp_269_fu_2122_p3;

assign zext_ln1158_158_fu_2142_p1 = tmp_270_fu_2134_p3;

assign zext_ln1158_159_fu_2154_p1 = tmp_271_fu_2146_p3;

assign zext_ln1158_160_fu_2166_p1 = tmp_272_fu_2158_p3;

assign zext_ln1158_161_fu_2178_p1 = tmp_273_fu_2170_p3;

assign zext_ln1158_162_fu_2190_p1 = tmp_274_fu_2182_p3;

assign zext_ln1158_163_fu_2214_p1 = tmp_276_fu_2206_p3;

assign zext_ln1158_164_fu_2226_p1 = tmp_277_fu_2218_p3;

assign zext_ln1158_165_fu_2238_p1 = tmp_278_fu_2230_p3;

assign zext_ln1158_166_fu_2250_p1 = tmp_279_fu_2242_p3;

assign zext_ln1158_167_fu_2262_p1 = tmp_280_fu_2254_p3;

assign zext_ln1158_168_fu_2274_p1 = tmp_281_fu_2266_p3;

assign zext_ln1158_169_fu_2286_p1 = tmp_282_fu_2278_p3;

assign zext_ln1158_170_fu_2298_p1 = tmp_283_fu_2290_p3;

assign zext_ln1158_171_fu_2310_p1 = tmp_284_fu_2302_p3;

assign zext_ln1158_172_fu_2322_p1 = tmp_285_fu_2314_p3;

assign zext_ln1158_173_fu_2334_p1 = tmp_286_fu_2326_p3;

assign zext_ln1158_174_fu_2346_p1 = tmp_287_fu_2338_p3;

assign zext_ln1158_175_fu_2358_p1 = tmp_288_fu_2350_p3;

assign zext_ln1158_176_fu_2370_p1 = tmp_289_fu_2362_p3;

assign zext_ln1158_177_fu_2382_p1 = tmp_290_fu_2374_p3;

assign zext_ln1158_178_fu_2394_p1 = tmp_291_fu_2386_p3;

assign zext_ln1158_179_fu_2406_p1 = tmp_292_fu_2398_p3;

assign zext_ln1158_180_fu_2418_p1 = tmp_293_fu_2410_p3;

assign zext_ln1158_181_fu_2430_p1 = tmp_294_fu_2422_p3;

assign zext_ln1158_182_fu_2442_p1 = tmp_295_fu_2434_p3;

assign zext_ln1158_183_fu_2454_p1 = tmp_296_fu_2446_p3;

assign zext_ln1158_184_fu_2466_p1 = tmp_297_fu_2458_p3;

assign zext_ln1158_185_fu_2478_p1 = tmp_298_fu_2470_p3;

assign zext_ln1158_186_fu_2490_p1 = tmp_299_fu_2482_p3;

assign zext_ln1158_187_fu_2502_p1 = tmp_300_fu_2494_p3;

assign zext_ln1158_188_fu_2514_p1 = tmp_301_fu_2506_p3;

assign zext_ln1158_189_fu_2526_p1 = tmp_302_fu_2518_p3;

assign zext_ln1158_190_fu_2538_p1 = tmp_303_fu_2530_p3;

assign zext_ln1158_191_fu_2550_p1 = tmp_304_fu_2542_p3;

assign zext_ln1158_192_fu_2562_p1 = tmp_305_fu_2554_p3;

assign zext_ln1158_193_fu_2574_p1 = tmp_306_fu_2566_p3;

assign zext_ln1158_194_fu_2598_p1 = tmp_308_fu_2590_p3;

assign zext_ln1158_195_fu_2610_p1 = tmp_309_fu_2602_p3;

assign zext_ln1158_196_fu_2622_p1 = tmp_310_fu_2614_p3;

assign zext_ln1158_197_fu_2634_p1 = tmp_311_fu_2626_p3;

assign zext_ln1158_198_fu_2646_p1 = tmp_312_fu_2638_p3;

assign zext_ln1158_199_fu_2658_p1 = tmp_313_fu_2650_p3;

assign zext_ln1158_200_fu_2670_p1 = tmp_314_fu_2662_p3;

assign zext_ln1158_201_fu_2682_p1 = tmp_315_fu_2674_p3;

assign zext_ln1158_202_fu_2694_p1 = tmp_316_fu_2686_p3;

assign zext_ln1158_203_fu_2706_p1 = tmp_317_fu_2698_p3;

assign zext_ln1158_204_fu_2718_p1 = tmp_318_fu_2710_p3;

assign zext_ln1158_205_fu_2730_p1 = tmp_319_fu_2722_p3;

assign zext_ln1158_206_fu_2742_p1 = tmp_320_fu_2734_p3;

assign zext_ln1158_207_fu_2754_p1 = tmp_321_fu_2746_p3;

assign zext_ln1158_208_fu_2766_p1 = tmp_322_fu_2758_p3;

assign zext_ln1158_209_fu_2778_p1 = tmp_323_fu_2770_p3;

assign zext_ln1158_210_fu_2790_p1 = tmp_324_fu_2782_p3;

assign zext_ln1158_211_fu_2802_p1 = tmp_325_fu_2794_p3;

assign zext_ln1158_212_fu_2814_p1 = tmp_326_fu_2806_p3;

assign zext_ln1158_213_fu_2826_p1 = tmp_327_fu_2818_p3;

assign zext_ln1158_214_fu_2838_p1 = tmp_328_fu_2830_p3;

assign zext_ln1158_215_fu_2850_p1 = tmp_329_fu_2842_p3;

assign zext_ln1158_216_fu_2862_p1 = tmp_330_fu_2854_p3;

assign zext_ln1158_217_fu_2874_p1 = tmp_331_fu_2866_p3;

assign zext_ln1158_218_fu_2886_p1 = tmp_332_fu_2878_p3;

assign zext_ln1158_219_fu_2898_p1 = tmp_333_fu_2890_p3;

assign zext_ln1158_220_fu_2910_p1 = tmp_334_fu_2902_p3;

assign zext_ln1158_221_fu_2922_p1 = tmp_335_fu_2914_p3;

assign zext_ln1158_222_fu_2934_p1 = tmp_336_fu_2926_p3;

assign zext_ln1158_223_fu_2946_p1 = tmp_337_fu_2938_p3;

assign zext_ln1158_224_fu_2958_p1 = tmp_338_fu_2950_p3;

assign zext_ln1158_225_fu_3008_p1 = add_ln1158_65_fu_3002_p2;

assign zext_ln1158_226_fu_3034_p1 = add_ln1158_67_fu_3028_p2;

assign zext_ln1158_227_fu_3050_p1 = add_ln1158_69_fu_3044_p2;

assign zext_ln1158_228_fu_3066_p1 = add_ln1158_71_fu_3060_p2;

assign zext_ln1158_229_fu_3076_p1 = add_ln1158_72_fu_3070_p2;

assign zext_ln1158_230_fu_3102_p1 = add_ln1158_74_fu_3096_p2;

assign zext_ln1158_231_fu_3118_p1 = add_ln1158_76_fu_3112_p2;

assign zext_ln1158_232_fu_3128_p1 = add_ln1158_77_fu_3122_p2;

assign zext_ln1158_233_fu_3138_p1 = add_ln1158_79_fu_3132_p2;

assign zext_ln1158_234_fu_3154_p1 = add_ln1158_81_fu_3148_p2;

assign zext_ln1158_235_fu_3164_p1 = add_ln1158_82_fu_3158_p2;

assign zext_ln1158_236_fu_3174_p1 = add_ln1158_83_fu_3168_p2;

assign zext_ln1158_237_fu_3184_p1 = add_ln1158_84_fu_3178_p2;

assign zext_ln1158_238_fu_3200_p1 = add_ln1158_86_fu_3194_p2;

assign zext_ln1158_239_fu_3210_p1 = add_ln1158_87_fu_3204_p2;

assign zext_ln1158_240_fu_3220_p1 = add_ln1158_88_fu_3214_p2;

assign zext_ln1158_241_fu_3246_p1 = add_ln1158_90_fu_3240_p2;

assign zext_ln1158_242_fu_3262_p1 = add_ln1158_92_fu_3256_p2;

assign zext_ln1158_243_fu_3272_p1 = add_ln1158_93_fu_3266_p2;

assign zext_ln1158_244_fu_3282_p1 = add_ln1158_94_fu_3276_p2;

assign zext_ln1158_245_fu_3298_p1 = add_ln1158_96_fu_3292_p2;

assign zext_ln1158_246_fu_3308_p1 = add_ln1158_97_fu_3302_p2;

assign zext_ln1158_247_fu_3318_p1 = add_ln1158_98_fu_3312_p2;

assign zext_ln1158_248_fu_3328_p1 = add_ln1158_99_fu_3322_p2;

assign zext_ln1158_249_fu_3338_p1 = add_ln1158_100_fu_3332_p2;

assign zext_ln1158_250_fu_3348_p1 = add_ln1158_101_fu_3342_p2;

assign zext_ln1158_251_fu_3358_p1 = add_ln1158_102_fu_3352_p2;

assign zext_ln1158_252_fu_3374_p1 = add_ln1158_104_fu_3368_p2;

assign zext_ln1158_253_fu_3384_p1 = add_ln1158_105_fu_3378_p2;

assign zext_ln1158_254_fu_3394_p1 = add_ln1158_106_fu_3388_p2;

assign zext_ln1158_255_fu_3404_p1 = add_ln1158_107_fu_3398_p2;

assign zext_ln1158_256_fu_3414_p1 = add_ln1158_108_fu_3408_p2;

assign zext_ln1158_257_fu_3424_p1 = add_ln1158_109_fu_3418_p2;

assign zext_ln1158_258_fu_3434_p1 = add_ln1158_110_fu_3428_p2;

assign zext_ln1158_259_fu_3444_p1 = add_ln1158_111_fu_3438_p2;

assign zext_ln1158_260_fu_3454_p1 = add_ln1158_112_fu_3448_p2;

assign zext_ln1158_261_fu_3464_p1 = add_ln1158_113_fu_3458_p2;

assign zext_ln1158_262_fu_3474_p1 = add_ln1158_114_fu_3468_p2;

assign zext_ln1158_263_fu_3490_p1 = add_ln1158_116_fu_3484_p2;

assign zext_ln1158_264_fu_3500_p1 = add_ln1158_117_fu_3494_p2;

assign zext_ln1158_265_fu_3510_p1 = add_ln1158_118_fu_3504_p2;

assign zext_ln1158_266_fu_3520_p1 = add_ln1158_119_fu_3514_p2;

assign zext_ln1158_fu_1830_p1 = xor_ln1158_60_fu_1824_p2;

assign zext_ln1159_31_fu_3546_p1 = add_ln1159_33_fu_3540_p2;

assign zext_ln1159_32_fu_3562_p1 = add_ln1159_35_fu_3556_p2;

assign zext_ln1159_33_fu_3572_p1 = add_ln1159_36_fu_3566_p2;

assign zext_ln1159_34_fu_3582_p1 = add_ln1159_37_fu_3576_p2;

assign zext_ln1159_35_fu_3598_p1 = add_ln1159_39_fu_3592_p2;

assign zext_ln1159_36_fu_3608_p1 = add_ln1159_40_fu_3602_p2;

assign zext_ln1159_37_fu_3618_p1 = add_ln1159_41_fu_3612_p2;

assign zext_ln1159_38_fu_3628_p1 = add_ln1159_42_fu_3622_p2;

assign zext_ln1159_39_fu_3644_p1 = add_ln1159_44_fu_3638_p2;

assign zext_ln1159_40_fu_3654_p1 = add_ln1159_45_fu_3648_p2;

assign zext_ln1159_41_fu_3664_p1 = add_ln1159_46_fu_3658_p2;

assign zext_ln1159_42_fu_3680_p1 = add_ln1159_48_fu_3674_p2;

assign zext_ln1159_43_fu_3690_p1 = add_ln1159_49_fu_3684_p2;

assign zext_ln1159_44_fu_3700_p1 = add_ln1159_50_fu_3694_p2;

assign zext_ln1159_45_fu_3710_p1 = add_ln1159_51_fu_3704_p2;

assign zext_ln1159_46_fu_3720_p1 = add_ln1159_52_fu_3714_p2;

assign zext_ln1159_47_fu_3730_p1 = add_ln1159_53_fu_3724_p2;

assign zext_ln1159_48_fu_3740_p1 = add_ln1159_54_fu_3734_p2;

assign zext_ln1159_49_fu_3750_p1 = add_ln1159_55_fu_3744_p2;

assign zext_ln1159_50_fu_3760_p1 = add_ln1159_56_fu_3754_p2;

assign zext_ln1159_51_fu_3770_p1 = add_ln1159_57_fu_3764_p2;

assign zext_ln1159_52_fu_3780_p1 = add_ln1159_58_fu_3774_p2;

assign zext_ln1159_53_fu_3796_p1 = add_ln1159_60_fu_3790_p2;

assign zext_ln1159_54_fu_3806_p1 = add_ln1159_61_fu_3800_p2;

assign zext_ln1159_55_fu_3816_p1 = add_ln1159_62_fu_3810_p2;

assign zext_ln1159_56_fu_3826_p1 = add_ln1159_63_fu_3820_p2;

assign zext_ln1159_5_fu_3018_p1 = add_ln1158_50_fu_3012_p2;

assign zext_ln1159_6_fu_3086_p1 = add_ln1158_54_fu_3080_p2;

assign zext_ln1159_7_fu_3230_p1 = add_ln1158_62_fu_3224_p2;

assign zext_ln1159_8_fu_3530_p1 = add_ln1158_78_fu_3524_p2;

assign zext_ln1159_fu_2986_p1 = add_ln1158_48_fu_2980_p2;

endmodule //table_serch_hd_cal962339
