// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module table_serch_hid_cal (
        ap_ready,
        flame96,
        hash_index,
        ap_return
);


output   ap_ready;
input  [95:0] flame96;
input  [31:0] hash_index;
output  [12:0] ap_return;

wire   [0:0] tmp_104_fu_144_p3;
wire   [0:0] tmp_105_fu_152_p3;
wire   [0:0] tmp_106_fu_160_p3;
wire   [0:0] tmp_107_fu_168_p3;
reg   [1:0] tmp_fu_232_p4;
wire   [0:0] tmp_109_fu_184_p3;
wire   [0:0] tmp_110_fu_192_p3;
wire   [0:0] tmp_111_fu_200_p3;
wire   [0:0] tmp_112_fu_208_p3;
wire   [0:0] tmp_113_fu_216_p3;
wire   [0:0] tmp_114_fu_224_p3;
wire   [0:0] tmp_115_fu_270_p3;
wire   [0:0] tmp_116_fu_278_p3;
wire   [0:0] tmp_117_fu_286_p3;
wire   [0:0] tmp_108_fu_176_p3;
reg   [1:0] tmp_s_fu_342_p4;
wire   [0:0] tmp_118_fu_294_p3;
wire   [0:0] tmp_119_fu_302_p3;
wire   [0:0] tmp_120_fu_310_p3;
wire   [0:0] tmp_121_fu_318_p3;
wire   [0:0] tmp_122_fu_326_p3;
wire   [0:0] tmp_123_fu_334_p3;
wire   [0:0] tmp_124_fu_380_p3;
wire   [0:0] tmp_125_fu_388_p3;
wire   [0:0] tmp_126_fu_396_p3;
wire   [0:0] tmp_127_fu_404_p3;
wire   [0:0] tmp_128_fu_412_p3;
wire   [0:0] tmp_129_fu_420_p3;
wire   [0:0] tmp_130_fu_428_p3;
wire   [0:0] tmp_131_fu_436_p3;
wire   [0:0] tmp_132_fu_474_p3;
wire   [0:0] tmp_133_fu_482_p3;
wire   [0:0] tmp_134_fu_490_p3;
wire   [0:0] tmp_135_fu_498_p3;
wire   [0:0] trunc_ln849_fu_506_p1;
wire   [0:0] tmp_136_fu_510_p3;
wire   [0:0] tmp_137_fu_518_p3;
wire   [0:0] tmp_138_fu_556_p3;
wire   [0:0] tmp_139_fu_564_p3;
wire   [0:0] tmp_140_fu_572_p3;
wire   [0:0] tmp_141_fu_580_p3;
wire   [0:0] tmp_142_fu_588_p3;
wire   [0:0] tmp_143_fu_596_p3;
wire   [0:0] tmp_144_fu_604_p3;
wire   [0:0] tmp_145_fu_612_p3;
wire   [0:0] tmp_146_fu_650_p3;
wire   [0:0] tmp_147_fu_658_p3;
wire   [0:0] tmp_148_fu_666_p3;
wire   [0:0] tmp_149_fu_674_p3;
wire   [0:0] tmp_150_fu_682_p3;
wire   [0:0] tmp_151_fu_690_p3;
reg   [1:0] tmp_98_fu_698_p4;
wire   [0:0] icmp_ln1016_5_fu_766_p2;
wire   [12:0] p_Result_s_fu_242_p13;
wire   [12:0] p_Result_1_fu_352_p13;
wire   [0:0] icmp_ln1016_4_fu_760_p2;
wire   [0:0] icmp_ln1016_3_fu_754_p2;
wire   [12:0] p_Result_2_fu_444_p14;
wire   [12:0] p_Result_3_fu_526_p14;
wire   [0:0] icmp_ln1016_2_fu_748_p2;
wire   [0:0] icmp_ln1016_1_fu_742_p2;
wire   [12:0] p_Result_4_fu_620_p14;
wire   [12:0] p_Result_5_fu_708_p13;
wire   [0:0] icmp_ln1016_fu_736_p2;
wire   [0:0] or_ln1016_fu_780_p2;
wire   [12:0] select_ln1016_fu_772_p3;
wire   [12:0] select_ln1016_1_fu_786_p3;
wire   [0:0] or_ln1016_1_fu_794_p2;
wire   [0:0] or_ln1016_2_fu_808_p2;
wire   [12:0] select_ln1016_2_fu_800_p3;
wire   [0:0] or_ln1016_3_fu_822_p2;
wire   [12:0] select_ln1016_3_fu_814_p3;
wire   [12:0] select_ln1016_4_fu_828_p3;
wire    ap_ce_reg;

assign ap_ready = 1'b1;

assign ap_return = ((or_ln1016_3_fu_822_p2[0:0] == 1'b1) ? select_ln1016_3_fu_814_p3 : select_ln1016_4_fu_828_p3);

assign icmp_ln1016_1_fu_742_p2 = ((hash_index == 32'd4) ? 1'b1 : 1'b0);

assign icmp_ln1016_2_fu_748_p2 = ((hash_index == 32'd3) ? 1'b1 : 1'b0);

assign icmp_ln1016_3_fu_754_p2 = ((hash_index == 32'd2) ? 1'b1 : 1'b0);

assign icmp_ln1016_4_fu_760_p2 = ((hash_index == 32'd1) ? 1'b1 : 1'b0);

assign icmp_ln1016_5_fu_766_p2 = ((hash_index == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln1016_fu_736_p2 = ((hash_index == 32'd5) ? 1'b1 : 1'b0);

assign or_ln1016_1_fu_794_p2 = (icmp_ln1016_3_fu_754_p2 | icmp_ln1016_2_fu_748_p2);

assign or_ln1016_2_fu_808_p2 = (icmp_ln1016_fu_736_p2 | icmp_ln1016_1_fu_742_p2);

assign or_ln1016_3_fu_822_p2 = (or_ln1016_fu_780_p2 | or_ln1016_1_fu_794_p2);

assign or_ln1016_fu_780_p2 = (icmp_ln1016_5_fu_766_p2 | icmp_ln1016_4_fu_760_p2);

assign p_Result_1_fu_352_p13 = {{{{{{{{{{{{tmp_115_fu_270_p3}, {tmp_116_fu_278_p3}}, {tmp_117_fu_286_p3}}, {tmp_108_fu_176_p3}}, {tmp_s_fu_342_p4}}, {tmp_118_fu_294_p3}}, {tmp_119_fu_302_p3}}, {tmp_120_fu_310_p3}}, {tmp_121_fu_318_p3}}, {tmp_114_fu_224_p3}}, {tmp_122_fu_326_p3}}, {tmp_123_fu_334_p3}};

assign p_Result_2_fu_444_p14 = {{{{{{{{{{{{{tmp_124_fu_380_p3}, {tmp_125_fu_388_p3}}, {tmp_126_fu_396_p3}}, {tmp_127_fu_404_p3}}, {tmp_108_fu_176_p3}}, {tmp_127_fu_404_p3}}, {tmp_128_fu_412_p3}}, {tmp_107_fu_168_p3}}, {tmp_129_fu_420_p3}}, {tmp_130_fu_428_p3}}, {tmp_119_fu_302_p3}}, {tmp_124_fu_380_p3}}, {tmp_131_fu_436_p3}};

assign p_Result_3_fu_526_p14 = {{{{{{{{{{{{{tmp_132_fu_474_p3}, {tmp_133_fu_482_p3}}, {tmp_128_fu_412_p3}}, {tmp_134_fu_490_p3}}, {tmp_117_fu_286_p3}}, {tmp_135_fu_498_p3}}, {tmp_105_fu_152_p3}}, {tmp_115_fu_270_p3}}, {trunc_ln849_fu_506_p1}}, {tmp_111_fu_200_p3}}, {tmp_136_fu_510_p3}}, {tmp_136_fu_510_p3}}, {tmp_137_fu_518_p3}};

assign p_Result_4_fu_620_p14 = {{{{{{{{{{{{{tmp_138_fu_556_p3}, {tmp_139_fu_564_p3}}, {tmp_140_fu_572_p3}}, {tmp_141_fu_580_p3}}, {tmp_142_fu_588_p3}}, {tmp_143_fu_596_p3}}, {tmp_114_fu_224_p3}}, {tmp_108_fu_176_p3}}, {tmp_144_fu_604_p3}}, {tmp_145_fu_612_p3}}, {tmp_126_fu_396_p3}}, {tmp_132_fu_474_p3}}, {tmp_141_fu_580_p3}};

assign p_Result_5_fu_708_p13 = {{{{{{{{{{{{tmp_146_fu_650_p3}, {tmp_124_fu_380_p3}}, {tmp_147_fu_658_p3}}, {tmp_121_fu_318_p3}}, {tmp_148_fu_666_p3}}, {tmp_111_fu_200_p3}}, {tmp_149_fu_674_p3}}, {tmp_106_fu_160_p3}}, {tmp_150_fu_682_p3}}, {tmp_138_fu_556_p3}}, {tmp_151_fu_690_p3}}, {tmp_98_fu_698_p4}};

assign p_Result_s_fu_242_p13 = {{{{{{{{{{{{tmp_104_fu_144_p3}, {tmp_105_fu_152_p3}}, {tmp_106_fu_160_p3}}, {tmp_107_fu_168_p3}}, {tmp_fu_232_p4}}, {tmp_109_fu_184_p3}}, {tmp_110_fu_192_p3}}, {tmp_111_fu_200_p3}}, {tmp_112_fu_208_p3}}, {tmp_113_fu_216_p3}}, {tmp_114_fu_224_p3}}, {tmp_113_fu_216_p3}};

assign select_ln1016_1_fu_786_p3 = ((icmp_ln1016_3_fu_754_p2[0:0] == 1'b1) ? p_Result_2_fu_444_p14 : p_Result_3_fu_526_p14);

assign select_ln1016_2_fu_800_p3 = ((icmp_ln1016_1_fu_742_p2[0:0] == 1'b1) ? p_Result_4_fu_620_p14 : p_Result_5_fu_708_p13);

assign select_ln1016_3_fu_814_p3 = ((or_ln1016_fu_780_p2[0:0] == 1'b1) ? select_ln1016_fu_772_p3 : select_ln1016_1_fu_786_p3);

assign select_ln1016_4_fu_828_p3 = ((or_ln1016_2_fu_808_p2[0:0] == 1'b1) ? select_ln1016_2_fu_800_p3 : 13'd0);

assign select_ln1016_fu_772_p3 = ((icmp_ln1016_5_fu_766_p2[0:0] == 1'b1) ? p_Result_s_fu_242_p13 : p_Result_1_fu_352_p13);

assign tmp_104_fu_144_p3 = flame96[32'd73];

assign tmp_105_fu_152_p3 = flame96[32'd11];

assign tmp_106_fu_160_p3 = flame96[32'd55];

assign tmp_107_fu_168_p3 = flame96[32'd39];

assign tmp_108_fu_176_p3 = flame96[32'd81];

assign tmp_109_fu_184_p3 = flame96[32'd42];

assign tmp_110_fu_192_p3 = flame96[32'd27];

assign tmp_111_fu_200_p3 = flame96[32'd38];

assign tmp_112_fu_208_p3 = flame96[32'd72];

assign tmp_113_fu_216_p3 = flame96[32'd20];

assign tmp_114_fu_224_p3 = flame96[32'd47];

assign tmp_115_fu_270_p3 = flame96[32'd66];

assign tmp_116_fu_278_p3 = flame96[32'd28];

assign tmp_117_fu_286_p3 = flame96[32'd40];

assign tmp_118_fu_294_p3 = flame96[32'd70];

assign tmp_119_fu_302_p3 = flame96[32'd26];

assign tmp_120_fu_310_p3 = flame96[32'd71];

assign tmp_121_fu_318_p3 = flame96[32'd14];

assign tmp_122_fu_326_p3 = flame96[32'd25];

assign tmp_123_fu_334_p3 = flame96[32'd46];

assign tmp_124_fu_380_p3 = flame96[32'd84];

assign tmp_125_fu_388_p3 = flame96[32'd24];

assign tmp_126_fu_396_p3 = flame96[32'd53];

assign tmp_127_fu_404_p3 = flame96[32'd10];

assign tmp_128_fu_412_p3 = flame96[32'd43];

assign tmp_129_fu_420_p3 = flame96[32'd34];

assign tmp_130_fu_428_p3 = flame96[32'd89];

assign tmp_131_fu_436_p3 = flame96[32'd95];

assign tmp_132_fu_474_p3 = flame96[32'd69];

assign tmp_133_fu_482_p3 = flame96[32'd60];

assign tmp_134_fu_490_p3 = flame96[32'd32];

assign tmp_135_fu_498_p3 = flame96[32'd16];

assign tmp_136_fu_510_p3 = flame96[32'd74];

assign tmp_137_fu_518_p3 = flame96[32'd22];

assign tmp_138_fu_556_p3 = flame96[32'd77];

assign tmp_139_fu_564_p3 = flame96[32'd8];

assign tmp_140_fu_572_p3 = flame96[32'd63];

assign tmp_141_fu_580_p3 = flame96[32'd75];

assign tmp_142_fu_588_p3 = flame96[32'd2];

assign tmp_143_fu_596_p3 = flame96[32'd21];

assign tmp_144_fu_604_p3 = flame96[32'd54];

assign tmp_145_fu_612_p3 = flame96[32'd9];

assign tmp_146_fu_650_p3 = flame96[32'd57];

assign tmp_147_fu_658_p3 = flame96[32'd48];

assign tmp_148_fu_666_p3 = flame96[32'd6];

assign tmp_149_fu_674_p3 = flame96[32'd23];

assign tmp_150_fu_682_p3 = flame96[32'd5];

assign tmp_151_fu_690_p3 = flame96[32'd86];

integer ap_tvar_int_0;

always @ (flame96) begin
    for (ap_tvar_int_0 = 2 - 1; ap_tvar_int_0 >= 0; ap_tvar_int_0 = ap_tvar_int_0 - 1) begin
        if (ap_tvar_int_0 > 66 - 65) begin
            tmp_98_fu_698_p4[ap_tvar_int_0] = 1'b0;
        end else begin
            tmp_98_fu_698_p4[ap_tvar_int_0] = flame96[66 - ap_tvar_int_0];
        end
    end
end

integer ap_tvar_int_1;

always @ (flame96) begin
    for (ap_tvar_int_1 = 2 - 1; ap_tvar_int_1 >= 0; ap_tvar_int_1 = ap_tvar_int_1 - 1) begin
        if (ap_tvar_int_1 > 81 - 80) begin
            tmp_fu_232_p4[ap_tvar_int_1] = 1'b0;
        end else begin
            tmp_fu_232_p4[ap_tvar_int_1] = flame96[81 - ap_tvar_int_1];
        end
    end
end

integer ap_tvar_int_2;

always @ (flame96) begin
    for (ap_tvar_int_2 = 2 - 1; ap_tvar_int_2 >= 0; ap_tvar_int_2 = ap_tvar_int_2 - 1) begin
        if (ap_tvar_int_2 > 93 - 92) begin
            tmp_s_fu_342_p4[ap_tvar_int_2] = 1'b0;
        end else begin
            tmp_s_fu_342_p4[ap_tvar_int_2] = flame96[93 - ap_tvar_int_2];
        end
    end
end

assign trunc_ln849_fu_506_p1 = flame96[0:0];

endmodule //table_serch_hid_cal
