# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/nomoto/src/StagedLSH/ver1.3/soft/u200/hw/_x/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_regslice_control_userpf_2/pfm_dynamic_regslice_control_userpf_2.xci
# IP: The module: 'pfm_dynamic_regslice_control_userpf_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/nomoto/src/StagedLSH/ver1.3/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_regslice_control_userpf_2/pfm_dynamic_regslice_control_userpf_2_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'pfm_dynamic_regslice_control_userpf_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/nomoto/src/StagedLSH/ver1.3/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_regslice_control_userpf_2/pfm_dynamic_regslice_control_userpf_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pfm_dynamic_regslice_control_userpf_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/nomoto/src/StagedLSH/ver1.3/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_regslice_control_userpf_2/pfm_dynamic_regslice_control_userpf_2_slr.xdc
# XDC: The top module name and the constraint reference have the same name: 'pfm_dynamic_regslice_control_userpf_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/nomoto/src/StagedLSH/ver1.3/soft/u200/hw/_x/link/vivado/vpl/prj/prj.srcs/my_rm/bd/bd/ip/pfm_dynamic_regslice_control_userpf_2/pfm_dynamic_regslice_control_userpf_2.xci
# IP: The module: 'pfm_dynamic_regslice_control_userpf_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/nomoto/src/StagedLSH/ver1.3/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_regslice_control_userpf_2/pfm_dynamic_regslice_control_userpf_2_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'pfm_dynamic_regslice_control_userpf_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/nomoto/src/StagedLSH/ver1.3/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_regslice_control_userpf_2/pfm_dynamic_regslice_control_userpf_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pfm_dynamic_regslice_control_userpf_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/nomoto/src/StagedLSH/ver1.3/soft/u200/hw/_x/link/vivado/vpl/prj/prj.gen/my_rm/bd/bd/ip/pfm_dynamic_regslice_control_userpf_2/pfm_dynamic_regslice_control_userpf_2_slr.xdc
# XDC: The top module name and the constraint reference have the same name: 'pfm_dynamic_regslice_control_userpf_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
