//File Automatically generated by SystemC Netlister Time
#ifndef EMU_SCI_H
#define EMU_SCI_H
#include "systemc.h"
#include "xtlm.h"
#include "utils/xtlm_aximm_transview.h"
#include "utils/xtlm_aximm_transaction_logger.h"
#include "utils/xtlm_axis_transaction_logger.h"
#include "emu_dpa_mon0_0_sc.h"
#include "emu_dpa_hub_0_sc.h"
#include "emu_dpa_mon1_0_sc.h"
#include "emu_dpa_mon2_0_sc.h"
#include "emu_dpa_mon3_0_sc.h"
#include "emu_dpa_mon4_0_sc.h"
#include "emu_dpa_mon5_0_sc.h"
#include "emu_memory_subsystem_0_sc.h"
#include "emu_sim_ddr_0_0_sc.h"
#include "emu_xtlm_simple_intercon_0_0_sc.h"
#include "emu_icn_pass_0_0_sc.h"
#include "emu_sim_ddr_2_0_sc.h"
#include "emu_icn_pass_3_0_sc.h"
#include "emu_sim_xdma_0_0_sc.h"
#include "emu_sim_ddr_3_0_sc.h"
#include "emu_icn_pass_2_0_sc.h"
#include "emu_icn_pass_1_0_sc.h"
#include "emu_sim_ddr_1_0_sc.h"

class emu_sci : public xsc::utils::xsc_sim_conn_base {

public:
	//Exported sockets declaration
	
	//Constructor for the module
	emu_sci(const sc_module_name& module_name);
	SC_HAS_PROCESS(emu_sci);
	//Destructor for the module
	~emu_sci();
	
	void initConnModule();

protected:
void before_end_of_elaboration();

private:
	emu_sci(const emu_sci&);
	const emu_sci& operator=(const emu_sci&);
};
#endif
